### ISSUE TITLE
send 404 status

### ISSUE THREAD

**Issue by dv336699** [angular-ui/ui-router#1042]
When the page the user requests is not found, I just send him to a pretty page called /404.

I'm using

``` javascript
$location.path('404');
```

To redirect the user, how can I set the header code to be 404 when accessing that page?
thanks

**Comment by molerat619** [comment]
How should this be handled then? Instead of routing to a 404 page with ui-router, I actually just make a http request to the 404 document on the server-side? Or does .htaccess do it for me? Sorry, I don't exactly understand how to solve this problem yet.

I have an express server running on the server side.
