### ISSUE TITLE
Refreshing the browser doesn't refresh the ui-router's state when doing nested states.

### ISSUE THREAD

**Issue by CMCDragonkai** [angular-ui/ui-router#105]
In a situation like:

```
                .state(
                    'blog',
                    {
                        abstract: true, //this state is abstract, it provides an abstract base for children (only abstract states can have a default child state)
                        url: '/blog',
                        templateUrl: 'blog.html',
                        controller: 'BlogCtrl'
                    }
                )
                .state(
                    'blog.posts',
                    {
                        url: '', //empty url demonstrates that it is the default childstate of the ui-view
                        templateUrl: 'blog_posts.html',
                        controller: 'BlogPostsCtrl'
                    }
                )
                .state(
                    'blog.post',
                    {
                        url: '/:blogPostId',
                        views: {
                            '': {
                                templateUrl: 'blog_post.html',
                                controller: 'BlogPostCtrl'
                            },
                            'comments': {
                                templateUrl: 'blog_post_comments.html',
                                controller: 'BlogPostCommentsCtrl'
                            }
                        }
                    }
                );
```

When you go into e.com/blog/123 and go back to e.com/blog by refreshing the browser or a location refresh, it doesn't change the state back to blog.posts. It does do it when I use the back button or hit on a link that changes the url, but a direct location refresh doesn't.

**Comment by zeeshanjan82** [comment]
When I have defined my angular routes in angular-ui-router and also have configured the middleware in gulp or grunt, I notice that when I have state like: http://localhost:9000/login loaded in my browser and when I refresh the page , I am able to view the login page. But if I have nested states like : http://localhost:9000/login/signup loaded in my browser and when I refresh the page, I either get a blank screen or I get a REST Get error or I am redirected to the http://localhost:9000/login page but I really want to be in the signup state which is the child state of login.

**Comment by zacronos** [comment]
@zeeshanjan82, sounds like you understand the problem.  How to fix it will depend on how you have set up node to serve that single file, and whether you also have API calls or other URLs to handle.

If you are using Express.js on the server, the easiest thing to do (which may not always be best) is to add a wildcard route (`/*`) after adding all other routes, and have that new route serve your single file.  That means if a request is made to your server for an unknown URL (such as a URL serviced in the browser by angular), instead of getting a 404 error, your server will blindly serve your single file.

**Comment by zeeshanjan82** [comment]
thanks @zacronos I am using gulp and its plugins like watch and browsersync , in my case how can I do it. Do I need to include some middleware in my gulp file as a task?

**Comment by zacronos** [comment]
@zeeshanjan82, the question is how the file gets into your browser.  Are you running a node backend server like Express.js to serve the file on something like `http://localhost/...`?  Or do you just access the file locally, via some URL that starts with `file:///`?  Or are you uploading the file to a web hosting service somewhere?

**Comment by zeeshanjan82** [comment]
@zacronos  I have not yet created the backend yet, I have the frontend app which is an angularjs app and I have configured the gulp to have the app run on the url http://0.0.0.0:9000

**Comment by zacronos** [comment]
@zeeshanjan82, then in that case gulp is acting as your backend server.  I haven't used gulp that way, so I don't know what you need to do.  But, since you will eventually have a real backend, anything you do now with gulp is just going to be a temporary fix.

I would recommend that you ignore the problem for now, and revisit when you have started to build your backend.  Or, you could go ahead and create a skeleton backend so you can fix this problem the "right" way instead of a temporary fix via gulp.

**Comment by zeeshanjan82** [comment]
thanks @zacronos  I will surely follow your advice and will get back when I have implemented the backend.

**Comment by marcandrews** [comment]
Are you using any sort of authentication and then checking for authorization on ```$stateChange*``` in a run block?

_Sorry if my terminology is incorrect; I'm new to AngularJS._

**Comment by gopikrishnahm** [comment]
@bikashsharmabks: Where do you add this code to avoid browser refresh taking to home page.


angular.module('app').run(['$state', '$stateParams',
    function($state, $stateParams) {
        //this solves page refresh and getting back to state
}]);

**Comment by horiaIon** [comment]
@jonathanadler 

I have the same problem when i refresh my page manually, and it's caused because of the resolve function  from my state (i load some data from server). Did you managed to go pass this issue, without timeout?
Can you provide some code example?

Thanks,
Horia.

**Comment by lifemixture** [comment]
gopikrishnahm, thank U very much good man!
I spent week avoiding browser refreshing taking to home page.

**Comment by chetanganguly** [comment]
**@lifemixture @gopikrishnahm ** 
where we can we this code ..

_angular.module('app').run(['$state', '$stateParams',
function($state, $stateParams) {
//this solves page refresh and getting back to state
}]);_

i tried to add but still its going to home page ..can you have any sample..?
please reply ASAP

here is my config 
_BaseModule.config(["$stateProvider", "$urlRouterProvider", function ($stateProvider, $urlRouterProvider) {
 $urlRouterProvider.when('', '/login');
 $urlRouterProvider.otherwise('/notfound');
 $stateProvider
  .state("login", {
                url: '/login'
                , templateUrl: "Login/login.html",
                controller: "LoginController",
                controllerAs: "ctrl",
                title: 'Login',
                authenticate: false

            })
            .state("default", {
                url: '/default',
                templateUrl: "Login/login.html",
            })
            .state("home.abcd", {
                url: '/AccountsList',
                templateUrl: "abcd/abcd.html",
                controller: "abcdController",
                controllerAs: "ctrl",
                title: 'abcd',
                authenticate: true
            })
}]);_

**Comment by lifemixture** [comment]
Hi. I really stuck with this issue about half a year ago.
Injecting '$state' and '$stateParams' to run section helped me, I do not understand why. Than I removed them from run section and it was still working (like a magic).
Also do not forget to add 'base' tag to your main html.

Maybe this will help you
https://github.com/lifemixture/my-data-store/blob/master/public/js/app.run.js

**Comment by padhyakash** [comment]
@lifemixture 

this worked for me on local  machine but not on server, Any hint please?

$rootScope.$on('$stateChangeStart', function (event, toState) {
            if (!$rootScope.global.loggedIn && (restricted.indexOf(toState.name.split('.')[0]) !== -1)) {
                //console.log("restricted");
                event.preventDefault();
                $state.go('login');
            }
            if (toState.name === 'login' && $rootScope.global.loggedIn) {
                event.preventDefault();
                $state.go('home');
            }
        });

**Comment by Husnainsheikh84** [comment]
> ```js
> angular.module('app').run(['$state', '$stateParams',
>     function($state, $stateParams) {
>         //this solves page refresh and getting back to state
> }]);
> ```
> 
> This will solve the issue

Thanks , It worked for me
