### ISSUE TITLE
Allow absolute option for ui-sref-opts (common use case: email templates)

### ISSUE THREAD

**Issue by demetriusnunes** [angular-ui/ui-router#1081]
I am using to ui-sref in html email templates that of course need to have absolute urls.

I don't understand why ui-sref-opts restrict the use of the absolute option.

**Comment by shaneeb** [comment]
FYI, created a new PR #1750 to get this fixed. This is something I needed to fix urls displayed in browser status bar (or whatever it's called now). Basically my static assets are hosted on S3 and I have a custom domain set up on top. I use a base tag to specify S3 bucket for loading assets. Unfortunately the link in base tag is used instead of browser's address bar location when relative links are used. This has no effect functionally except that when hovering over the link, the url showed is relative to S3 one. Using absolute option seems to fix that but it's not allowed in uiSrefOpts (yet).

**Comment by nateabele** [comment]
Fixed in #1750.
