### ISSUE TITLE
Optional parameters errors throwing "uncaught object" in angular

### ISSUE THREAD

**Issue by charandas** [angular-ui/ui-router#1132]
Exists on master only.

I deliberately leave out some state configuration to create this issue:

``` js
$stateProvider
    // bunch of code ommitted
    .state('state1', {
      params: {
        paramName: {value: null}
      },
      url: "/state1/:paramName",
    })
    .state('state1.list', {
      params: {
        paramListName: {value: null}
      },
      url: "/list/:paramListName",
    })
```

Check out this [plunkr](http://plnkr.co/edit/05kkPlMm1XaJerWP5yIZ)

Breakpoint on angular.js L3801 is the only way of currently knowing that the error is:
`"Missing required parameter 'paramName' in state 'state1.list'"`

First off, the errors would be helpful in console output. Secondly, since module creation doesn't complete, the app never loads. In my usual experience with ui-router, I run my app, access a state and address concerns thereby.

In this case, however, the only way to get more context is to breakpoint. Let me know if you have trouble replicating the issue on the plunkr.

**Comment by adamreisnz** [comment]
I just ran into this issue as well. I would recommend updating the documentation [here](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_transition_) with a link to [here](https://ui-router.github.io/guide/ng1/route-to-component#accessing-transition), because as the OP mentions it states there it can be used to inject into controllers, but doesn't mention it can't be used for routing to components.
