### ISSUE TITLE
$stateChangeSuccess fires when url still has the previous state in it.

### ISSUE THREAD

**Issue by SimplGy** [angular-ui/ui-router#1151]
#### UI-Router Question

Inside of $stateChangeSuccess, the current window.location.hash is still the previous state.  This is not what I expect (since I'm in the success handler). Is this known? Is it a mindful decision?

    $rootScope.$on('$stateChangeSuccess', function (event, toState, toParams) {
      console.log window.location.hash // '#/myLastPage' <-- I expect this to be changed already.
      toState.name // 'myNextPage'  
      setTimeout(function(){
        console.log(window.location.hash) // '#/myNextPage'
      }, 1)
    });

 
#### Background (you can ignore this if you like)

I need to force a real, complete page refresh in [some situations](http://stackoverflow.com/questions/24292403/force-page-refresh-to-release-memory) to relieve pressure from built-up memory leaks.

An approach to do this is to watch the state changes, and do a full page refresh every 100th or so.

`$state.reload()` doesn't do a full reload. Neither does `$state.go($state.current, null, {reload: true})`. Neither does `window.location.reload(false)` (it's supposed to skip the cache, but actually doesn't re-parse the JS, which is a shame).

So, I'm using `window.location.reload(true)` to force a refresh. This uses the value of `window.location` at the time, so using `$stateChangeSuccess` requires this `setTimeout`.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by nolazybits** [comment]
I would like to reopen this issue as I can't use any angular related thing in the component I'm using.
I would have hoped we could use window.location...

**Comment by ProdigySim** [comment]
I ran into this issue because my controller wants to save data to `$history.state`. However, at the time the controller boots up, the URL is not correctly pointing at the current state's URL--so I cannot correctly access the history entry for the current page.

I thought perhaps I could listen to this event, but it seems that the event fires even before the controller is run.

I had the choice of either using `$timeout` or the `$locationChangeSuccess` to execute code after the URL was updated. This seems to work, but it would be nice if the History API state and ui router state were more in sync.
