### ISSUE TITLE
$state.go() in onEnter causes infinite redirect loop

### ISSUE THREAD

**Issue by rockwood** [angular-ui/ui-router#1169]
We use the master/detail ui pattern in many of our states, and I commonly want to pre-populate the detail side with the first result from the server. The problem is that doing a `state.go()` in the onEnter hook results in an infinite loop. Is there a common way to do this?

example plunker: http://plnkr.co/edit/14pumrI7QoDhDD73kJQr?p=preview.

``` javascript
$stateProvider
  .state('posts', {
      url: "/posts",
      templateUrl: "posts-index.html",
      controller: "PostsIndexController",
      resolve: {
        posts: function(Post) {
          return Post.all()
        }
      },
      onEnter: function($state, posts) {
        if (posts.length > 1) {
          $state.go('posts.show', { postId: posts[0].id });
        }
      }
    })
    .state('posts.show', {
      url: "/:postId",
      templateUrl: "posts-show.html",
      controller: "PostsShowController",
      resolve: {
        post: function($stateParams, Post) {
          return Post.find($stateParams.postId)
        }
      }
    })
```

**Comment by prisonier** [comment]
@rockwood Hi, i don't really understand how can i be sure that the $state.go will be executed once the transition is over. I see that you did not give a delay, so in my logic it means that the function is executed whenever it is possible (maybe before end of transition). I suppose that i'm wrong because each time i refresh everything is ok but i would like to be sure.

thanks

**Comment by noblecraft** [comment]
@prisonier the call to $timeout returns immediately and allows the onEnter() function to terminate normally without calling $state.go().
