### ISSUE TITLE
Nothing is added to history when changing states on Internet Explorer on Windows Phone 8

### ISSUE THREAD

**Issue by bumblebeeman** [angular-ui/ui-router#1217]
When you visit a site built with Angular UI Router on Windows Phone 8/8.1 (unsure about 7), nothing is added to the browser history as you navigate between states, meaning a press of the back button (or a call to $window.history.back()) goes to the page you were on before you visited the site.

We initially thought this was an issue with the site we were building, but the Angular UI Router demo site is the same.

**Comment by cyberlif** [comment]
I have the same issue with UI Router v0.2.10 on the Lumia 1020 (WP8.1, IE 11).
While that particular browser isn't very popular yet, it is still a bit of a pain since once you press back, it will just display a blank page (both on the sample page as well as mine). I've tried to debug it, but Visual Studio didn't seem to notice that something was wrong.

**Comment by nateabele** [comment]
UI Router relies on Angular's `$location` service (which in turn relies on the underlying History/pushState API of the browser) to manage state changes. Unfortunately, if the underlying APIs aren't reporting changes, there's not much we can do. See http://diveintohtml5.info/history.html for properly detecting History API support.

**Comment by cyberlif** [comment]
Thanks, at least now I know where to look
