### ISSUE TITLE
Wizard form validation (not) possible.... Well very difficult anyway....

### ISSUE THREAD

**Issue by smcardle** [angular-ui/ui-router#1388]
Hi

If a form is broken up into a wizard then the form.$valid/$invalid only applies to the CURRENT displayed state and NOT to the entire containing form.

This makes form validation checking for say, enabling save buttons etc very difficult without using some kind of validation object on the $scope and $watches on each of the wizard forms partials.

We need to document a best practice example for users showing a standard way of checking a form.$valid/$invalid at each step in a wizard. (or a dedicated service to use for this as the ui-view team should know all the partials that will be used during compilation)

All available examples seem to deliberately avoid validation checks on multi-page form wizards, possibly because of this. 

Steve

**Comment by motin** [comment]
@ProLoser: Link is broken nowadays, but I found it had moved to https://github.com/angular-ui/AngularJS-StyleGuide/tree/master/modules/User - will check it out, thanks.

>> @smcardle Please post a link here when you do... I would be interested to see how you did it.
> I will do :)

Did you ever come around to doing anything with this?

**Comment by motin** [comment]
@ProLoser I checked your implementation, which seem to be the same approach as @georeith suggested: To check validity of the **models** in an abstract parent state.

However, @smcardle is referring to the validity of the **form** (form.$valid/$invalid). 

Is it fair to say that doing multi-step forms with ui-router inhibits the ability to use [ngForm](https://docs.angularjs.org/api/ng/directive/form)'s $valid/$invalid feature?

The only workaround I see currently is to use ng-show and $state.includes() like so:

    <form name="projectForm" ng-controller="editProjectController" ng-submit="persistModel()" novalidate>
        <div ng-show="$state.includes('projects.new.step1')">
            <div ng-include="'crud/projects/step1.html'"></div>
        </div>
        <div ng-show="$state.includes('projects.new.step2')">
            <div ng-include="'crud/projects/step2.html'"></div>
        </div>
    </form>

... but it does not scale with large forms. Is there some other way to keep using ngForms validation or is the recommended approach to skip ngForm when using multi-step forms with ui-router?

**Comment by ProLoser** [comment]
Huh? I don't see why you're in any way limited whatsoever. I'm sorta confused. Yes you can put validation into the form AND into the state definitions both. I don't get how the router stops you from doing anything.

What are you talking about keeping or losing ngForms? I'm totally confused. Why do you not have a form inside of every single state? Like validate each step as it's own individual form.

**Comment by motin** [comment]
> What are you talking about keeping or losing ngForms? I'm totally confused. Why do you not have a form inside of every single state? Like validate each step as it's own individual form.

Having a form inside of every single state makes the form.$valid/$invalid only applies to the CURRENT displayed state and NOT to the entire wizard.

Here is a plunkr showing the problem with that approach when using ngForm: http://plnkr.co/edit/KVxe7hGl2WbNpdetmn6k?p=preview

1. Fill out an invalid field on step 1. The form.$valid is set to FALSE
2. Go to step 2. The form.$valid is now TRUE
3. Even worse, go to step 3 and you are able to press the Submit button even though it has `ng-disabled="signupForm.$invalid"`

In step 2 and step 3, the form.$valid should still be FALSE since the input in step 1 is invalid, like it would have been in case the form was not broken down into steps loaded separately by ui-router. 

This is not the fault of ui-router itself, since the same effect would be observed if ng-if would be used to switch out the the form-steps. Anytime the DOM changes, the form element's contents is changed, and ngForm does it's job "as usual", thus only validating the current step available in the DOM tree. 

What this issue really is about is a current lack of documentation/FAQ or best practice to be achieve Wizard-style form validation.

**Comment by ProLoser** [comment]
You should be putting the form inside every state, yes. Why are you validating data for inputs you don't see on the screen before you? If you want to perform validation checks to see if an entire form is valid you can relocate the validation logic to a service or factory with some sort of validation method and run the method when you enter the state.

You're putting too much reliance (and business logic) emphasis on the HTML structure, which is always going to be brittle. Your plunker has no sorts of checks that stop you from changing steps based on validation.

Alternatively you could do is prevent people from changing steps until the current step is valid. 

If the DOM that contains your validation rules DOESNT EXIST, then WHERE do you expect these rules to come from? What you're describing is that essentially because HTML _was_ on the page (or even could eventually _be_ on the page) the router (or perhaps ng-form) should some how take all of that into account when calculating validity.

You're designing your wizard wrong.

Here is an example of a multi-step registration wizard that places validation rules into the the state definitions themselves. It also makes the entire form (and registration process) more stateful, and relocates most of the business logic and validation into an easily-testable factory. Using HTML as your source-of-truth for validation is nice and convenient, but not super reliable.

https://github.com/angular-ui/AngularJS-StyleGuide/blob/master/modules/User/User.js#L21-L62
