### ISSUE TITLE
TypeError: Object required (IE8)

### ISSUE THREAD

**Issue by zajca** [angular-ui/ui-router#1505]
I now everybody hates IE8 (I do too). But I try lastest UI-Router under IE8 and get this errors which I can't understand and didn't find similar issue.

I try solve it with es5-shin,html5shim,ie8, autopolyfiller, but non works, everytime I get same issue.

This error occured on first route load

```
 TypeError: Object required<div class=ng-scope ui-view="" ng339="10">
```

A this after click on ui-sref link.

```
 Error: unsupported HTMLEvents<div class=ng-scope ui-view="" ng339="11">
```

**Comment by jonny2779** [comment]
I'm also getting this error.

on this server: https://204.187.13.122/#/rebates

![screen shot 2015-04-23 at 9 50 32 am](https://cloud.githubusercontent.com/assets/3011407/7297330/461b0d6e-e99e-11e4-8ec8-2e5affd87af1.png)

The code for the page looks like this: https://gist.github.com/jonny2779/8f5ad2d769a3d1daec19
and the controller: https://gist.github.com/jonny2779/2ebdfc2f1be8574ffffd

This is a large project. I'm not sure how to get it all in plunkr and its not supposed to be out in the wild due to client requirements. I'm not telling them about the gists :)

**Comment by jonny2779** [comment]
I found the answer to this.

You need to have jquery showing up first on your index page. It needs to be loaded before angular. That will get rid of the ng399 error.

Then you need es5-shim (https://github.com/es-shims/es5-shim) loaded before angular.

That is what worked for me anyway.
