### ISSUE TITLE
forward slashe being replaced by %2F in the latest release

### ISSUE THREAD

**Issue by t0lkman** [angular-ui/ui-router#1557]
Forward slash is being replaced by %2F in the latest release (0.2.12).

**Comment by adambuczynski** [comment]
I ran into this (or similar) issue with hosting my Angular app (HTML5 mode) on S3 and using redirection rules to prevent 404's when a user types in a direct URL to a certain route.

Due to S3 limitations, these direct URL's needed to be rewritten to use the hash symbol, e.g. `example.com/some/path` would have to be rewritten to `example.com/#/some/path` so that S3 would serve the `index.html` correctly.

Angular's HTML5 mode then kicks in and automatically removes the `#/` part from the URL.

However, I found when using `$urlMatcherFactoryProvider.strictMode(false);`, this behaviour got broken and ui-router replaced the URL to `example.com/#%2Fsome%2Fpath` instead.

Removing the strict mode setting to false fixed the issue.
