### ISSUE TITLE
406 Not Acceptable with version 0.2.13

### ISSUE THREAD

**Issue by brgrz** [angular-ui/ui-router#1610]
I'm loading UI router from jsdelivr version 0.2.13 and I get 406 Not Acceptable on angular's

`xhr.send(post || null);`

The same goes for 0.2.12 but everything works fine with 0.2.11.

**Comment by brutaldev** [comment]
Not going to get involved in the flame war here, just want to add my two cents.

I ran into the exact same issue thanks to web.config settings recommended by H5BP so thanks @brgrz for figuring that one out. I agree with @brgrz here as well that the charset should be sent since this seems to be the general recommendation out there. It's unlikely that the requested change will cause any problems for existing users, however, changing the header to one without a charset certainly does.

**Comment by rluiten** [comment]
I ran into this yesterday, I actually created a http interceptor that checked the url path for where our template html files live and modified the Accept header to */*. It is a hack but I thought some one else who ends up here after a search might find the information useful. 

I did try to set the accept header to "text/html; charset=UTF-8" but that caused IIS to keep returning 406's unclear why.  using "*/*" for our path checked url land ending in html did not seem to risky

**Comment by RichardM99** [comment]
I also ran into this issue guys so thanks to everyone in the thread for pointing me in the right direction!

**Comment by Pharylon** [comment]
I put this inside my module's config:


    .config(["$httpProvider",
    function($httpProvider) {

      //$httpProvider.defaults.headers.common["Content-Type"] = "application/json";

      $httpProvider.interceptors.push(function() {
        return {
          "request": function(config) {
            if (config.url && config.url.endsWith(".html")){
              config.headers["Content-Type"] = "text/html; charset=utf=8";
              config.headers["Accept"] = "text/html; charset=utf=8";
            }
            else{
              config.headers["Content-Type"] = "application/json";
              config.headers["Accept"] = "application/json";
            }
            return config;
          }
        };
      });


};

**Comment by drewfreyling** [comment]
This is also a problem in 0.2.18
