### ISSUE TITLE
Infinite digest when loading url without anything after the #

### ISSUE THREAD

**Issue by LordWingZero** [angular-ui/ui-router#1616]
Angular version: 1.3.5
ui-router: 0.2.13

When I hit my URL with: index.html# or just index.html

the page and URL will flicker a few times before finally going to my location defined in $urlRouterProvider.otherwise('/otherwisetest');

I will get this about 6 times:
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []

**Comment by OverZealous** [comment]
OK, so it turns out for **me** this issue was caused by `angular-permission` module, which will cancel a state change on start if redirected to a page with permissions associated to it.

This is the same issue as #600, and if you are experiencing the `$digest issues`, I suggest you look into their workaround (which fixed the issue for me completely).

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
