### ISSUE TITLE
Custom UrlMatcher types cannot be decoded asynchronously

### ISSUE THREAD

**Issue by schmod** [angular-ui/ui-router#1634]
The example contained within the documentation for custom `UrlMatcherFactory` types implies that I should be able to implement a custom type that resolves some data from an AJAX call:

``` js
// Defines a custom type that gets a value from a service,
// where each service gets different types of values from
// a backend API:
$urlMatcherFactoryProvider.type('dbObject', {}, function(Users, Posts) {
  return {
    encode: function(object) {
      // Represent the object in the URL using its unique ID
      return object.id;
    },
    decode: function(value, key) {
      // Look up the object by ID, using the parameter
      // name (key) to call the correct service
      return services[key].findById(value);
    ....
```

After browsing the code, it doesn't appear that there is _any_ sort of support for asynchronously decoding custom URL parameters.
1.  This functionality would be very nice to have.  For my use cases, this would be a **much** cleaner and reusable way to asynchronously load things than `resolve`.
2.  We should update the documentation to avoid suggesting that this functionality currently exists.  

It sounds like the new `transitionProvider` magic explained in #1399 might be a prerequisite to getting this to work.  Thoughts?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by schmod** [comment]
I think that this is still a valid issue.

Resolves are a powerful feature, but I think they need to be used sparingly.  Decoding URL params into objects (possibly via an AJAX call, or a call to some other persistence layer) seems like it could potentially be a much more maintainable solution.

**Comment by nateabele** [comment]
Yeah, we can leave this open as a potential design issue. I'm not sure what injecting individual parameters would look like, but accessing unwrapped async values without additional ceremony would definitely be handy.

**Comment by christopherthielen** [comment]
I think this will be possible using transition hooks. A hook can add resolves on the fly. The hook could inspect the state params and create a resolve that fetches the data based on the param.

**Comment by christopherthielen** [comment]
(I don't think this belongs in the params layer, by the way)

**Comment by trisys3** [comment]
One reason for it to still belong in the params layer is `ui-sref-active`. For example, if we have a dropdown with a bunch of users, and the URL may not have the correct user, and the URL user may even be empty, how do you choose the correct item? I know we could do fancy things like re-resolve the user in the controller, then have `ng-class` instead of `ui-sref-active`, but it would be easier if this were done in the params.

One obvious pitfall is how to decide when the state is finally transitioned to/resolved, or whether it is OK for the user to not be known right away and what to show in the UI in the meantime.
