### ISSUE TITLE
Don't use reserved keywords as object properties

### ISSUE THREAD

**Issue by soroushhakami** [angular-ui/ui-router#1639]
Doing something like: 
```
$state.current.abstract
```

Will cause errors with some minifiers such as Adobes JsFileBuilder.
Perhaps it'd be a good idea to not use any of the reserved keywords (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) as object properties? And instead use something like 

```
$state.current.isAbstract
```

**Comment by scottohara** [comment]
This is also a problem with `eslint` and the `no-reserved-keys` rule.

http://eslint.org/docs/rules/no-reserved-keys

```
/*eslint no-reserved-keys: 2*/

$stateProvider.state("foo", {abstract: true, ...});
```

`2:28 - Reserved word 'abstract' used as a key`

@soroushhakami 's suggestion of `isAbstract: true` seems like a logical replacement.

**Comment by scottohara** [comment]
FYI, eslint 1.0.0 has deprecated its `no-reserved-keys` rule; and merged it with the `quote-props` rule.
(because both rules needed to maintain the same list of reserved words).

With `quote-props`, reserved words can be used as properties as long as they're quoted, so `{"abstract": true, ...}` is valid and should not throw a warning.

**Comment by eddiemonge** [comment]
This seems like a silly thing that the builders should fix
