### ISSUE TITLE
Function to get the state that matches a path

### ISSUE THREAD

**Issue by pirhoo** [angular-ui/ui-router#1651]
Hi guys,

I'm in a situation where I want to retreive a state (and its parameters) using an URL. I didn't find anything about that in you documentation. I tried to combine `$urlMatcherFactory` and `$state` without result.

I'm thinking about something like:

``` javascript
// Where 'state' would contain the name of the states, its parameters, etc
var state = reverse("file/54984e5a3c9e2da72bcdddad");
```

Best !

**Comment by mambax** [comment]
> var match = privatePortion.url.exec(url);

A question herefore @christopherthielen , your docs [URLMatcher](https://angular-ui.github.io/ui-router/site/#/api/ui.router.util.type:UrlMatcher) states a second argument called `searchParams `, which you do not mention in the quoted line. We would need to match an absolute URL against our states, with your explanation all matches fail since `match` is (obviously) null. We see that the parameter is optional, but how can he match it without the parameters?

Any advice?
Thanks in advance.

**Comment by vodich** [comment]
Can you decorate state in main config and have the $$state available trought application
```
_.each($state.get(), function(state) {
      var privatePortion = state.$$state();
      var match = privatePortion.url.exec(url);
      if (match) console.log("Matched state: " + state.name + " and parameters: " + match);
});
```
I get  state.$$state is not a function

**Comment by mambax** [comment]
This how we did it and it works, tell me if it works for you:

```
  angular.module('app')
        .config(['$stateProvider', function($stateProvider) {
            // Reveal internal state representation
            $stateProvider.decorator('parent', function(internalStateObj, parentFn) {
                internalStateObj.self.$$state = function() {
                    return internalStateObj;
                };
                return parentFn(internalStateObj);
            });
            }
        }])
        .run(...);
```

Access it later with:

```
var privatePortion = state(*).$$state(); //Where state is a ui-router-initialized state (e.g. in a $stateChangeSuccess function
```

**Comment by christopherthielen** [comment]
Note that in ui-router 1.0,  the `$$state()` accessor is created by default.

**Comment by vodich** [comment]
This is probbably the gotcha
`//Where state is a ui-router-initialized state (e.g. in a $stateChangeSuccess function)`

I want to access it in my controller or directive

**Comment by christopherthielen** [comment]
@vodich you can access the using `$state.get('stateName')` from wherever you want

**Comment by mambax** [comment]
You can get them from the injector('$state') or $state itself.
I am mobile right now, but try $state.get('whateverstate') and you should be fine :)

**Comment by vodich** [comment]
What I wanted  was `$state.get('whateeverurl') ` not `$state.get('whateverstate') `
I solved the problem by going trough all states in loop and finding which one matches the url but thought it would be nice if I can paste whole url and just get the state from it but that didn't work. maybe because my router version is not 1.0

**Comment by mambax** [comment]
You can, there is a URLMatcher for that. If noone answers until tomorrow (when i get back to my desk) i will help more. But since you already solved it on your own you have it. I (not disrespecting your effort, just remarking) honestly would still give a look at the matcher, coz its tested and well woven into the ui router :)
