### ISSUE TITLE
$state.href should not decode parameters

### ISSUE THREAD

**Issue by thomack** [angular-ui/ui-router#1655]
Hi Guys,

When you want to build an URL from a $state with typed parameters, you expect the method $state#href to take a typed params Object.

For exemple, for an url with an int param : 
You expect : $state.href('mystate', {id: 123});
Instead of : $state.href('mystate', {id: '123'});

While this is not a problem for int type (because parseInt work on int as well), it is a source of trouble for bool parameters or any other custom type.

When you call $state.href('mystate', {someBoolParam: false}), the boolean param is decoded first (with : parseInt(val, 10) !== 0), and the result is 1. Disturbing... ;)

In my opinion, $state.href should not decode parameters by default, or should provide a way to skip this behavior.

**Comment by christopherthielen** [comment]
It seems this was fixed in 0.2.14 by adding the `normalize()` method which checks if the value is of the parameter type: `paramtype.is(val)` 

This allows the type's `.is()` function to check if the value is already (for example) a boolean.
This enables both `$state.go('mystate', {id: 123})` and `$state.go('mystate', {id: '123'})`
