### ISSUE TITLE
UIRouter not working inside an iframe

### ISSUE THREAD

**Issue by natcohen** [angular-ui/ui-router#1712]
I'm using UIRouter inside an iframe and the route doesn't seem to link to the controllers...

Here is how I configure the states:

     $stateProvider.state('main',
           {url: "/main",
                 views: {
                     '': { templateUrl: "/partials/main", controller: "MainCtrl" },
                     'private@main': {templateUrl: "/partials/prv-client_list", controller: "PrvClientListCtrl"}
                 }
           }
     );

I set up my iframe as follow:

      iframe(src="partials/main.jade")

and my ui-view inside main.jade

      div(ui-view='private')

The problem is that my controller (PrvClientListCtrl) is never called. The same configuration works when I'm not using it in an iframe.

**Comment by michaelcox** [comment]
I've never actually tested it, but I'm not surprised that an iframe does not hear the same hashchange events from the parent window.

Maybe try something like this in order to relay hashchange events down to the iframe?
http://stackoverflow.com/questions/26034204/unify-the-routing-urls-for-independent-pages-rendered-inside-an-iframe

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by KrzysztofKowalskiKainos** [comment]
This issue still occurs - there is a workaround as navigation works if **location** is set to false in **options**. However this is not ideal solution as our app is used both in iframe and as host app and without location the url is not changed...
