### ISSUE TITLE
Nested views side-by-side on DOM

### ISSUE THREAD

**Issue by enapupe** [angular-ui/ui-router#1715]
Is it possible to arrange the traditional nested view schema but using side by side elements?

I have it working with <ui-view> inside the previously loaded view, so it becomes:
/ ui-view
/ - ui-view
/ - / - ui view

I'm building a parallel animation so I need the following structure:
/ ui-view
/ ui-view name="second"
/ ui view name="third"

So, all elements must be siblings on the DOM, not children of the previous.

Is it possible? I think that the view name should help but I couldn't find in the docs anything about ...

**Comment by michaelcox** [comment]
I don't think what you're trying to do is the intent of ui-router. Another way to approach this is to have a containing view that optionally loads the correct directives. Rather than putting all of your logic in a ui-router controller and expect to render it with a ui-view, create separate directives for all of those "views" and then load the directives as necessary.

``` html

<div ng-switch on="some-route-params-maybe">
    <div ng-switch-when="first">
        <my-custom-1 /> <!-- optionally loaded directive, sibling of #3 below -->
    </div>
    <div ng-switch-default>
        <my-custom-2 /> <!-- optionally loaded directive, sibling of #3 below -->
    </div>
</div>
<my-custom-3 /> <!-- sibling directive -->
```

Using this approach it probably makes sense to control the url via querystrings, in which case you might not even have a need for ui-router and instead just rely on $location.search (https://docs.angularjs.org/api/ng/service/$location)

**Comment by enapupe** [comment]
Thank you. 
I managed to animate the elements within the original children structure.
