### ISSUE TITLE
semantic ui modal not closing on login after logout 

### ISSUE THREAD

**Issue by alaksandarjesus** [angular-ui/ui-router#1762]
I am using a signup modal form of semantic-ui css framework. On first login the modal is disappearing.On logout, if i login again, the modal is not disappearing.

If i refresh the page the modal is works fine for only one time.

I am using angularjs with ui-router and here is a short 1 min video that explains the problem.

https://www.youtube.com/watch?v=gQpt-oQI7QE&feature=youtu.be

You can download the whole code to test drive from your localhost from Here.

https://github.com/alaksandarjesus/mockuponline

Alternatively you can visit

http://plnkr.co/edit/auurNcTpEk5izurQI6os?p=preview

Thanks in advance.

**Comment by nateabele** [comment]
The plunkr works fine for me. I just needed to add `<script>document.write('<base href="' + document.location + '"/>');</script>` to the top of the `<head />`, so that the template path was correct.

After that, I could log in and log out any number of times. The problem is likely with some other part of your code that handles authentication and modal management, not UI-Router.
