### ISSUE TITLE
Issue with HTML5Mode

### ISSUE THREAD

**Issue by renesansz** [angular-ui/ui-router#1764]
Having an issue with **v0.2.13** wherein you enable the **html5mode**,
the routes seems to work well, but when you refresh the browser it says **'Page not found'** error
and you have to go back to the base url to make the page work again and I have to manually navigate by clicking the links in which were I left off.

**Comment by eddiemonge** [comment]
Thats an issue with your server not correctly redirecting pages back to your root index.html (or whatever your root file is). Not ui-router related. html5mode merely makes hash-less urls but it is up to you use a server with the correct redirects.

**Comment by renesansz** [comment]
But should it work also with `<base href="/">` ?

**Comment by eddiemonge** [comment]
Not if your server is trying to serve `/some/route/that/doesnt/exist/on/the/file/system`. The only page that probably exists is `index.html`. Thus when that page above is requested, your server (apache|nginx|whatever) tries to serve a page that doesn't exist instead of serving the `index.html` page. Something like http://serverfault.com/questions/400042/rewrite-rule-to-redirect-all-subpages-to-a-single-page (quick google, didnt fully read everything)

**Comment by nateabele** [comment]
This is not a UI-Router issue.
