### ISSUE TITLE
ui-sref-active not working with custom parameter type

### ISSUE THREAD

**Issue by emertechie** [angular-ui/ui-router#1785]
I'm trying to use a custom type ([$urlMatcherFactor.type](http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$urlMatcherFactory)) to hold some complex application state in a URL query parameter but that seems to break `ui-sref-active`.

Example using simple string parameter type: http://plnkr.co/edit/Go0RCY?p=preview
Now using custom parameter type: http://plnkr.co/edit/yX7Z17?p=preview

Click the bottom links to navigate between states (Best to pop out both examples so you can see URL changes). You'll notice in the second example that the navbar doesn't highlight the "(with param)" ui-sref links.

Is this a bug or have I done something wrong with the custom type definition?

Thanks

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by nite2** [comment]
This issue is still valid, at least for me. When a custom type is defined and this custom type evaluates to object (not primitive) ui-sref-actie does not work
From what i found out the problem lies in  equalForKeys function which does not compare objects property ie:

if (a[k] != b[k]) return false

Changing this comparision to !angular.equals(a[k],b[k]) seems to fix the issue
