### ISSUE TITLE
Open in new tab does not work on command-click of non-anchor element

### ISSUE THREAD

**Issue by andyfleming** [angular-ui/ui-router#1797]
When an element like a `<tr>` has a `ui-sref` attribute, <kbd>⌘ command</kbd> + <kbd>click</kbd> is ignored.

Example:

```html
<tr ng-repeat="item in items" ui-sref="view-item({itemId:item.id})">
```

**Comment by andyfleming** [comment]
I came up with a work-around here:
http://stackoverflow.com/questions/28872720/ui-sref-on-tr-element-wont-open-in-new-tab

Here's the code:

```js
app.run(function($rootScope, $state) {

    $rootScope.navigate = function($event, to, params) {

        // If the command key is down, open the URL in a new tab
        if ($event.metaKey) {
            var url = $state.href(to, params, {absolute: true});
            window.open(url,'_blank');

        } else {
            $state.go(to, params);
        }

    };

});
```

```html
<tr ng-repeat="item in items" ng-click="navigate($event, 'view-item', {itemId:item.id})">
```

**Comment by JamesHenry** [comment]
This is an interesting one, because I think the browser behaviour is actually expected and consistent in this case.

The `ui-sref` attribute, as well as handling the state navigation logic, dynamically adds an `href` attribute to the element in question and references the resolved URL which relates to the ui-router state declared within the `ui-sref`.

`href` is a valid HTML attribute on `a`, `area` and `link` tags to offer a way to create a conceptual link between two resources. Modern browsers allow you to follow the reference of one of these valid tags in a new tab by pressing <kbd>command</kbd> + <kbd>click</kbd>, as you have noted.

Whilst ui-router is indeed still adding the `href` onto the `tr` in this case, it is not part of the HTML spec (and therefore not respected by the browser) for a `tr` to link to another resource.

That being said, with modern SPAs we are often straying from the exact (often limited) intentions of HTML and I think it makes sense for ui-router to consider supporting cases such as this (where the user expectation is that the "link" on the element they are clicking performs like any other).

In the meantime a more semantic, but admittedly more verbose, solution may be to simply use anchor tag(s) within your `tr`...

**Comment by andyfleming** [comment]
Good points, @JamesHenry. I had a similar conversation with a colleague.

I think that it's important for the behavior to be consistent. If a `<tr>` element was not intended to have a `ui-sref` then it shouldn't function at all. Because it does function, I think it should behave consistently (and respect modifier keys for opening in a new tab).

**Comment by sklyukin** [comment]
Similar issue - I'm using `ui-sref`on `<div>` element, as my element contains multiple rows, columns and a lot of info. So middle mouse button click is not working for me, as well as `command` + `click` .

**Comment by eddiemonge** [comment]
> If a <tr> element was not intended to have a ui-sref then it shouldn't function at all

That means we would have to whitelist all the things it is allowed on. This is not great because what if we put it on a directive element that then puts it on an anchor. That original things wouldn't pass it through.

@sklyukin you can wrap all that with an anchor tag and put display block on it to treat it like a div.

I am on the fence about this. On one hand, we should be using standard semantic things and letting the browser do their thing with them. On the other, we should be flexible enough to all things like adding a sref on a tr. If a user really wants to do that then they should probably be prepared to extend that tr functionality to include things like option clicking.

**Comment by sklyukin** [comment]
@eddiemonge yes, thx, that will work. But in case I will have another button inside my element, that approach will be wrong.


>HTML 5 states that the <a> element "may be wrapped around entire paragraphs,  lists, tables, and so forth, even entire sections, so long as there is no interactive  content within (e.g. buttons or other links)".

**Comment by eddiemonge** [comment]
> But in case I will have another button inside my element, that approach will be wrong.

stopPropagation in that case.

**Comment by sklyukin** [comment]
yes, it will work, just it will be against HTML 5.

**Comment by eddiemonge** [comment]
Im inclined to close this. If people want to add this functionality, they can use a directive to accomplish it.
