### ISSUE TITLE
Server side rendered pages and ui-view causes controller to run multiple times

### ISSUE THREAD

**Issue by aidanlister** [angular-ui/ui-router#1807]
On the first hit to a page I want to send a fully rendered page back to the user. This works fine if javascript is disabled, but if javascript is enabled then angular-ui-router looks up the state and renders into ui-view on top of the existing content. Is there a way to disable this on the first page load somehow? Perhaps a toggle to ui-view that some state is already loaded?

**Comment by stephenjwatkins** [comment]
We are running into the same issue. We want to send a fully-rendered page to the client from the server on first page load, and then have JavaScript take over from that point onward. Not only are the controllers rendering multiple times, but directives attached to the DOM are also linking several times. This is causing a lot of issue in our code.

We really need a way to be able to manage the initial page load (with server-generated content) that works properly with UI router.

Here's a plunker that I setup with a setup that's similar to ours (server generated nested views): http://plnkr.co/edit/7PHW27ou2Ot2AKDwsIeV

If you run the plunker, you can see the console output running the controllers and directives multiple times. If you take out the server generated content and replace it with just `<main ui-view></main>`, it works properly (no duplicated code running).

**Comment by nateabele** [comment]
See [$urlRouterProvider.deferIntercept()](https://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouterProvider#methods_deferintercept).

Please refer further questions to StackOverflow. http://bit.ly/UIR-SOF

**Comment by aidanlister** [comment]
Here's my attempt at a solution: https://stackoverflow.com/questions/29446178/prevent-angular-ui-router-from-re-loading-ui-view-on-first-page-load/29453450#29453450

**Comment by rapilabs** [comment]
I'd just like to clarify the issue here.  Controllers are run multiple times if ui-router encounters the following pre-rendered html:

```html
<div ui-view>
  Some content
  <div ui-view>
    Some nested content
  </div>
</div>
```

The simplest solution at the moment is to simply filter out any nested `ui-view` when pre-rendering.

It doesn't seem to make sense for ui-router to attach controllers to nested `ui-view` as the content will be replaced anyway.  It would be great if the uiView directive could detect its context, but I understand how hard that could be, so I don't expect ui-router to solve this.
