### ISSUE TITLE
"Global" states, aka how to properly inject the language

### ISSUE THREAD

**Issue by l0rn** [angular-ui/ui-router#1824]
Hello,

i'm facing following problem, i want to integrate the language into my url slug to have localized permalinks. So effectively "example.com/de/foo" shoud route to the german version of foo.

So i have written this root controller

```
$stateProvider.state('root',{
        url: '/:language',
        abstract: true,
        template: '<ui-view/>',
        controller: 'rootCtrl'
    });
```

This works but have the really annoying side effect that i now have to write 
```
$state.go(root.somestate, { language: currentLanguage } )
```
in every single ui router link.

What I want is a "global" stateParam... so the router should recognize that i come from a /de state and i most certainly want to keep this param.

Could we integrate something like that in ui-router or is it already somehow possible and i'm missing something out here?

EDIT: I thought about that a bit more and try to make my question more specific. What I want is a feature where the ui-router remembers my parent state params. I think this is needed very often, not only when trying to implement localized URLs.

**Comment by acollard** [comment]
@l0rn The parent stateParam is kept. You shouldn't need to specify it while you are traversing between sub states (ex. root.someStateA -> root.someStateB). You should only need to include the language param if you are entering from a state that is not the root or a child (ex. login.success -> root.someStateA) because it won't already have resolved this information.

We do this a lot and it works for us. One thing to remember is that the language won't be accessible to anyone other than the root state. If you need to make it accessible then you will likely want to pull it out of stateParams and return it on the resolve.

```javascript
$stateProvider.state('root',{
        url: '/:language',
        abstract: true,
        template: '<ui-view/>',
        resolve: {language: ['stateParams',function(stateParams){ return stateParams['language'];}]},
        controller: 'rootCtrl'
    });
```

**Comment by l0rn** [comment]
@acollard wow, thanks. you just solved one of our biggest problems of our project. i actually googled a lot for this and never found a satisfying solution. I think this should be documented somehow since i'm most certainly not the only one looking for this behavoir. I would provide this language inheritance as example in the guide under "nested states". i start an approach when i get home.

many thanks again!

**Comment by acollard** [comment]
@l0rn Happy to help.
