### ISSUE TITLE
resolve behavior is 'wrong'

### ISSUE THREAD

**Issue by arieljake** [angular-ui/ui-router#1827]
From the docs:

'resolve is an optional map of dependencies which should be injected into the controller.'

Wouldn't it be as simple but more powerful if "resolve is an optional map of data/functions which should be injected into the $scope of the controller?"

One issue is that the controller's constructor is only called once. But anyway, the controller has access to the $scope, and can still access these dependencies as properties of it anywhere it wants, including the constructor, but if resolve injects to the $scope, then binding can do its work.

**Comment by acollard** [comment]
@arieljake I would argue you are making it less powerful by forcing dependencies to be placed on the scope.

There is nothing stopping you from just placing the data/function on the scope once your controllers constructor is called. Data is fine, but I would be hesitant to put functions not from the controller directly on the scope, since the intention of the controller is to encapsulate the logic for the view. In most cases it is better to add a controller function that calls your external dependency. 

Also your statement "One issue is that the controller's constructor is only called once." isn't 100% accurate. It is only called once for every instance of the controller. Every time you enter the view that requires the controller it will be created.

Lots of information can be put in the resolves, you may not want it all on the scope. The controller should be the one who controls what is accessible on the scope.

**Comment by arieljake** [comment]
Thanks for the reply.

When you said "Every time you enter the view that requires the controller it will be created" I realized that something was amiss. I was not seeing that behavior, but it was because Ionic framework implemented a caching behavior that re-uses views and their controllers, therefore disrupting the use of resolve. When the constructor is called very time the state is entered, the issues I was trying to address, namely updating state to reflect state params, are moot.

Thanks again.
