### ISSUE TITLE
Simplify Redirects (Alias URLs?) 

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#185]
See @ksperling comment in https://github.com/angular-ui/ui-router/issues/174#issuecomment-19370489:

I like the idea of aliases, but I'd be okay with just adding a new redirect method to $stateProvider. Like this:
```$stateProvider.redirect("/fancypants", stateNameOrURL)```

If we did allow urlAlias then I'm not too worried about the various parent/child alias combinations. If that's what the user wants, they should get it.

This also brings up the point of too many providers, see https://github.com/angular-ui/ui-router/issues/184

**Comment by mkoczorowski** [comment]
Hi guys,
I have a weird problem
<pre><code>
$urlMatcher.rootLocale 'en'

$states.state 'app.locale',
			url: $urlMatcher.compile
				en: '/'
				fr: '/:locale'
			views:
				'@': '/modules/dashboard/views/dashboard.html'
</code></pre>
No view is being loaded when I visit '/' route
<pre><code>
$states.state 'app.locale.home',
			url: $urlMatcher.compile
				en: '/home'
				fr: '/:locale/dom'
			views:
	                       '@': '/modules/dashboard/views/dashboard.html'
  </code></pre>
Visiting '/home/ in this case results redirecting to '/'. 

It looks like the '/' route doest really work. Does anyone of you encounter this problem before ?

**Comment by mkoczorowski** [comment]
anyone ?

**Comment by gerisztein** [comment]
I have the same problem. I always go to $urlRouterProvider.otherwise when I try to not use the :locale prefix. But, if I change the state using $state.go, it works properly. I'm kinda stuck in this issue also @mkoczorowski.

**Comment by mkoczorowski** [comment]
Yeah, so close.. Let us know if you managed to figure this on out @gerisztein

**Comment by gerisztein** [comment]
So do you, @mkoczorowski 
I'm trying a different approach today, let's see what happen. If I make any progress I'll let you know.

**Comment by mwarren2** [comment]
@vizo I agree with you that multilingual apps are complicated with ui-router as it stands. I totally agree with you that 'It would be so much easier if ui-router would support alias urls for same state'. Your solution is possible (thankyou for your work), but it comes with several 'musts' before you can start to use it. I suppose that there are good reasons why there must only be one URL per state, but actually a cow is a cow whether you call it 'cow' in english or 'vache' in french. And the URL '/cow' and the URL '/vache' is the same URL for those who have to deal with SEO in multilingual apps, they both use exactly the same state.

**Comment by mwarren2** [comment]
I had another brilliant idea (hack I suppose). See the following code:

		$stateProvider.state('it-chiantiClassico', {
			url: '/it/chianti/vino/chiantiClassico',
			templateUrl: 'modules/core/views/chiantiClassico.client.view.html'
		});
		$stateProvider.state('en-chiantiClassico', {
			url: '/chianti/wine/chiantiClassico',
			templateUrl: 'modules/core/views/chiantiClassico.client.view.html'
		});

Since at the moment I have to create a state for every language URL I could put the language in front of the state name, such as 'it-chiantiClassico' and 'en-chiantiClassico' and then change the ui-sref on the fly when I click to change languages.

ui-sref="{{currentLang}}-chiantiClassico"

But ui-sref doesn't listen for changes so that can't work.

**Comment by gerisztein** [comment]
Actually this is exactly the approach I'm working on.
I generate all the states dynamically with the language prefix also.

Tomorrow I'm going to work on a custom directive to emulate ui-sref behavior.

Se riesco a finirlo te lo faccio sapere ;)

**Comment by mwarren2** [comment]
Thanks Lucas for your reply.

I suppose another idea along the same lines would be a state url with params:
url: ':slashPlusLang/:someHyphenatedPhraseInLangForSeo/'

This would need only one url per state, so it might fit in with ui-router just as it is, but slashPlusLang is not particularly elegant, although it might to be the only way if there is a root lang which doesn't appear,
and of course ui-sref would need a $watch on it for when the language changes.

**Comment by vizo** [comment]
Thanks for all your thoughts!

I was also trying a lot of other approaches before i came to this, but it seems that all others are more complicated on the end. You will figure it out when your app gets bigger.

**Comment by mkoczorowski** [comment]
@vizo any idea about the bug we are descibing above ? We would appreciate your help

**Comment by mwarren2** [comment]
I've reached a simple solution to the multi-language problem which is suitable for my needs.
It uses a nested state solution with the locales at the root.

It is not completely DRY: templateURLs are still repeated, but nested states are still possible. 

Ok, my site is not going to be complicated so I haven't tried this with more esoteric combinations, but it looks like I have stayed within normal ui-router semantics.
So to those that are interested I include my routing below.

There is an abstract state for each locale at the root, and in my example there are two locales, 'en' and 'it'.
I also found that I had to provide a template with just '<ui-view/>' for each abstract state, otherwise nothing appeared.

The root abstract states have urls like '/it' - or, in the case of english, a blank string '' - because on my site 'en' locale has no url prefix.
Then the nested 'home' state for the home page has blank urls because the home page just uses the root locale prefixes.

		$stateProvider.state('en', {
			url: '',
			abstract: true,
			template: '<ui-view/>'
		});
		$stateProvider.state('it', {
			url: '/it',
			abstract: true,
			template: '<ui-view/>'
		});
		
		$stateProvider.state('en.home', {
			url: '',
			templateUrl: 'modules/core/views/home.client.view.html',
		});
		$stateProvider.state('it.home', {
			url: '',
			templateUrl: 'modules/core/views/home.client.view.html',
		});
		
		$stateProvider.state('en.chiantiClassico', {
			url: '/chianti/wine/chiantiClassico',
			templateUrl: 'modules/core/views/chiantiClassico.client.view.html',
		});
		$stateProvider.state('it.chiantiClassico', {
			url: '/chianti/vino/chiantiClassico',
			templateUrl: 'modules/core/views/chiantiClassico.client.view.html',
		});

-------------------------

Now, there's the problem of ui-sref. On a multi-lingual site it's basically unusable because it won't respond to an change of the language - e.g. from 'en.home' to 'it.home'.

So, to solve the href problem I considered a couple of solutions.
1) Calling a function in ng-href from the view that called $state.href(). This would be tidy, but it has the usual $scope.apply() problem of being called multiple times.
2) Creating an adhoc map of 'state:url' filtered for the current locale from all states in $state.get() each time the language changes, which is not particularly often. Then I do all the look-ups in my header from the map using ng-href. 
data-ng-href="#!{{urlsInLanguage.chiantiClassico}}".

Code for making the map when the language changes;

			$scope.currentLang = $scope.currentLang || 'en';
			$scope.urlsInLanguage = {};
			var states = $state.get();

			//filter for all states that have currentLang in them
			states.filter(function(currentState){
				if(currentState.name.substring(0,2) === $scope.currentLang){
					return currentState;
				}
				return null;
			}).map(function(thisState){	
				//put each url value with stateName key into our object map
				//the key should be just the basic stateName, we don't want the locale on the front
				$scope.urlsInLanguage[thisState.name.substring(3)] = $state.get($scope.currentLang).url + thisState.url;
			});

**Comment by gerisztein** [comment]
Hi! I'm using another method as I already have lodash running on my project I've decided to create the states dynamically using an object to set the templateurl, controllers and other settings for each state and the forIn function. I've reduced 200 lines in my code and I think it's kinda easy to maintain.

I already have some configurations for the routes for each state and an object dynamically generated that shows me which locales are available to use. In addition to this, I have something like this:

the object:

```js
var states = {
  'home': {
    'controller': 'HomeCtrl',
    'templateUrl': 'home.html',
    'params': {}
  }
}
```

the function
```js
_.forIn(states, function(prop, state) {
  _.forIn(available, function(props, locale) {
    $stateProvider.state(stateName, {
      data: {
        analytics: analytics,
        title: title
      },
      params: prop.params,
      resolve: resolve,
      url: url,
      controller: prop.controller,
      templateUrl: prop.templateUrl,
    });
  });
});
```

It solved my problem. It's not the prettiest solution but works like a charm.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by fxck** [comment]
any updates on this @vizo @gerisztein @mwarren2 ?

**Comment by KAnilKotha** [comment]
Has anyone tried this?

Sets the lang parameter to en and remains on the same state.
```script
<a ui-state="" ui-state-params="{ lang: 'en' }">English</a>
```
useful when using the `ui-state`s instead of `ui-sref`s.
