### ISSUE TITLE
controller as syntax doesn't work when controller written in coffeescript implicitly returns a function

### ISSUE THREAD

**Issue by inetfuture** [angular-ui/ui-router#1880]
See this plunker: http://plnkr.co/edit/G3zJHEyXsGPbTlQ3uk8U?p=preview

When the coffeescript controller definition implicitly returns a function, `controller as vm` doesn't work, while use `ng-controller` in template works.

**Comment by nateabele** [comment]
If you'd like to transpile your app to regular JavaScript and post a new plunkr, I'd be happy to debug it for you, but I don't read CoffeeScript.

**Comment by inetfuture** [comment]
Here you are: http://plnkr.co/edit/I2FaOhFQgjLiPdJ1pU5x?p=preview

**Comment by nateabele** [comment]
Yeah, I'm not really sure. It must be something particular to how Angular controllers expect return values.

All I know is, it works if I change this:

```javascript
  vm = this;
  vm.data = 'It does not work!';
  return function () {};
```

...to this:

```javascript
  var vm = this;
  vm.data = 'It does not work!';
  var func = function () {}
  return angular.extend(func, vm);
```

Internally, UI-Router just shells out to Angular's core `$controller` service, so it could be an issue there.  If you're suggesting that this issue is CoffeeScript-specific because of the implicit return value, I guess all I can say is, this is why I hate trying to read CoffeeScript and would never use it. :stuck_out_tongue: Sorry.

**Comment by davenaeder** [comment]
Just ran into the same problem. If you manually return false in your controller it will work as expected.

**Comment by wesleycho** [comment]
I did some investigation, and the culprit seems to be with Angular seeing a returned value of a function, and so returns that, assuming that that means it is an instance: https://github.com/angular/angular.js/blob/master/src/auto/injector.js#L843 . This behavior can also be observed for an object, as can be seen [here](http://plnkr.co/edit/Z7ufCakKOeOYcjPp9wu0?p=preview)

Given this behavior, this is not a UI Router bug, and I am closing this as won't fix - this is the type of gotcha that makes the implicit return of CoffeeScript in JS a bad idea, and as a result, this is something that a user needs to watch out for himself/herself.
