### ISSUE TITLE
$state.go does not regiester a new entry in the browser history when navigating to child state

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular-ui/ui-router#1888]
I have a case when I need to run parent state's controller to determine which child state needs to be loaded (which is why I cannot set it `abstract`). The issue arises when after loading of first child state, and navigating to another child state - pressing the browser's "Back" button will not redirect back to the first child state.

The issue is described in details in [StackOverflow Question](http://stackoverflow.com/questions/29683176/angular-ui-router-nested-states-browser-back-button-does-not-work-as-expec) and can be observed in this [Plunker example](http://plnkr.co/edit/Sh9Ulx4cgsCwzxqpZtpJ?p=preview)

I saw "[How to set up default child state](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-set-up-a-defaultindex-child-state)" in FAQ, but it's not quite my scenario, since I actually need parent state to run initially.

**Comment by nateabele** [comment]
It looks like, because the new transition is happening before the old one is fully finalized, that it's not getting `$location.replace()`'d properly. We have some new APIs that will allow you to do this somewhere other than the controller, which should be somewhat cleaner.

For now, I recommend using the `onEnter` hook instead of the controller to do your redirect.

**Comment by DmitryEfimenko** [comment]
I cannot get it to work even when placing the conditional logic and `$state.go()` call in to the `onEnter` hook. It gets into an infinite redirect state and crashes the browser.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
