### ISSUE TITLE
Would renaming the release folder to dist cause a lot of pain? 

### ISSUE THREAD

**Issue by djabraham** [angular-ui/ui-router#1913]
Thanks for this excellent extension to Angular and sorry in advance because this is going to sound peevish..

Seems that the release folder is filtered quite often when ui-router is deployed as a library. I have seen it in both SVN and GIT now, so it must be a popular entry on the default ignore lists.

Just saying..

EDIT: Dang, I just noticed it happens in ui-router-extras too.

**Comment by nateabele** [comment]
For anyone deploying via NPM/JSPM, we'd just have to update the `main` entry in `package.json`, and they probably wouldn't even notice. No idea how much disruption it would cause for other people. I'm not totally opposed to it (especially since it's kind of a standard), but I'd like to get some feedback from others first.

**Comment by eddiemonge** [comment]
probably needs some bower loving to only have the release files included as well

**Comment by eddiemonge** [comment]
Ideally the release files would only get added to the tag they are for. They probably should not be in master. Would require slightly changing the release process.

**Comment by christopherthielen** [comment]
Ijust ran across this  issue, and things have changed a lot since it was created.

> They probably should not be in master. Would require slightly changing the release process.

We've removed `release` from the `master` branch altogether.  We're bundling and publishing four packages out of the `master` branch:

- ui-router-core (npm)
- angular-ui-router (npm and bower)
- ui-router-ng2

- angular-ui-router is published to both bower and npm, and each package is built separately. 
- for backwards compat, those bundles still use `/release/angular-ui-router.js`


We're still publishing two `angular-ui-router` packages (npm and bower) from the `legacy` branch, but they are not built separately.  

The bower releases are now coming out of http://github.com/angular-ui/angular-ui-router-bower repo

**Comment by christopherthielen** [comment]
With all that said, this does not fix the original request.  I think it would be too much impact to change the release directory to dist at this point.  Closing as wont-fix
