### ISSUE TITLE
Problems with $state.reload reinitializing controller in IE11

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ui-router#1914]
Hi All, 
I am hitting a peculiar bug in IE 11 w.r.t state transitions. 
Now, I have the following line of code:
$state.go('state1.state2',{test:1},{reload:true}) 
When I run this in chrome and firefox everything works fine, and I don't run into any issues. 
However when I run the above piece of code in IE 11, the parameters are resolved, 
any promises that are associated with the state are also resolved, but the controller is not re-initialized/view is not refreshed. 

This problem seems to only happen when I run the app in IE, it works fine in FF and chrome. I am unsure as to how to proceed and debug the issue. Are there any events, that I can listen to check if the controller is being re-initialized? 

PS: Apologies on not providing a plunkr, I tried to create one but it didn't seem to repro with simple state configurations.

**Comment by nateabele** [comment]
Try adding this, to see if any IE-specific errors are being swallowed by the transition rejection:

```javascript
app.run(function($rootScope) {
  $rootScope.$on("$stateChangeError", console.log.bind(console));
});
```

**Comment by masterkidan** [comment]
So, it turns out there was nothing wrong with state transitions. The actual problem was with IE caching ajax requests. Hence, though the resolve was running, the data from the $http.get was stale. 

Thanks for the tip, it definitely helped me identify the correct issue, and keep up the great work with this project!

**Comment by odellcraig** [comment]
@masterkidan What did you do to resolve the issue for IE?

**Comment by odellcraig** [comment]
If anyone comes across this thread, I solved it by disabling caching using HTTP response headers from the server. This prevents IE from caching AJAX calls, because someone thought it was a good idea to cache AJAX calls... that's a terrible idea, IE *sigh*.

In Node world this middleware does the trick:
app.use(function noCache(req, res, next){

    res.header("Cache-Control", "no-cache, no-store, must-revalidate");
    res.header("Pragma", "no-cache");
    res.header("Expires",0);
    next();
});

**Comment by masterkidan** [comment]
You can also do the following if you are using $httpProvider in angular (1.3):
app.config(['$httpProvider', function ($httpProvider) {
 $httpProvider.defaults.headers.get = { 'If-Modified-Since': 'Mon, 26 Jul 1997 05:00:00 GMT','Cache-Control':'no-cache','Pragma': 'no-cache' };
}]);

**Comment by pursual** [comment]
Holy shit, this is a new level of horrible.

**Comment by pursual** [comment]
Does anyone have a solution for disabling the caching on api requests but maintaining it for static files? I guess i could make a middleware function and add it to all my api routes, just wondering if there is a nicer solution.

**Comment by hannadrehman** [comment]
@pursual i ran into the same problem, IE was caching all HTTP requests. this method has helped me 
app.config(['$httpProvider', function ($httpProvider) {
$httpProvider.defaults.headers.get = { 'If-Modified-Since': 'Mon, 26 Jul 1997 05:00:00 GMT','Cache-Control':'no-cache','Pragma': 'no-cache' };
}]);
since i am using angular template cache service , i dont have to worry about my partials not being cached.
