### ISSUE TITLE
$state.params != $stateParams in resolve block

### ISSUE THREAD

**Issue by lookfirst** [angular-ui/ui-router#1984]
angular 1.3.15
ui-router 0.2.14

I'm not sure if this is expected behavior, but I found it kind of odd. That said, it is unclear to me what the difference is between the two.

```
		.state('auth.store', {
			url: '^/stores/:crock',
                        controller: 'StoresController',
			resolve: {
				store: ($state, $stateParams) => {
                                     $state.params.crock; // this is undefined
                                     $stateParams.crock; // this is defined
				}
			}
		})
```

The confusion here is that if I inject `$state` and `$stateParams` into `StoresController`, both of them have the value set correctly. I'd prefer to only have to inject one thing, so I pick `$state` since it would give me everything I need in one object. :smile:

**Comment by nateabele** [comment]
The answer is that `$state.params` is a global, and `$state`'s globals are only updated once the transition is finalized (since the transition could fail as a result of a resolve, which would leave your app in an inconsistent state). `$stateParams`, however, is a magical local injected value that represents the parameters received by _just_ that state (and parent states).

**Comment by lookfirst** [comment]
:+1: 

Definitely something to add to the documentation.

**Comment by wesleycho** [comment]
Updated the Wiki FAQ [here](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-what-is-the-difference-between-stateparams-and-stateparams).
