### ISSUE TITLE
Initial route doesn't load unless $state is passed in run method

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#2051]
I'm having the weirdest issue with ui-router. I've been using it for over a year now, so I know how to use it, but I'm encountering a strange issue now which I have not seen before.

My initial route won't load when I navigate my browser to `/` or `/test` (the routes are defined). Just a blank page is show. If I navigate to those routes programmatically though or via links (`ui-sref='test'`), it works and the proper route template shows up.

It's just not working for the initial page load.

The strange thing is, that I figured out how to "fix" it, but I have no clue why this fixes it or what is broken in the first place:

``` javascript
//Change this...
.run(function($rootScope, App) {
    $rootScope.App = App;
});

//To this...
.run(function($rootScope, App, $state) {
    $rootScope.App = App;
});
```

Simply adding `$state` to the run function (not doing anything whatsoever with it) fixes the issue, and the correct route now shows up when refreshing the browser.

Has anyone else ever encountered this?

This is with ui-router 0.2.15 and angular 1.4.0.
Also tested with ui-router 0.2.13, same behaviour.

For good measure, these are my routes:

``` javascript
$stateProvider.state('home', {
  url: '/',
  templateUrl: 'home/home.html'
});
$stateProvider.state('test', {
  url: '/test',
  templateUrl: 'test/test.html'
});
```

And config:

``` javascript
$locationProvider.html5Mode(true);
$urlRouterProvider.otherwise('/');
```

**Comment by willhartman** [comment]
Interesting issue.  Would you be able to recreate this in a Plunkr please?

**Comment by adambuczynski** [comment]
I don't think I'll be able to reproduce it there, I think it may have to do with my server setup (nodejs + express), but I can't really find anything odd there either:

```
//Set static folder
app.use(express.static(path.resolve('./public')));

//...currently no other server routes yet

//Send all other requests to Angular
app.all('/*', function(req, res) {
  res.sendFile(path.resolve('./public/index.html'));
});
```

That's all working fine, and the whole app works fine as long as I enter that $state variable there.

I already checked if it has anything to do with the code minification process, but the same was happening with non-minified sources as well.

I will see if I can do some more testing on it later this week, I'll try to replicate it on a different server setup or on Plunkr.

**Comment by eddiemonge** [comment]
I can't seem to reproduce this

**Comment by adambuczynski** [comment]
Still haven't had the time to reproduce it in a controlled environment. Will try to do it asap.

**Comment by adambuczynski** [comment]
Ok I've narrowed it down to the following. It only happens when my main index template does not contain a ui-view element. My index HTML looks like this:

```html
...
<body lang="en">
  <ng-include src="'app.html'"></ng-include>
</body>
...
```

And then app.html contains the following:

```html
...
<main class="site-contents">
	<div class="container" ui-view></div>
</main>
...
```

When I replace the `ng-include` directive by the contents from `app.html`, it works fine. When I put back `ng-include` it only works when I pass the `$state` variable as an argument to the run method of the application.

The latter leads me to believe that it must be a bug with ui-router, because it should work whether I use `ng-include` or not, and it shouldn't depend on the `$state` variable being requested/injected.

I have also managed to reproduce this behavior in a Plunkr:

http://plnkr.co/edit/cZ6NUNU6UrxTN8iokGdP?p=preview

When you load it now, you don't see the home.html contents appearing. However, if you uncomment $state on line 22, you will see the home.html contents appear. Also, uncommenting line 11 in the HTML also triggers the home page contents to be displayed correctly. Presumably for the same reason, e.g. the `ui-sref` directive causes some initialization in ui router to occur, just like injecting `$state` does.

Also note that clicking on the home link causes the home state to load correctly as well.

Hope this helps and that you can fix it! Let me know if you need more info.

**Comment by adambuczynski** [comment]
I think maybe the problem lies in the fact that basically ui-router never gets initiated, unless you have `ui-sref` or `ui-view` elements in your main HTML, or if you inject the `$state` service somewhere. Is this correct?

If so, then maybe some of the initialization logic should be moved to the `.run()` portion of the ui-router module?

**Comment by eddiemonge** [comment]
I think technically that ui-router is a directive so it needs to be included to work. But yeah, maybe moving some of that logic to run might be needed

**Comment by adambuczynski** [comment]
I can have a look at it when I have time this week. The strange thing is that technically the directive is being included, just with a delay, through `ng-include`. However, you wouldn't expect that to prevent the directive from firing up.

**Comment by adambuczynski** [comment]
I've tried to play around with it, but unfortunately I'm not familiar enough with the code base of ui-router and it's not that well documented (inside the code), so I couldn't find what the problem is :(

I think someone who's a bit more familiar with the internals of ui-router should have a look at this one.

**Comment by leandro-shifteight** [comment]
I am having a similar problem. 
I am following https://github.com/angular-class/NG6-starter for creating a new project. There is an ````<app></app>```` directive that works as an entry point for the app. The template simply has a ````<div ui-view></div>````.
If I remove the app directive and put ui-view directly on the index.html works ok, when I use the directive with ui-view inside is not. I think is something related with priorities but not sure.

**Comment by adambuczynski** [comment]
Yes, sounds like the same issue to me.

**Comment by adambuczynski** [comment]
@eddiemonge Is this something that has been addressed in 1.0.0?

**Comment by RobinBuschmann** [comment]
I have a similar issue as well. Some states are initially blank, but working when opened by ui-sref. 

But in my case the problem seems to result from using "resolve" with returning a Promise like:

`````

$stateProvider
      .state('app.something', {
        url: '/something/:Id',
        views: {
          someView: {
            templateUrl: 'someTemplate.html',
            controller: 'Controller as vm',
            resolve: {
                 init: function(someService) {
                        return someService.getSomethingAsync()
                  }
            }
          }
        }
      })

`````

When `return` is removed everything works well

**Comment by eddiemonge** [comment]
@RobinBuschmann your issue sounds different and should be in a separate issue. But if you remove the return then init will not have the value from the `getSomethingAsync` response.

@adambuczynski It probably has been addressed. @christopherthielen would know better.

Part of me wants to say that ng-include isn't compiling things correctly or something in UI router is looking for the ui-view and it doesn't find it immediately because of the ng-include. In that, referencing it manually bootstraps it. If there isn't anything ui-router in the page then it shouldn't load its things so this seems like correct behavior to me.

**Comment by adambuczynski** [comment]
Thanks, I'll await the 1.0.0 release, and will start fiddling around with Angular 2. Will leave this issue as is, as I don't think it's worth fixing it anyway.

The workaround is simple enough, just include `$state` as a dependency in the app run function.

**Comment by virth** [comment]
Had the same issue with angular 1.5.2 and ui-router 0.2.18. As soon as the ui-view element is inside a template that gets loaded with ng-include you have to enter the $state variable in the .run() method.

we "fixed" the problem by creating a directive instead of using ng-include.

**Comment by imadulhaque** [comment]
@RobinBuschmann how did you solve your that was due to resolve with promise. I am also have same issue. Would really appreciate any help on this. (Tried to find a separate issue on this but couldn't find it so posting  request for help here).

**Comment by RobinBuschmann** [comment]
@imadulhaque I can hardly remember, but i think that i stopped using 'resolve'. But if you could provide a sample, i could have a look.

**Comment by imadulhaque** [comment]
I am doing something similar what you did. Here is the code:
`
.state('home', {
url: '/',
templateUrl: "./src/dashboard.html",
resolve: {
loggedin: isLoggedIn
}
})

function isLoggedIn($location, loginService) {
var deferred = $q.defer();
return loginService
.loggedin()
.then( function(result) {
if (!result){
$location.url('/login');
}
deferred.resolve(true);
},
function(err){
$location.url('/login');
deferred.resolve(true);
});
return deferred.promise;
};`

**Comment by RobinBuschmann** [comment]
@imadulhaque  Maybe you could use an abstract parent state and solve to the correct state (home or login) using the onEnter callback (https://github.com/angular-ui/ui-router/wiki#user-content-onenter-and-onexit-callbacks) instead:

`````

.state('app', {
  url: '/',
  abstract: true,
  onEnter: ['loginService', function(loginService) {
    loginService.isLoggedIn()
      .then(function() {
           if(!result) {
               ...
           }
       })
       .catch(function() { .. })
  }]
})
.state('app.home', { ... })
.state('app.login', { ... })

`````

or do it like this:

http://stackoverflow.com/a/23345992

Regarding your code example I have some advices:

If you're using promises, you should rather use the catch syntax than the error callback for catching errors (http://bluebirdjs.com/docs/anti-patterns.html#the-.then)
Second, your use of defer is unnecessary, since you will always get a promise in return, this is how promises work (http://bluebirdjs.com/docs/anti-patterns.html#the-explicit-construction-anti-pattern). So you could simply use

`````
return loginService.isLoggedIn()
      .then(function() { ... })
      .catch(function() { .. })

`````

**Comment by imadulhaque** [comment]
@RobinBuschmann thank you for you, i really appreciate that. 
I found the problem. I was bitten by a very silly mistake. Order of dependencies in my loginService module and its service function were not matching and hence resolve function was not working.
