### ISSUE TITLE
Triaging Issues

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-router#2059]
Pinging @angular-ui/router team: Hey guys, this project is definitely a pivotal project but it's easily getting bogged down with issues (~400 at current). I just want to remind / suggest that if people make "I need help" bugs close the issue and point them to Stack Overflow. I would also adopt the philosophy of some of the stricter projects (such as Ionic and Angular which have declared bug bankruptcy at times) to just close issues if they aren't actionable. Encourage people to reopen or create new issues or move their "how do I" questions to SO (with the option of answering them yourself or not, or at least giving a suggestion).

**Comment by nateabele** [comment]
:+1: We've mostly already been doing that.

**Comment by eddiemonge** [comment]
Sorry I've been on vacation/honeymoon for two weeks. I'll get back on triaging.

**Comment by christopherthielen** [comment]
@eddiemonge don't sweat it, hope you enjoyed your honeymoon!  congrats!

I'd be open to declaring "bug bankruptcy" at some point after 1.0.

**Comment by ProLoser** [comment]
I am also referring to the "needs more info bugs"

**Comment by christopherthielen** [comment]
I think we decided those ones should be closed after a week of inactivity

**Comment by nateabele** [comment]
> @eddiemonge don't sweat it, hope you enjoyed your honeymoon! congrats!

Ditto.

> I am also referring to the "needs more info bugs"

@ProLoser Yup, like @christopherthielen mentioned, that's more or less been the policy. We're slowly but surely getting it under control, but I think last ~couple weeks we just all happened to be otherwise occupied.

At this point it's basically a numbers game. If you wanna recruit more issue-triagers, that'd be great. Have 'em report to @eddiemonge.

> I'd be open to declaring "bug bankruptcy" at some point after 1.0.

I'm not opposed to this, but we should at least make some effort to tally up popular/common issues to make sure we're not leaving the community hanging.

**Comment by eddiemonge** [comment]
Down to under 250. A lot of issues are feature requests/bug fixes/docs stuff that should remain open until 1.0 is done to make sure its all covered. I'll continue to close older things that I think shouldn't be open.

Did start using https://gist.github.com/eddiemonge/f6a58169c2846731a1eb , didn't know people were commenting on it that instead of the actual issue though lol.
