### ISSUE TITLE
Deprecate looking up states by reference

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-router#2060]
I just feel like no one has used this feature whatsoever (since it's not convenient to get a handle on a state definition reference from everywhere else in the app) and it merely creates the small annoyance of having to clone your state definitions if you want to have multiple identical states with the different names but identical definitions.

Thoughts?

At least until the feature of adding a state to multiple parents is implemented.

**Comment by schmod** [comment]
| At least until the feature of adding a state to multiple parents is implemented.

Is this being considered for inclusion in 1.0?

The inability to arbitrarily nest/reuse states has been a big stumbling block for us, as it's often meant that state definitions often need to be repeated (which is problematic for code re-use).

As the state definitions themselves become more complex (particularly with the new functionality around resolves and state transitions coming in 1.0), this issue is going to become even more pertinent, because we're starting to pack an awful lot of logic into the state itself (rather than the controller).  If states aren't easy to re-use, controllers also become difficult to re-use, and we've suddenly erased one of the key benefits of using an MVC framework.

I've personally shied away from using resolves for similar reasons -- a controller that depends on a resolve no longer has enough logic to resolve all of its own dependencies.  While this might be an acceptable tradeoff, it becomes a nightmare to maintain if that controller needs to be used in more than one place.  

Apologies if I'm derailing this issue.  If there's another active issue discussing the aforementioned issues, I'll take my comments over there...

**Comment by ProLoser** [comment]
@schmod for me, the purpose of a controller is to wire logic and data onto the view, nothing more. I actually prefer the controller being agnostic about how the data was populated, and have found it beneficial at times because I can resolve the same data in different ways and the controller won't know or care.

For instance, editing a record vs creating a record can reuse the same controller yet just have the objects be resolved differently.

**Comment by nateabele** [comment]
>> At least until the feature of adding a state to multiple parents is implemented.

> Is this being considered for inclusion in 1.0?

Yes. Objects are going to be a bigger deal.

**Comment by schmod** [comment]
@nateabele is there a discussion about this someplace else, or any way that I can help out?

**Comment by nateabele** [comment]
Check out the feature-1.0 branch. We'll get roadmap issues out for it in the next few days if you wanna keep an eye on the tracker (or I can try to remember to @ you on them).
