### ISSUE TITLE
Parent attribute does NOT create a two way link.

### ISSUE THREAD

**Issue by Aaron-Pool** [angular-ui/ui-router#2066]
For example

```
$stateProvider
    .state('base', {}  /*attributes here*/ )
    .state('child1', { parent: base /*more attributes*/ }
    .state('child2', { parent: base /*more attributes*/ }
```

Then, in the template file for child1 I can put `$log.info($state.get('^'));`, and get the parent appropriately, but `$log.info($state.get('^.child2'))` is return unresolved. All children are linked to the parent through the `parent` attribute. But it seems this is not a bidirectional link.

Here's a plunkr: http://plnkr.co/edit/5kaTpgYxrLsl3wV8e5KA

**Comment by Aaron-Pool** [comment]
In fact, just ui-sref the child's name works, without any prefix. This doesn't seem correct. Shouldn't nesting help to avoid state namespace collisions as well as offer the benefits of nesting?

**Comment by Aaron-Pool** [comment]
Anything every happen with this?

**Comment by blemaire** [comment]
You cannot use `'^.child2` as it isn't the 'dot notation' name
It is explained in the [docs](https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views#object-based-states) which refers to issue #368 where the problem is explained.
in brief, using the parent property does not modify the actual state name and if you had 2 parents both containing a child called `child2`, you would have to use the 'dot notation' for the state names otherwise it would not work at all.
