### ISSUE TITLE
No way to respond to view state change cancellations

### ISSUE THREAD

**Issue by janakerman** [angular-ui/ui-router#2123]
In summary, I'm trying to build a loading spinner that shows during state changes. I'm utilising resolves on each of my states. If I transition between them quickly, I have no way of hiding the loading spinner. Here's an event timeline & commentary:

1) Click to load into state A.
2) Click to load into state B (long resolve begins) and $stateChangeStart is fired.
3) Click to load into state A (state A is currently active so no events are fired).

Ideally, I'd receive a `$stateChangeCancelled` event for state B. I could also work with a `$stateChangeSuccess` transition for the re-entry into state A (3).

A SO post from someone else experiencing a similar problem is available [here](http://stackoverflow.com/questions/29071416/how-to-be-informed-of-state-change-cancellations-in-ui-router). He also provides a [Plunkr](http://plnkr.co/edit/Uf3nSuOIgd6zvpIniUUY?p=preview).

**Comment by eddiemonge** [comment]
There is a stateChangeCancel event: https://github.com/angular-ui/ui-router/blob/dba25db961e3b8a2fff6fc388022cb6c194cec38/src/state.js#L1081

You should probably use a service. Add the state being transitioned to in the stateChangeStart event. Load the spinner for any state in the service. In the stateChange{Success|Cancel} event, remove the state from the service. Once all states have been removed, the spinner should go away as well.

closing since its the same question on stackoverflow and its an implementation issue, not ui-router bug. If there is a bug in any of this, we can reopen or a new ticket can be created with the specific bug.

**Comment by arjunu** [comment]
That cancel event will be called only when we manually cancel a state change but not in the scenario I've described. Please check this Plunk plnkr.co/edit/YcuG5HCcCAYqdkapkSPY

**Comment by eddiemonge** [comment]
So its not really a bug but should be a feature request.

**Comment by Grety** [comment]
There is an option currently to handle superseded transition. Need to handle the `transition` promise returned by `$state.go`. See more details in my [answer on SO](http://stackoverflow.com/a/31620297/4573999)

**Comment by Jaco-Pretorius** [comment]
+1 for this issue, I'm having exactly the same problem.  Same as @janakerman - 

> Ideally, I'd receive a $stateChangeCancelled event for state B. I could also work with a $stateChangeSuccess transition for the re-entry into state A (3).
