### ISSUE TITLE
[$urlMatcherFactoryProvider] Pattern defined in definitionFn is not resolved correctly

### ISSUE THREAD

**Issue by khashayar** [angular-ui/ui-router#2199]
I've found an issue with `$urlMatcherFactoryProvider` and custom type definition **function**. Here's a sample config:

``` javascript
app.config(function ($stateProvider, $urlMatcherFactoryProvider) {
  $urlMatcherFactoryProvider.type('myType', {}, function () {
    var typeMap = ['foo', 'bar', 'baz'];

    return {
      encode: function (val) { return typeMap.indexOf(val); },
      decode: function (val) { return typeMap[parseInt(val, 10)]; },
      is:     function (val) { return typeMap.indexOf(val) > -1; },
      pattern: /\d/
    };
  });

  $stateProvider
  .state('home', {
    url: '/',
    template: 'home.html'
  })
  .state('home.documents', {
    url: '{entityType: myType}{entityId: int}/documents',
    template: 'documents.html'
  })
});
```

If I navigate from home to document, let's say `/125/documents`, everything works as expected, $state params are:
`{entityType: 1, entityId: 25}`

but once I enter url directly in the browser's address bar, urlMatcher parses the params incorrectly:  `{entityType: 12, entityId: 5}`

Although I've specified `pattern: /\d/` in the type config.

I've looked into the source code and found what causes the issue. Inside `this.type` function, there's this line:

``` javascript
    $types[name] = new Type(extend({ name: name }, definition));
    if (definitionFn) {
      typeQueue.push({ name: name, def: definitionFn });
      if (!enqueue) flushTypeQueue();
    }
```

When it comes here `enqueue` is `true` and it doesn't apply the `definitionFn` at this point. Then it goes to `matchDetails` function where it tries to read the type's config:

``` javascript
type = $$UMFP.type(regexp || "string") || inherit($$UMFP.type("string"), { pattern: new RegExp(regexp, config.caseInsensitive ? 'i' : undefined) });
```

And since the definitionFn is not applied on the $type yet, the pattern is the default pattern `/.*/` and that's where the problem happens.

I know that there is this line inside `this.$get`:

``` javascript
    enqueue = false;
    flushTypeQueue();
```

But it's too late and `matchDetails` function has already been called and applying the definitionFn has no impact at this point.

So my question is why there's this line inside `this.type` function:

``` javascript
if (!enqueue) flushTypeQueue();
```

and based on the comments in the code

``` javascript
// `flushTypeQueue()` waits until `$urlMatcherFactory` is injected before invoking the queued `definitionFn`s
```

Why `flushTypeQueue` waits for until  `$urlMatcherFactory` is injected?

**Comment by eddiemonge** [comment]
Wow that is detailed. @nateabele might know

**Comment by nateabele** [comment]
> Why `flushTypeQueue` waits for until `$urlMatcherFactory` is injected?

Because [`flushTypeQueue()` relies on `$injector`](https://github.com/angular-ui/ui-router/blob/master/src/urlMatcherFactory.js#L878), which is not available until `$urlMatcherFactory` itself is injected.

I'm not 100% sure why it is attempting to route to a state before this happens. Currently you're prevented from passing `pattern` as part of the definition object outside of the definition function, which would allow you to work around your problem.

@christopherthielen Do you remember why that's a thing? (It was intro'd in https://github.com/angular-ui/ui-router/commit/4533fe36e0ab2f0143edd854a4145deaa013915a).

**Comment by khashayar** [comment]
I switched to definition object and now everything works well for me, just filed it here as a heads-up.

**Comment by christopherthielen** [comment]
@nateabele I remember we discussed if we should register types at config or at runtime and landed on config time (I think because states are built during config).  The pieces we needed in order to build the state at config time were the type name and the type's pattern, for building the URL pattern.

**Comment by ka8725** [comment]
@khashayar how did you solve the issue? It's not clear what does it mean *switched to definition object*, sorry.

**Comment by nateabele** [comment]
@ka8725 Post a plunkr and we'll take a look. The original issue here is that type definitions have to include a pattern in the config block, and can't override it in a function.
