### ISSUE TITLE
If there is not a state with '/' defined, infinite loop

### ISSUE THREAD

**Issue by eddiemonge** [angular-ui/ui-router#2238]
http://plnkr.co/edit/cH0LiMq29CIyzfZzHYva?p=preview

Seems like if there is not a state with a url of '/' then the states will go in an infinite loop.

**Comment by filipesilva** [comment]
I did some testing, and it seems that the `/` state cannot be an abstract parent state.

http://plnkr.co/edit/0wnnfKpS9l11i4azravK

**Comment by christopherthielen** [comment]
App Bootstraps; url is ""
-> check rules against ""; only otherwise('/home') matches 
-> $location.path('/home') 
-> check rules against "/home"; match 'home' and transitionTo('home')  (Transition 1)
-> Transition 1) $stateChangeStart.preventDefault() 
-> transitionTo('login') (Transition 2)
-> Transition 2) $stateChangeStart, not prevented; goes to async portion
-> Stack popped until we get back to...
-> Transition 1) $stateChangeStart.defaultPrevented === true, so call $urlRouter.update()
-> $location.path() is reset to the last know url, ""
cycle starts

**Comment by christopherthielen** [comment]
I can't seem to create a failing unit test.  Perhaps this is due to the mocks behaving differently.

Also interesting: the plunker works if you downgrade angular to 1.3.3 or earlier.  1.3.4 and above exhibit the infinite digest.

**Comment by filipesilva** [comment]
I'm glad to hear I was of help @christopherthielen. Great job on the fix!
