### ISSUE TITLE
Back button not reloading controller 

### ISSUE THREAD

**Issue by ramanathan92** [angular-ui/ui-router#2300]
I created one angular application and used UI router.From my app need to redirect to some other website.But am getting this problem : - 

Step 1: From my ui-router app to another website i was redirected.
Step 2: If i click back button from that website it will redirect to my UI-router app.

Problem is : It is not loading my controller on landing to my ui-router page.It is retaining my previous state instead of reloading it.

**Comment by eddiemonge** [comment]
Why should it reload instead of retain? You are going back, not reloading the page

**Comment by ramanathan92** [comment]
No.Actually think it in this way,That is a confirmation page.If user clicks on back button then i should redirect them from instead landing into confirmation page to main page right,For that at least my controller should load for that particular state.But In firefox and safari it is not loading,But in chrome it is loading that state.

**Comment by eddiemonge** [comment]
Don't do the confirmation page as a state then and instead consider something like a modal

**Comment by wesleycho** [comment]
This sounds more like a usage issue - the library itself should not reload the controller, that is huge wasteful sudden processing. This would compound when the user quickly hits back on the browser to get to the particular view he/she wants. In addition, there would be no clean way to get to this proposed change that is not a large breaking change for other users of the library.

I would highly recommend structuring the application more appropriately for handling how the view is presented to the user when the user hits back. This puts less processing pressure, as well as avoids a major change in expected behavior with the library.
