### ISSUE TITLE
when router loads view javascript in view is not evaluated

### ISSUE THREAD

**Issue by kroupa1985** [angular-ui/ui-router#2343]
I am making an simple application with ui-router. 

The javascript loaded from the view is not evaluated. 

I am making an application with webix. 

Did i miss some configurations ?

**Comment by wojohowitz** [comment]
I do not in any way represent any support on this project, though you may want to [check out this issue thread on Angular 1.4.4 animations](https://github.com/angular/angular.js/issues/12612)

My problem was/is with using Founation modals. I found that the modal would only find the refrenced id node when nested in the main body and not in a ui-view. I had also, though tried having it in a directive (enclosed scope) and it failed to fire as well.

My issue is not resolved and while that issue is closed with a patch on 1.4.5, I am running 1.4.7. So, I'm not sure what's up yet.  

Try putting into out of a ui-view and in a directive in the main body and see if jquery persists not function. At least then you can rule out ui-router (and if you are running angular 1.4.4, upgrade).

P.S. I realize that foundation has a rich set of angular directives made available in foundation for apps though I have my reason for using the former. :)

**Comment by kroupa1985** [comment]
I've managed the isshue.

I don't need javascript in view anymore.

I've used directive webix-ui="config". And in controller i've used $scope.config = { ... } to setup the webix widgets. Not its working fine.

Thank anyway.
