### ISSUE TITLE
Create map file in realese

### ISSUE THREAD

**Issue by goldserg** [angular-ui/ui-router#2378]
Please, create *.map file in realese for debugging in browser.

**Comment by eddiemonge** [comment]
You should use the non-minified file for debugging.

**Comment by goldserg** [comment]
No, I means when debugging need in production. In this case i cann't change code.

**Comment by eddiemonge** [comment]
Why are you debugging in production?

**Comment by goldserg** [comment]
When developing the software, you are not protected from errors, and sometimes it is impossible to reproduce the error on the test stand because of the difference in data on production.
Why other libs has js, min.js, map files in release, but this lib no?

**Comment by nateabele** [comment]
I'm not opposed to it, if someone wants to submit a PR.

**Comment by eddiemonge** [comment]
> Why other libs has js, min.js, map files in release, but this lib no?

Because including the source mapping in min.js adds to the file size and the point of minimizing is to minimize the file size so it is served as fast as possible.

You should probably have a staging/dev/test environment that you can duplicate the data to or reproduce in so you can debug safely there. If not, perhaps its time to look into increasing your dev ops so you can have these environments.

Also you can debug in Chrome. Click the `{}` button in the source viewer to see a bit more readable part.

**Comment by nateabele** [comment]
> Because including the source mapping in min.js adds to the file size and the point of minimizing is to minimize the file size so it is served as fast as possible.

Maps are typically served as separate files.
