### ISSUE TITLE
Ui-sref and Abstract States

### ISSUE THREAD

**Issue by Exagram** [angular-ui/ui-router#2396]
I have a state hierarchy with abstract parents but ui-sref throws an error: "Cannot transition to abstract state 'home'". I was able to get navigation with HTML anchor tags to work with `$urlRouterProvider.when('/home', '/home/child2');`. However I want to make ui-sref work because I want ui-sref-active to work too.

States - (@=abstract):

    @home, "/home"
    home.child1, "/child1"
    home.child2, "/child2"

Code: http://plnkr.co/edit/01xXCFFIuEh8kLTZmpdV?p=preview

**Comment by eddiemonge** [comment]
ui-sref is working in your example. The href isn't (which is understandable since you should be using the ui-sref anyway).

**Comment by Exagram** [comment]
Disregard the href examples, refer to "working with ui-sref", the error still exists. If you click "Home" or "Other", you will see the error in the console.

**Comment by eddiemonge** [comment]
Its because you really are trying to transition to an abstract state. ui-sref takes the actual state name. If you want home to redirect to the child state then you need to make it not abstract and add a state.go in either a stateChangeStart or onEnter or some other means. 

You can use the $urlRouterProvider but you need to do it differently. I forget the exact syntax. The way you have it, you are saying when the url is /home, go to somewhere else. ui-sref doesn't change the url until after it has transitioned to the state (or starts to) but if the state is abstract it can't transition to it.
