### ISSUE TITLE
[Feature request] Force auto-refresh of a single parent resolve

### ISSUE THREAD

**Issue by sylvainbx** [angular-ui/ui-router#2424]
Hi,

I've been searching around for a while but I was unable to find an elegant way to achieve what I've got in my mind. Here's the case (in coffeescript):

```coffee
$stateProvider
  .state 'app',
    abstract: true
    views:
      (...)
    resolve:
      translations: [ '$state', 'Translations', ($state, Translations) ->
        Translations.query($state.next.name).$promise
      ]
      (more resolves ...)
```
 With (moreover) this little hack to set the `.next` parameter in the state:
```javascript
angular.module('application', [ ... ]).config(function(...) {
  $provide.decorator('$state', ['$delegate', '$rootScope', function($delegate, $rootScope) {
    $rootScope.$on('$stateChangeStart', function(event, state) {
      $delegate.next = state;
    });
    return $delegate;
  }]);
}):
```

So basically, I want to retrieve from my `Translation` service (using `$http` internally) the translations for the next `$state`.

The problem, with this approach is that the "translations" resolve will be resolved just once, when the first state inheriting from `app` will be loaded ... and it will never be reloaded on future state changes.

So, the commonly told solution would be to remove the resolve from `app` and to put it every states where I want it from being resolved, but I feed bad at the idea to have to write these similar lines of code for each states in my application (about 50) which all inherits from `app`.

Another working solution would be to pass the `{reload: true}` parameter on every links but this has three drawbacks to my senses:
1. If I forget to modify any link, I will get f*cked
2. This implies some little unnecessary redundancy with the `{reload:true}` on each `ui-sref`/`$state.go()`/etc.
3. The other `resolves` from every inheritance levels will get reloaded ... this is not necessary nor desirable.

So I think that it would be great to have a way to tell ui-router to "refresh" a specific resolve on every state change, maybe doing something like this:

```javascript
resolve: {
  translations: [ '$state', 'Translations', function ($state, Translations) {
   Translations.query($state.next.name).$promise;
  }]
  options: {
    'auto-reload': ['translations']
  }
}
```

**Comment by christopherthielen** [comment]
1.0 allows resolves to be added *per transition*.

```
$transitions.onStart(function ($transition$, Translations) {
  $transition$.addResolves({ translations: Translations.query($transition$.to().name) });
}) ```

**Comment by peterzebird** [comment]
Is there an elegant solution to do this on ui router 0.2.x ?

**Comment by chillyistkult** [comment]
I have the exact same problem. @christopherthielen is it possible to explain the idea behind putting resolves per transition. As far as I understand your example code would resolve the translations on every transition, but what we need is to define a kind of reload option for resolves on the state level.

**Comment by christopherthielen** [comment]
> Is there an elegant solution to do this on ui router 0.2.x ? 

nope.

> is it possible to explain the idea behind putting resolves per transition

An onbefore hook adds a resolve (to the root state).  That resolve is fetched, and then is available to be injected into any states being *entered*.

> but what we need is to define a kind of reload option for resolves on the state level.

that doesn't make sense from a ui-router architecture POV.  You'll need to store the value elsewhere; not in a resolve. The resolve is refreshed only when a state is exited/re-entered.

---

instead of using resolve injection mechanism, maybe you want a transition hook that refreshes a value found in a service:

http://plnkr.co/edit/uI7MmZvylcOkz5JpGKMc?p=preview

**Comment by magumbo** [comment]
> that doesn't make sense from a ui-router architecture POV. You'll need to store the value elsewhere; not in a resolve. The resolve is refreshed only when a state is exited/re-entered.

I agree with this sentiment - but my situation may be a suitable caveat. 

I'm using dynamic state params with $state.go('.', {paramToBeUpdated: newValue}) to reflect user selections in the location bar & applicable child states. I'm doing this deliberately so the parent states don't reload/ update/ re-enter as per ui-router docs.

Dynamic state params enable us to update parameters without a state transition  - wouldn't a logical extension of this idea be a hook in the parent state to update any resolves?

I agree on your philosophy that most other global-ish state data should live in a service - but surely the state params are explicitly tied to ui-router?

**Comment by adamreisnz** [comment]
I too would like to request this feature. I have a global resolve that is resolved in my top level application route, and as that resolve is used throughout the entire application, it's super convenient to have it there and not in a service, so that I don't need to fetch it from the service everywhere, everytime I need it.

With the one-way binding mechanisms available in Angular, and the resolve value trickling down to all the child routes and child components, it would be nice if there was a way to update or refresh the resolve value at the top level, so that the new value would automatically trickle down to the other child components.

Using a service for it would mean that every component will have to refresh the value and request it from the service again.

**Comment by adamreisnz** [comment]
As a work around, I am now adding the resolve to each applicable route via an onBefore hook. Since it's already resolved in the $store it won't fetch it from the server again, but if it's refreshed in the store it will provide the new value. 

Still doesn't solve it if one would like to refresh it and trigger one way bindings without moving away to another route, but it'll do for now.
