### ISSUE TITLE
Animating nested views

### ISSUE THREAD

**Issue by gomoto** [angular-ui/ui-router#2427]
I have been trying to animate the entrance of nested ui-views.

After reading the [ui-router FAQ on animating ui-views] (https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-animate-ui-view-with-ng-animate), I was under the impression that ng-enter could be added to any ui-view, including nested ui-views. 

But it seems like:

1) ng-enter is added only to the root ui-view (and not to nested ui-views)

2) ng-enter is added to the root ui-view only when transitioning to a top-level state (and not when transitioning to nested states)

I tried to summarize these two points in this [plunker] (http://plnkr.co/edit/6KqhGqZiyTlodzkwfSNF?p=preview).

Is this intentional? If so, what is the proper way to animate entering nested ui-views?

**Comment by christopherthielen** [comment]
I have to admit mostly ignorance to angular animation code.  I know that we simply delegate to angular animation code, and we do ask for animation to be added for all (including nested) ui-views.

https://github.com/angular-ui/ui-router/blob/master/src/viewDirective.js#L250

I suspect the core `$animate` service is noticing that your css targeting `ng-enter` doesn't have a `transition` definition and "optimizing it away".  See here where I managed to get the grandchild to fade to orange:  http://plnkr.co/edit/6KqhGqZiyTlodzkwfSNF?p=preview

I'm going to do some finger pointing and close this issue, because I don't think it's ui-router's issue. Feel free to convince me otherwise :)

**Comment by lstone** [comment]
You can also run into this issue if you're using `[ui-view]` attribute selector in your css instead of the `ui-view` tag selector.

**Comment by christopherthielen** [comment]
^ oh really O_o
Very interesting!
