### ISSUE TITLE
$state.includes broken

### ISSUE THREAD

**Issue by IcanDivideBy0** [angular-ui/ui-router#2438]
The `$state.includes` function seems broken :
```js
console.log($state.current.name, $state.includes('**.todo.*'));
'awesome.edit.todo.inbox', false
```
v0.2.15
this used to return true in v0.2.11, propably introduced by https://github.com/angular-ui/ui-router/commit/19715d15e3cbfff724519e9febedd05b49c75baa or https://github.com/angular-ui/ui-router/commit/232e94b3c2ca2c764bb9510046e4b61690c87852

**Comment by eddiemonge** [comment]
I know its an easy case, but can you create a plunkr showing this please?

**Comment by IcanDivideBy0** [comment]
Here it is : https://plnkr.co/edit/LyRUf0ipi71s0Vf9Xkx9?p=preview

**Comment by christopherthielen** [comment]
weird.  `**.todo.**` works though.  @nateabele can you have a look when you get a chance?

**Comment by axar** [comment]
This is caused by https://github.com/angular-ui/ui-router/commit/8c977360ceaa73fda5cc3fca8f1e57b9574350ed raised at #1680
In`about.person.item`  not sure what`about.*.**` is suppose to validate to? It's the same as saying `about.**` if we need to match that combo we can say `about.*.*`
I'm assuming that `**` matches anything and nothing.  while `*` matches exactly something. 

If we wanted to do a particular number of nodes comparison  by saying `about.*.**` matches exactly one element after about then any element after that. The current glob implementation isn't suitable. 

#2880 pull request
