### ISSUE TITLE
0.2.17 - Internal URL Regex do not match Params

### ISSUE THREAD

**Issue by linvi** [angular-ui/ui-router#2514]
The `state.internal.url.regexp` is not correct as it does not match the parameters. For example if you have the following url : http://localhost/#/test/42?pageId=2. The match will return { pageId : "" }.

Here is the state configuration : 

``` js
state('home.document.viewer', {
	url: '/test/:id?pageId',
	reloadOnSearch: true,
	params: {
		pageId: {
			value: ''
		}
	},
```

The generated `url.regexp` is the following : `/^\/test\/([^\/]*)?$/`. As you can see there is clearly no mention of the params in the regexp.

Here is a reference to what I have used for some time now : http://stackoverflow.com/questions/29892353/angular-ui-router-resolve-state-from-url.

Here is the code that do not work : 

``` js
APP.config(function ($stateProvider) {
    $stateProvider.decorator('parent', function (internalStateObj, parentFn) {
        internalStateObj.self.matchURLAndGetParams = function (url) {
            var match = internalStateObj.url.exec(url);
            return match; //
        };

        return parentFn(internalStateObj);
    });
});
```

**Comment by linvi** [comment]
I am not sure whether it was changed or not but I found in the source code that the url.exec requires 2 parameters, `path` and `search`.

By passing these parameters through I was able to get what I wanted. Though I am not sure yet how to get these parameters from a simple url. The source code is using `$location.path()` and `$location.search()`.

**Comment by christopherthielen** [comment]
As you've noticed, the regex in UrlMatcher  for the path only.  You cannot use a regexp to match query parameters, since they could be in order, out of order, have duplicate values, be mixed in with parent and child parameters.

The $location service gives us the key/value pairs for the query parameters, which we then pass through to the UrlMatcher. 

That stackoverflow answer isn't complete, since it doesn't deal with query parameters.


Hope this helps.
