### ISSUE TITLE
$state.go() with {notify:false} causes {resolve} property of route recall

### ISSUE THREAD

**Issue by nadavelyashiv** [angular-ui/ui-router#2544]
I'm using $state.go('state.name', {params}, {notify:false}) to update my url params and it works well. The problem is I have defined 'resolve' services for this route and they are being called, and I don't really want that to happen, as it is unnecessary calls to the server. I would expect {notify:false} to skip that too, Is there a way to skip the resolving? 
Or even better - another elegant way to update state params with ease? (instead of $state.go()) ?
I've asked that on SO as well.
http://stackoverflow.com/questions/35038133/change-stateparams-with-notifyfalse-and-no-resolve

**Comment by christopherthielen** [comment]
`notify: false` suppresses the `$stateChange*` events (nothing more, nothing less).  However, suppressing those events has lots of *really nasty* side effects.  We really need to update our docs to state that `notify: false` is deprecated and dangerous.

The only supported way to update params without performing a transition is using `reloadOnSearch: false`.  You're limited to query params if you use this.

In 1.0 alpha, we're really close to a full solution to this use case called "dynamic params" (update the params in the url, but not perform a full transition)

Sorry I don't have a better answer for right this moment, but it is coming.  Closing because we have eleventy open issues for notify: false

**Comment by cbier1** [comment]
`reloadOnSearch` is now deprecated as well.
https://ui-router.github.io/ng1/docs/latest/interfaces/state.statedeclaration.html#reloadonsearch

**Comment by christopherthielen** [comment]
Dynamic parameters from 1.0 should do the trick
