### ISSUE TITLE
1.0.0-alpha.1: $stateChangeStart and $stateChangeSuccess status

### ISSUE THREAD

**Issue by jahtalab** [angular-ui/ui-router#2655]
Hi, 
What is the current status of $stateChangeStart and $stateChangeSuccess, they seem to be removed from the lib but I can't find any documentation about it.

What is the alternative solution if they're actually removed?

Thanks

**Comment by garycourt** [comment]
I just ran into this problem myself. Discovered you can use this instead:

```js
$transitions.onStart({}, function() {});
$transitions.onSuccess({}, function() {});
```

**Comment by christopherthielen** [comment]
Woops, it looks like 1.0.0-alpha.1 build didn't include the state events!

We've deprecated the `$stateChange*` events in favor of the `$transitions` lifecycle hooks.  We do provide them as an addon file, however, which is missing in the release.


The hooks documentation is at http://angular-ui.github.io/ui-router/1.0.0-alpha.1/interfaces/transition.ihookregistry.html

**Comment by arcreative** [comment]
This was a pretty heinous thing to include without a deprecation notice.  Just realize we have no analytics since the upgrade, and pretty terrible transition help to get it back to where it needs to be.  I vote greater caution is taken with this sort of stuff in the future, especially because removed events don't ever show up in your error tracking.

**Comment by christopherthielen** [comment]
Sorry @arcreative , we tried!

https://github.com/angular-ui/ui-router/issues/2219
https://ui-router.github.io/guide/ng1/migrate-to-1_0#breaking-changes
