### ISSUE TITLE
1.0.0-alpha.1: Cannot read property 'resolveContext' of undefined

### ISSUE THREAD

**Issue by garycourt** [angular-ui/ui-router#2657]
I'm attempting to upgrade ui-router to `angular-ui-router#1.0.0-alpha.1` with `angular#1.4.7`. Some of our links are throwing errors at the following line:

```js
var resolveCtx = common_1.find($transition$.treeChanges().to, hof_1.propEq('state', vc.viewDecl.$context)).resolveContext;
```
```
TypeError: Cannot read property 'resolveContext' of undefined
```

Best I can tell, routes that have a `resolve` option to them (`$stateProvider.state('foo',{resolve:{/*...*/}})`) seem to throw this.

Any ideas why `common_1.find` would return `undefined` when this route used to work in `angular-ui-router#0.2.17`?

**Comment by christopherthielen** [comment]
That code is fetching all the locals for a view (controller)

As far as I can tell, we couldn't find the right object in the "to path" (which is the path of nested states from the root state down to the transition's target state). 

This could be caused by a number of things.  Can you drop a breakpoint there (in Chrome, use the "pause on exceptions" feature) and report back what is the value of:

- `vc.viewDecl`
- `vc.viewDecl.$context.name`
- `$transition$.treeChanges().to.map(function(node) { return node.state.name; })`
- `$transition$.treeChanges().to.map(function(node) { return node.resolveContext; })`
- I'd also like to see the state definition which is failing.

If I can reproduce this, I'll get this fixed up ASAP and put into alpha.2

**Comment by garycourt** [comment]
As requested:

```js
//vs.viewDecl
{
$context:exports.extend.exports.extend
$name:"menu@main.shop"
$type:"ng1"
$uiViewContextAnchor:"main.shop"
$uiViewName:"menu"
controller:"ShopMenuController"
resolveAs:"$resolve"
templateUrl:"shopMenu.html"
}

//vc.viewDecl.$context.name
"main.shop.collection.category"

//$transition$.treeChanges().to.map(function(node) { return node.state.name; })
["", "main", "main.shop", "main.shop.category"]

//$transition$.treeChanges().to.map(function(node) { return node.resolveContext; })
[ResolveContext, ResolveContext, ResolveContext, ResolveContext]
```

If you still need to see the state definitions, let me know and I'll send it as a PM to you.
