### ISSUE TITLE
ui.router custom type with a child state and full reload from server doesn't work.

### ISSUE THREAD

**Issue by lahsrah** [angular-ui/ui-router#2680]
I registered a GUID type into my ui-router using an example I followed online:

```
.config(['$urlMatcherFactoryProvider', function($urlMatcherFactoryProvider) {
  var GUID_REGEXP = /^[a-f\d]{8}-([a-f\d]{4}-){3}[a-f\d]{12}$/i;
  $urlMatcherFactoryProvider.type('guid', {
    encode: angular.identity,
    decode: angular.identity,
    is: function(item) {
      // BUG: item should just be the GUID and not the child url path!!
       return GUID_REGEXP.test(item);
    }
  });

```
Then I use it in my state like this `"/parent/{id:guid}"`

This works fine in all scenarios except when there is a child state to the above parent AND the user loads the child state directly by copying the URL in new tab or reloading browser.

The issue is, the `is `function receives `"CD73FAD2-E226-4715-B6FA-14EDF0764162/child"` instead of just receiving `"CD73FAD2-E226-4715-B6FA-14EDF0764162`" and so the regex fails.

Here is a plunker demoing this issue: http://plnkr.co/edit/kdKIG4ies3yuWS1z52f1?p=preview

Try clicking the four links in new tabs and you will notice that only the last 2 with the hard-coded GUID in the state will work and correctly load the state but the first 2 using the new custom type of GUID do not work.

**Comment by christopherthielen** [comment]
sorry I seem to have missed this bug report. 

Thanks for the plunker with easy reproduction.  Here's what's happening:

StateBuilder creates a UrlMatcher for each state.  The UrlMatcher is created by appending the current state's regexp to the parent state's regexp.  The current state's regexp is built by parsing the `url` property.  When a custom parameter type is encountered, the custom type's regexp is inserted in place of the parameter (in order to match the parameter in the URL).  

By default, a custom type's pattern (regexp) is `.*`.   Your custom type didn't provide any custom `pattern`, so it was matching the url as `.*`, and including the `/child` suffix.  However, when the parameters were `validate()`ed in `transitionTo()`, the transition was rejected because the parameter`.is()` returned false.

The solution is to define a pattern in the custom type that works for your use case. 


# option 1

Don't match slashes

http://plnkr.co/edit/XRKGGAAZqPsQ8BcBvLAc?p=preview

```js
.config(['$urlMatcherFactoryProvider', function($urlMatcherFactoryProvider) {
  var GUID_REGEXP = /^[a-f\d]{8}-([a-f\d]{4}-){3}[a-f\d]{12}$/i;
  $urlMatcherFactoryProvider.type('guid', {
    encode: angular.identity,
    decode: angular.identity,
    pattern: /[^/]+/,
    is: function(item) {
      // BUG: item should just be the GUID and not the child url path!!
       return GUID_REGEXP.test(item);
    }
  });
```

# option 2

Match exactly GUIDs

http://plnkr.co/edit/82rpitArzhZdQci8yGS8?p=preview

This is probably a better option, but you have to play by the ui-router regexp rules, which means 

- no capture groups
- no `^` or `$` (because the regexp is embedded inside another regexp)
- no modifiers like `/i`

```js
.config(['$urlMatcherFactoryProvider', function($urlMatcherFactoryProvider) {
  var GUID_REGEXP = /^[a-f\d]{8}-([a-f\d]{4}-){3}[a-f\d]{12}$/i;
  $urlMatcherFactoryProvider.type('guid', {
    encode: angular.identity,
    decode: angular.identity,
    pattern: /[^/]+/,
    is: function(item) {
      // BUG: item should just be the GUID and not the child url path!!
       return GUID_REGEXP.test(item);
    }
  });
```
