### ISSUE TITLE
deferIntercept() not possible since 1.0.0-alpha.1

### ISSUE THREAD

**Issue by rockmacaca** [angular-ui/ui-router#2701]
Since commit 9a7c605 in src/ng1/services.ts, it's impossible to hook into `$locationChangeSuccess` before ui-router does in the same way that the docs advertise you can.

The commit introduces use of its own location change registry kept in the `urlListeners` array. This is fine, except the other important change that was made is that the `$locationChangeSuccess` hook is registered upon the injection of $urlRouter instead of when $urlRouter.listen() is called.
```
$get.$inject = ['$location', '$browser', '$sniffer', '$rootScope'];
function $get($location, $browser, $sniffer, $rootScope) {
	$rootScope.$on("$locationChangeSuccess", evt => urlListeners.forEach(fn => fn(evt)));
	...
}
```
Thus, the logic in the function
```
function getUrlRouterProvider() {
	router.urlRouterProvider["$get"] = function() {
		router.urlRouter.update(true);
		if (!this.interceptDeferred) router.urlRouter.listen();
		return router.urlRouter;
	};
	return router.urlRouterProvider;
}
```
has no effect, since `router.urlRouter` has already been created with $get and the `$locationChangeSuccess` listener has already been registered with the functions in `urlListeners`.

Basically this means that that the immediate fix to register your own handler like the example in the documentation would be something like this:
```
.run(function ($rootScope, $injector, UserService) {
 
  $rootScope.$on('$locationChangeSuccess', function(e) {
    // UserService is an example service for managing user state
    if (UserService.isLoggedIn()) return;
 
    // Prevent $urlRouter's default handler from firing
    e.preventDefault();
 
    UserService.handleLogin().then(function() {
      // Once the user has logged in, sync the current URL
      // to the router:
      $injector.invoke(['$urlRouter', function ($urlRouter) { $urlRouter.sync(); }]);
      // ^^ We can inject $urlRouter now that we have the first handle on $locationChangeSuccess
    }
  });
 
  // Configures $urlRouter's listener *after* your custom listener
  $injector.invoke(['$urlRouter', function ($urlRouter) { $urlRouter.listen(); }]);
});
```
Obviously, this isn't ideal, but the best solution would be to expose a way of pushing to the `urlListeners` array at config time. That way custom handlers added then still would run before the handlers that $urlRouter.listen() adds. I wasn't able to find any way to natively do this in the current documentation however.

**Comment by christopherthielen** [comment]
I've been looking at this issue but can't see the problem.

- The `onChange` listener registry is created early, but the listener isn't registered until `listen()` is called. 
- When `listen()` is called, it adds a single listener to the registry, which delegates to the URL matching code.
- The line `if (!this.interceptDeferred) router.urlRouter.listen();` avoids calling `listen()` automatically.
- Although the `$locationChangeSuccess` event handler is indeed registered early, the `urlListeners` registry should be empty until `$urlRouter.listen()` is invoked.


This plunk demonstrates `deferIntercept()` and it seems to work fine: http://plnkr.co/edit/zkwe1gjiRI324t9KT6IS?p=preview

Let me know if this clears anything up, or if there is still a problem with `deferIntercept()`

I'm closing for now because I don't think this is a bug.
