### ISSUE TITLE
Cannot GET /profile/ after reloading the page

### ISSUE THREAD

**Issue by deniz946** [angular-ui/ui-router#2741]
Hello, all my states get the "Cannot GET /profile/" or "Cannot GET /whatever/" error in the browser after reloading the page with F5, why is this happening?

```
http://localhost:3000/profile/ Failed to load resource: the server responded with a status of 404 (Not Found)
```
this is my route file

```
angular.module('test123')
.config(function ($stateProvider) {
	$stateProvider
	.state('profile', {
		url: '/profile',
		templateUrl: 'profile/profile.html',
		controller: 'ProfileCtrl'
	}); 
})
```

**Comment by voroninp** [comment]
This is probably because browser makes a request to http://localhost:3000/profile/ and interprets it like an attempt to browse a directory. You need url rewrite mode. Web server should ignore `/profile` part of the url as it will be later processed on the client. Had the same problem with asp.net mvc a couple of days ago.

**Comment by eddiemonge** [comment]
Closing as this is an implementation issue. Like @voroninp your server needs to support rewriting all requests to the file you want to actually serve
