### ISSUE TITLE
transitionsProvider onEnter not firing everytime for '*'

### ISSUE THREAD

**Issue by zirho** [angular-ui/ui-router#2783]
Hi, 

I was trying to save the previous state for auth success redirection.
Isn't this code supposed to fire every transition? 
```
    $transitionsProvider.onStart({to:'*'}, ($transition$) => {
       // save previous state info
    })
```

but this fires every time. 
```
    $transitionsProvider.onEnter(
      {to: () => { return true; }},
      $transition$ => {
       // save previous state info
      }
    )
```

Am I missing something?
I was trying it with the alpha.3 version.

**Comment by christopherthielen** [comment]
> Isn't this code supposed to fire every transition?

The `'*'` glob matches only top-level states, as opposed to the `'**'` glob which matches any top level or child state.  

`$transitionsProvider.onStart({to:'**'}, cb)` should invoke the callback for every transition.   

---

```js
    $transitionsProvider.onEnter(
      {to: () => { return true; }},
      $transition$ => {
       // save previous state info
      }
    )
```
This code will fire for each state being entered (not just for each transition)

` $transitionsProvider.onEnter({ to: 'login' }, getFromStateFunction)` will fire when the login state is entered.

---

Take a look at the sample app's login state: https://github.com/ui-router/sample-app/blob/master/app/login.state.js

It defines a resolve `returnTo` which injects the current Transition, then figures out where the user should be sent back to after a successful login.  
The sample app accounts for two cases: 

1) a redirected request 
  - unauthenticated user is on e.g. 'welcome'
  - user attempts to access protected resource e.g. 'contacts', so the transition is redirected to 'login'
  - after user logins in, they should return to 'contacts' (the redirected transition's `to` state) because that's where they wanted to go
2) user clicks login
  - unauthenticated user is on e.g. 'welcome'
  - user clicks 'login' link
  - after user logs in, they should return to the 'welcome' page because that's where they came `from`

**Comment by eddiemonge** [comment]
@zirho does that answer your issue?

**Comment by christopherthielen** [comment]
closing because I don't think there's a bug here

**Comment by zirho** [comment]
@christopherthielen @eddiemonge  
Yes it resolves my issue.
Thank you so much for the support.
I really appreciated.
