### ISSUE TITLE
Error: [$injector:unpr] with $transition$ only after uglify

### ISSUE THREAD

**Issue by bartonsprings** [angular-ui/ui-router#2820]
I am running into this issue which only happens after minification using grunt uglify task. I may be doing something wrong with injection of the service. Everything works great without minification.

Also, as soon as I remove the $transition$ from the function and console.log, it works. Any thoughts on what may be going on here or how to properly use the special helper $transition$ and $state$. This is with v1.0.0 alpha 5.

`.run(['$rootScope', '$state', $timeout', $transitions', 
    function ($rootScope, $state, $timeout, $transitions) {
        $transitions.onSuccess({ from: '**', to: '**' }, function ($transition$) {
            console.log($transition$.$to().name);
        });
    }]);`

**Comment by christopherthielen** [comment]
Since the hook function is injected, it also needs to be annotated (using the array notation or `$inject`)

```
.run(['$rootScope', '$state', $timeout', $transitions', runFn }]);

function runFn ($rootScope, $state, $timeout, $transitions) { 
  function successFn($transition$) { console.log($transition$.$to().name); }
  $transitions.onSuccess({ }, ['$transition$', successFn ]);
}
```

However, this commit: https://github.com/angular-ui/ui-router/commit/ca45957901d53a77f69074d15ea87baf1b78a48c is a breaking change where hook functions are _no longer injected_, but always receive three parameters: 1) Transition, 2) Injector and 3) State

This change will land soon, in a new release
