### ISSUE TITLE
How could I hold a navigator active

### ISSUE THREAD

**Issue by ZhangJianQ** [angular-ui/ui-router#2824]
I have a page, there is a navigator on left, and main(changed) content on right. I want show a list, when click a row go to the detail page. the list and the detail page all show in the same ui-view.

Here is my code. I just want to hold the active(underline behavior) when click the user in the users list.
[http://plnkr.co/edit/uFpmejIu3pukxz2pVCmf?p=info](http://plnkr.co/edit/uFpmejIu3pukxz2pVCmf)

**Comment by christopherthielen** [comment]
`ui-sref-active` turns on the class only when its `ui-sref` is currently active.  Since your sref points to `list`, it's not active when you go to `detail`.  However, if you make `detail` a substate of `list`, then it will remain highlighted when you go to `list.detail`.

http://plnkr.co/edit/IJYoNGA7ag6SZTpNNAQo?p=preview

**Comment by ZhangJianQ** [comment]
@christopherthielen Thanks for your reply. The detail state is active with your method. But the controller of list will run before the controller of detail, is it right?? If I want remain active on both list and detail, and just run controller of detail, What should I do?

**Comment by christopherthielen** [comment]
if you're on `list` and navigate to `list.detail`, the controller of `list` does not get re-run because that state is *retained*
