### ISSUE TITLE
component template customization V2

### ISSUE THREAD

**Issue by kuhnroyal** [angular-ui/ui-router#2838]
From what I can tell, it is currently not possible to customize the generated template string for the component when using component-routing. Except for implementing an own `templateProvider`.

How would I go about adding custom CSS classes or attributes to a component template, for example like angular-material's `flex layout="column"`?

**Comment by christopherthielen** [comment]
you can always build the template yourself using `template: '<my-component class="flex" input="$resolve.data"></my-component>'`

The `component: ` is convenient, but it's just sugar for creating a route-to-component template

**Comment by kuhnroyal** [comment]
That is true but with multiple bindings this gets cumbersome.
Something like this would be nice.

```
...
component: {
   name: 'foo',
   attributes: 'flex layout="column"'
}
...
```

Or allow registration of a custom templateprovider.

**Comment by Tommatheussen** [comment]
I needed this as well, I got a hack to get around the flex attribute.
Since Angular Material only needs the flex attribute present, even if the values that are added to it are rubbish, it will still apply the flex (eg flex="blabla" will still apply the flex attribute correctly as full).

```
angular.module('foo')
  .component('bar', {
    templateUrl: ...,
    controller: ...
    bindings: {
      flex: '='
    }
  });
```

What this little piece does, is add the flex binding attribute to the component, and it tries to assign values to it. But since they are not specified, they are just added. Which results in the flex attribute being applied to the element.
The little piece would result in the following rendered html:
`<bar flex="::$resolve.flex" class="ng-scope ng-isolate-scope flex"></bar>`

I have not yet found a solution for the layout thing, since `::$resolve` get added in front of the bindings.

**Comment by christopherthielen** [comment]
> Or allow registration of a custom templateprovider.

We do support templateProvider (it's how `component:` template is built), so you can build the route-to-component template however you want: 
https://ui-router.github.io/docs/latest/interfaces/ng1.ng1viewdeclaration.html#templateprovider

**Comment by matt328** [comment]
+1 for @kuhnroyal's suggestion. I like to use the shorthand component syntax but I'm not crazy about it producing an html element that I can't add attributes or even a css class to.

**Comment by cadilhac** [comment]
Seems like my problem is related to that. I have a design where flex is used. I migrated my code to use ui-router with components and now my design is broken because some dom nodes have been added to represent the components I created. Since the flex css property relates to direct children, these inserted nodes broke everything.

**Comment by viros** [comment]
+1

**Comment by devotis** [comment]
I'm in the progress of migrating an AngularJS app to be component based (to prepare for eventual Angular migration). The nested views are introducing that extra layer of the component tag which messes up the layout. The app is on Angular Material too. 

What @kuhnroyal suggested as a solution would be exactly good enough.
```
...
component: {
   name: 'foo',
   attributes: 'flex layout="column"'
}
...
```

What @Tommatheussen suggested shows resourcefulness, but is not quite good enough.

We could use a custom TemplateProvider as suggested by @christopherthielen , but A. I wouldn't know how and B. the `component` configuration on a state is supposedly the sugar that most developers like.

**Comment by devotis** [comment]
@kuhnroyal I've figured out a workaround that works for me in an AngularJS 1.6.4, Angular Material 1.x setup. It stretches the immediate child to the ui-view which is the component created by the router state.

```javascript
angular.module('foo')
  .component('bar', {
    templateUrl: ...,
    controller: ...
    bindings: {
      isComponent: '='
    }
  });
```

And in your css, add:

```css
[ui-view] > [is-component] {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
  flex: 1;
  -webkit-flex: 1;
  -webkit-box-flex: 1;
}
```

**Comment by kuhnroyal** [comment]
@devotis The easiest way I found was using an Javascript superclass or a Typescript decorator, that ofc only works if you use ES6/Typescript.

Otherwise there are a few workarounds I have toyed with over the last couple months, none of them stands out, yours as good as any I guess.

**Comment by sevdog** [comment]
If, instead of extending `component` attribute of `Ng1ViewConfig`, there was a new attribute in `Ng1ViewConfig` called `attributes`?

Something like 
```
...
component: 'foo',
attrbutes: {
// no callable objects should be passed here
  bar: 'bar', // key-value
  baz: true // boolean
}
...
```
this could be passed to `makeComponentTemplate` method.

This solution will however leave an open issue: how to manage conflict between `bindings` and `attributes`. Maybe `attributes` should win.

It's just an idea.

**Comment by bitoverflow** [comment]
@devotis I ran into the same issue, where angular material requiring flex and layout attributes on every element child to make sticky toolbars work.

My workaround for now..

My ui-view is defined with `<div ui-view flex layout="column">`

On every completed state transation I manually add the classes normally added by the material attributes to the unreachable `<ui-view>` created by the router :

` 
const element = document.getElementsByTagName('ui-view');
element[0].classList.add('flex');
element[0].classList.add('layout-column');
`

combined with defining state components in the state config
`template: '<status-page layout="column" flex></status-page>'`

Using: angular-material 1.1.5, ui-router 1.0.6
