### ISSUE TITLE
calling API after prevent stateChangeStart

### ISSUE THREAD

**Issue by karan4336** [angular-ui/ui-router#2876]
i have a requirement to prevent the state change and call an API and then re-trigger the stateChange with initial params.

So I have a code like this 

``` js
$rootScope.$on($stateChangeStart, function(event, toState, toParams, fromState, fromParams, options ) {
    event.preventDefault();
    //doSomething
    callAPI.then(function(){
      $state.go(toState, toParams, options); 
    }, errorHandler();
});
function errorHandler() {
  //doSomething
 console.log('error occured');
}
```

whenever I am doing this, before my API call gets successfull, errorHandler() method gets invoked in response to $stateChangeCancel method invoked because event.preventDefault().

Please expalin why is it happening and how can I refactor to call API using this approach.

**Comment by christopherthielen** [comment]
> Please expalin why is it happening and how can I refactor to call API using this approach.

I can't explain it with the information you've provided because the code you posted isn't complete.  There's a syntax error in your `.then()`.

My best guess is that you're calling the error handler like  `.then(function() {}, errorHandler())`, instead of passing it in like `.then(function() {}, errorHandler)`

You mentioned

>  errorHandler() method gets invoked in response to $stateChangeCancel

but I didn't see any `$stateChangeCancel` handler?
