### ISSUE TITLE
How import angular-ui-router.d.ts of latest version

### ISSUE THREAD

**Issue by greatelv** [angular-ui/ui-router#2920]
My team have used typescript and we have used typings that declared tsd.json. Recently, we upgraded version of ui-router to 1.0.0-beta.1 but i cant find angular-ui-router.d.ts of this version in DefinitelyTyped
How import d.ts file in my project ? 
I want to use the pattern like "private $transitions:TransitionService" in my local project.

**Comment by christopherthielen** [comment]
We now publish the type definitions with every release, instead of separate publish to `DefinitelyTyped`.  This is the preferred method of publishing projects written in typescript (like Angular 2 project).

If you use `npm` to fetch `angular-ui-router`, and use `"module_resolution": "node"` in your `tsconfig.js`, then your IDE should use the typings files automatically.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules

We use `"typings": "commonjs/ng1.d.ts"` in our `package.json` to let your typescript compiler know where to find the typing information.

In your typescript you then just use `import {TransitionService} from "angular-ui-router";`

**Comment by greatelv** [comment]
the option 'moduleResolution' is awesome...
I resolve the problem
Thanks! @christopherthielen

**Comment by nvivo** [comment]
Sorry, but what about when not using modules?
I have a project that still uses ambient declarations. Is there a .d.ts bundle somewhere or should I build it myself?

**Comment by christopherthielen** [comment]
@nvivo there is not a .d.ts bundle.  I'm not even sure how to go about using the types in an ambient context.

All the types are currently exported from the .d.ts file in `node_modules/angular-ui-router/commonjs/ng1.d.ts`.  Everything I've read from the TypeScript folks is that this is the correct way to publish a TypeScript project.  I don't know how to enable your need for ambient declarations.  If it's possible, feel free to submit a PR.  I'll merge it if it doesn't break other users.

**Comment by NeoGenet1c** [comment]
@nvivo I've managed to 'bundle' the code through the usage of `typings install npm:angular-ui-router --save`. 

This will basically look into the `node_modules/angular-ui-router/package.json`, find the file specified in the `typings` attribute and somehow compiles it together. The output will be available in `typings/modules/angular-ui-router/index.d.ts`.

The problem is that the typings definition was built as a module (that's why it is in typings/modules/...) and not the ambient (a.k.a 'global') declaration. I tried to bundle it as a 'global' declaration using `--global` option like this: `typings install npm:angular-ui-router --save --global`, but I'm getting following error:

```
typings ERR! message Attempted to compile "angular-ui-router" as a global module, but it looks like an external module. You'll need to remove the global option to continue.
```
Maybe it's just a lack of my TS knowledge and I do not know what exactly I need to type in to get the correct suggestions. But it might be the case when there's actually something missing in the definitions.
