### ISSUE TITLE
How to resolve from a service with 1.0.x?

### ISSUE THREAD

**Issue by deleugpn** [angular-ui/ui-router#2926]
I have a piece of code that is working just fine with 0.3.x, but I would like to make usage of the `component: myComponent` attribute when defining a route, so I tried updating to 1.0.x, but my code stopped working. I've tried going through the releases notes (breaking changes), but could not find my problem.

```
            .state('app.user', {
                url: '/user',
                abstract: true,
                templateUrl: helper.basepath('user.html'),
                resolve: {authCheck: ['Authentication', function (Authentication) {
                    return Authentication.isAuthenticated();
                }]}
            })
```

In my head, the problem happens like this: `$stateProvider` is a provider injected at the `config` phase, so I can't inject my services. In order to rely on a service for the resolve, the above snippet of code will make sure to DI my `Authentication` service to the function and it will block that route in case of the promise being rejected.

 With 1.0.0beta, this piece of code gets an `undefined` error onto the console.

http://puu.sh/qF9qQ/e344ad268d.png

I tried replacing the object with an array and the error changes to: **Uncaught Error: Invalid resolve value: "Authentication"**

```
                resolve: ['Authentication', function (Authentication) {
                    return Authentication.isAuthenticated();
                }]
```

http://puu.sh/qF9Cy/46441e2d11.png

Both snippets will work under 0.3.x, but not under 1.0.0beta.

**Comment by christopherthielen** [comment]
Weird. Resolve API should be backwards compatible with 0.3.1.

The `undefined` in the console comes from the `defaultErrorHandler`, which is invoked when a transition fails for any reason.  

1) Put a breakpoint in the default error handler to see where the error happens.
2) Enable trace mode `app.run($trace => $trace.enable())`

---

In 1.0, transition hooks should be used instead of resolve for things like checking authentication.  Check this plunker, which demonstrates three ways to implement auth checking:

1) `restricted1` using a `resolve: `
2) `restricted2` using `onEnter` transition hook
3) `restricted3` and `restricted3.child` using a declarative hook which inspects the target state for a `requiresAuth` boolean (preferred)

http://plnkr.co/edit/nW1Q3Kth4E9bzLSQLJaI?p=preview
