### ISSUE TITLE
ui-router-ng2: Dependency injection into state's transition hooks

### ISSUE THREAD

**Issue by jspizziri** [angular-ui/ui-router#2927]
Is it possible to allow for dependency injection into the transition hooks (e.g. `onEnter`) on a state.

Ex.

```ts
import {Ng2StateDeclaration, Transition, State} from 'ui-router-ng2';
import FooComponent from './foo.component';
import {AuthService} from '../../services/auth.service';

export let REGISTRATION_STATES: Ng2StateDeclaration[] = [
  {
    name: 'foo',
    url: '/foo',
    component: FooComponent,
    onEnter: (trans: Transition, state: State, authService: AuthService) => {
      if(authService.isLoggedIn()) {
        trans.router.stateService.go('bar');
      }
    }
  }
];
```

It appears that this is in the 1.0 spec for AngularJS 1, but doesn't seem to be possible with Angular2.

**Comment by christopherthielen** [comment]
Get the Transition injector using `transition.injector()` then `.get(token)` the dependencies you need.

**Comment by christopherthielen** [comment]
Also I recommend returning `.target("foo")` from your hook to redirect the transition, instead of starting a different one.

**Comment by jspizziri** [comment]
Thanks!

I didn't realize there would be an injector on the transition service.

**Comment by jspizziri** [comment]
@christopherthielen, quick question. Does the `transition.injector()` return the RootInjector? or does it return the component injector, then look up the chain?

Thanks again!

**Comment by christopherthielen** [comment]
It [returns a UIInjector](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#injector), scoped to the "to state" of the transition.  A UIInjector returns resolve values, and delegates to the native injector if the token doesn't match a resolve.  The native injector for ng2 is the parent component's Injector.

Because of rc.5's `NgModule` and lazy loading, the native injector that we delegate to may change in 1.0.0-beta.2.  We may be delegating to the Injector for the NgModule, to ensure that a routed component has access to all the services defined in its `NgModule`.
