### ISSUE TITLE
.otherwise(), .when() should support a TargetState, not just URL redirection.

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2967]
something like this:

``` js
urlRouterProvider.otherwise(() => ({ state: 'foo', params: { fooId: 123 } }))
urlRouterProvider.when('/foo/:fooId', (arg1: ??, arg2: ??) => ({ state: 'bar', { fooId: arg2.fooId } }))`
```

**Comment by JamesHenry** [comment]
Is there any WIP for this @christopherthielen?

I was really hoping to implement the excellent migration strategy outlined by @bourey in her talk at ng-europe https://www.youtube.com/watch?v=2b-tEis9k4M for large ng1 apps. The source code from her talk is available here: https://github.com/bourey/ngupgrade-example/blob/aot/app/router-root.module.ts.

A critical part of it is that the Angular 2 <router-outlet> is used as a fallback template for any routes/states not handled by the router implementation for the Angular 1 app.

She is using `ngRoute`, so she is able to do this:
```
$routeProvider
    .otherwise({template : '<ng2-router-root></ng2-router-root>',
        reloadOnSearch: false});
```

Where `<ng2-router-root></ng2-router-root>` is purely a downgraded Angular 2 component with `<router-outlet></router-outlet>` as its template.

With the Angular 2 Router being entirely URL-driven, the fact that ui-router's `$urlRouterProvider.otherwise()` can only redirect the URL makes it incompatible with this strategy.

I would love to hear your thoughts!

**Comment by christopherthielen** [comment]
@JamesHenry I don't think implementing this issue 2967 would help enable the approach outlined by @bourey.  the implementation for this issue would make this:

```js
.otherwise({ state: 'migrate' });
```

roughly be equivalent to this:

```js
.otherwise(() => $state.go('migrate'));
```

In which case the standard UI router URL writing rules would apply.

**Comment by christopherthielen** [comment]
I'd also like to point your attention to the migration approach provided by UI Router: https://github.com/ui-router/ng1-to-ng2

**Comment by JamesHenry** [comment]
Thanks, Christopher!

I will definitely dig into that a bit more. Do you have any thoughts on how I might be able to proceed with the original idea?

Whether that is based on existing functionality or would require some tweaks (which you would be willing to accept as a PR :D)

I would ideally like to move to @angular/router as part of the migration.

**Comment by JamesHenry** [comment]
I realise it is a cheeky line of questioning, but any help is greatly appreciated!

**Comment by JamesHenry** [comment]
UI router has served me incredibly well for over 2 years!

**Comment by christopherthielen** [comment]
I would play with a State definition (that has no URL defined) which gets activated when the otherwise function is called.

basically this: 

```js
... .otherwise(() => $state.go('migrate'));

... .state('migrate', {
  template: '<router-outlet></router-outlet>'
});
```

**Comment by JamesHenry** [comment]
Thanks so much! That looks really promising for my case. I will nevertheless dig into https://github.com/ui-router/ng1-to-ng2 a bit more.

Thanks again for all your work on ui-router!
