### ISSUE TITLE
change state inside $transition onStart hook function got Error

### ISSUE THREAD

**Issue by xr** [angular-ui/ui-router#2977]
```
$transitions.onStart({
		to: (state) => state.auth
	}, () => {
		if (syncAuthCheckFailed()) {
                        $state.go('state_not_auth');
			return false;
		} else {
			return true;
		}
	});
```

error:

> message: "The transition has been superseded by a different transition (see detail)."

without $state.go() everything is fine

## update

even i just simply called the $state.go inside onEnter, same error appear.

```
onEnter: ['$state', function ($state) {
      	$state.go('guest');
}]
```

**Comment by xr** [comment]
without $state.go() everything is fine

**Comment by hulkish** [comment]
try this instead:

```
$transitions.onStart({
        to: (state) => state.auth
    }, () => {
        if (syncAuthCheckFailed()) {
          return $state.target('state_not_auth');
        } else {
          return true;
        }
    });
```

**Comment by xr** [comment]
@hulkish thanks, but no use..

**Comment by christopherthielen** [comment]
In ui-router legacy, people wondered why their transitions were failing.  In 1.0, we added a [default error handler](https://ui-router.github.io/docs/latest/classes/state.stateservice.html#defaulterrorhandler) which is printing the message that the original transition (to an auth state) was superseded by the new one (to `guest`).  Read more here https://ui-router.github.io/guide/ng1/migrate-to-1_0

1) Disable the default error handler in production mode  by calling `$state.defaultErrorHandler(function() { /* do nothing */});` (or provide some meaningful filtering/error logging)

2) The suggestion by @hulkish is the correct approach.  Instead of forcibly superseding the original transition, use `$state.target('guest')` to nicely redirect the original transition.

Enable `trace` to get more insight into what is happening.

`app.run(function($trace) { $trace.enable('TRANSITION'); })`

**Comment by ashwaniare** [comment]
I followed the same steps but getting `Error: Too many Transition redirects (20+)` . I am using `return $state.target('state_not_auth');` as you mentioned instead of `state.go('state_not_auth')`

**Comment by christopherthielen** [comment]
@ashwaniare I suspect your hook is being run in an infinite loop.  

- Hook is invoked on initial transition
- Hook redirects to `state_not_auth `
- Hook is invoked on redirected transition
- Hook redirects to `state_not_auth`
- ...

Make sure your hook doesn't redirect if it's already heading to `state_not_auth`.

**Comment by denlabs** [comment]
I'm experiencing similar issues using the same code @hulkish posted above.  Instead of "nicely redirecting" to my new target state (accessdenied)  it seems like the original state is being entered regardless: 
` $transitions.onBefore({
      to: (state) => {
        return state.data !=  && state.data.authorization.authRequired !== false;
      }
    }, (transition) => {
      let authenticationService = $injector.get('authenticationService');
      let authorization =  transition.to().data.authorization;
      if (!authenticationService.hasRole(authorization.hasRole[0], AuthUtil.getRoles()))
        return $state.target(states.accessdenied, {}, {inherit: false}); //this state is never loaded
      } else {
        return true;
      }`

I enabled trace and did notice that it tried Starting a new Transition to accessdenied however the previous state's resolve also fired a call to the api (which somehow caused the transition to fail?) even though I'd thought I stopped it from going to the 'app' state entirely?
`Started  -> "Transition#2( 'login'{} -> 'accessdenied'{"spon":null} )"`, however the pervious state's resolve

Transition #0 Digest #1: Started  -> "Transition#0( ''{} -> 'login'{} )"
 Transition #0 Digest #1: <- Success  "Transition#0( ''{} -> 'login'{} )", final state: login
 starting auth check for state 'app'
 auth check failed for user when attempting to access state app
 Transition #2 Digest #31: Started  -> "Transition#2( 'login'{} ->  'accessdenied'{"spon":null} )"
:8080/api/acl/check?query=%7B%22method%22:%22get%22,%22isArray%22:true,%22cancellable%22:false%7D:1 GET http://localhost:8080/api/acl/check?query=%7B%22method%22:%22get%22,%22isArray%22:true,%22cancellable%22:false%7D 403 (Forbidden)
trace.ts:203 Transition #2 Digest #34: <- Rejected "Transition#2( 'login'{} -> 'accessdenied'{"spon":null} )", reason: [object Object]

Any ideas?

**Comment by ashishrp** [comment]
Solution 
$transitions.onStart({
        to: (state) => state.auth
    }, () => {
        if (syncAuthCheckFailed()) {
                        return $state.target('state_not_auth');
           
        } else {
            return true;
        }
    });
