### ISSUE TITLE
$stateChangeSuccess

### ISSUE THREAD

**Issue by mm-rtin** [angular-ui/ui-router#299]
The $stateChangeSuccess event doesn't trigger when loading a page for the first time with a hash state such as: www.mysite.com/page/page_slug/#/hash1/hash2/ - 

Not using Angular HTML5 mode.

```
    $rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
        console.info('########## state change success');
    });
```

**Comment by jackvial** [comment]
Thanks @cm325. I using it in an Ionic project and was attaching the handler inside the $ionicPlatform.ready callback. Moving it outside $ionicPlatform.ready fixed it for me. It didn't cause an issue when running my app in the browser but it did cause an issue when running on an iPhone, must have been because of the slower startup time.
