### ISSUE TITLE
ui-router v1.0.0.beta.2 & Angular 1: ui-router hangs if you change state during resolve

### ISSUE THREAD

**Issue by MystK** [angular-ui/ui-router#3032]
How to reproduce
1. In your state, add a route that depends on an async(es6) resolve. Add a artificial timeout of 10 seconds.
2. Navigate to that state
3. Before the resolve completes, navigate somewhere else.
4. After the artificial timeout, note that the URL changed but you are in state #3. 
5. See that you are unable to change states until you hard refresh.

I will make a plunkr for this soon, unless someone else has time. :)

**Comment by christopherthielen** [comment]
I think this is fixed in upcoming beta.3.   #2972
Try adding this to your app as a workaround for beta.2:

```$transitions.onFinish({}, function() {})```

**Comment by MystK** [comment]
Thanks! That was it.

**Comment by josx** [comment]
Nice to read this!
Thanks a lot!

**Comment by RenanRossiDias** [comment]
For anyone who's still having problems with this:

I was using async calls within $transition hooks on my app.run.
Based on [this](https://github.com/angular-ui/ui-router/issues/3246#issuecomment-272845157) answer, i created a TransitionService to manage application transactions and keep track of what transactions are running on application in order to guarantee that only one transaction happens at a time. I achieved this by saving the current transaction on TransitionService and then aborting any previously saved transaction on every new transaction.
