### ISSUE TITLE
Change the order of the definitions of the `ui.router` (main) module above every other module definitions

### ISSUE THREAD

**Issue by mrhammadasif** [angular-ui/ui-router#3062]
I am using the `gulp-angular-modules` and the issue is that you have multiple modules defined I called an regexp which is getting the very first module definition of every library and then get the module name to auto-include the dependency in my app-modules.js file but for this library (not for the other libraries) I am unable to catch the first definition as the very first module definition is `ui.router.util` which is meant not to be included as dependency.

Just move the definition above the other module definitions so `gulp-angular-modules` gets working properly

Note: the module is defined at Line : 304
`angular.module('ui.router', ['ui.router.state']);`

**Comment by christopherthielen** [comment]
The order of module declaration is not meaningful.

What if somebody else asks us to put it as the _last module declaration_?  
What if the files are transpiled and bundled in a different order by webpack?

Putting `ui.router` first isn't something we'll commit to supporting.  However, if you create a pull request, I'll merge it.

closing because we won't commit to supporting this.  If you really really want this, make a pull request for both the `legacy` branch (which I assume you're using)  and `master` branch.
