### ISSUE TITLE
State.onEnter() does not behave as documented

### ISSUE THREAD

**Issue by csvn** [angular-ui/ui-router#3072]
Hello,

The `onEnter` hook on the state declaration does not match the documentation:
https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#onenter

``` javascript
.state({
  name: 'mystate',
  onEnter: function(trans, state) {
    console.log("Entering " + state.name);
  }
});
```

When I use `onEnter` it is injected by angular DI as usual (Angular 1.5). See plunkr for details:
https://plnkr.co/edit/lNS6CJThVvd1MK1y2AFd?p=preview

I can't create a pull request, since I'm not sure which is the correct option.

Have I missed something or is this not working as intended?

**Comment by christopherthielen** [comment]
The documentation is wrong!  Sorry about that...

For ng1 only the `onEnter/Exit/Retain` declared on a state are injected in standard ng1 style, like they are in version 0.3.1.

The transition hooks are no longer injected since beta.1:  https://github.com/angular-ui/ui-router/releases/tag/1.0.0-beta.1 ... However, for backwards compatibility, we are continuing to inject the state's `onEnter/Exit/Retain` and this should be in the API docs.

**Comment by csvn** [comment]
OK, thanks for clarifying. I might create a pull request later to fix the ng1 interface and documentation if I have the time.
