### ISSUE TITLE
ng2: deep rxjs imports?

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#3087]
We're currently importing from `rxjs/Rx` like:

```
import { Observable } from "rxjs/Rx";
import { ReplaySubject } from "rxjs/Rx";
import {Subscription, ReplaySubject} from "rxjs/Rx";
```

we might be able to do deep imports instead, so people don't have to load the entire `rxjs/Rx` package.  

Need some research on the proper approach to allow users to either load the entire rxjs as a bundle, or  build their own using webpack, etc.

**Comment by bfricka** [comment]
I think for ng2 this is an important issue. Here are some suggestions:

- Source repo should be refactored as you mention
- ng2 build should require peer dependency of rxjs as Angular 2 does. Since this is the standard practice it doesn't add anything that this community isn't already familiar with.
- ng2 build should chunk out vendor deps and exclude from bundle

As it stands the overhead associated w/ this is too large for us to use ui-router, even though we desperately want to (the angular 2 router is turning into a nightmare for complex routing).

Where are your thoughts on moving this forward? Is there something I can do to help w/ the builds / refactoring?

**Comment by aitboudad** [comment]
see https://github.com/ui-router/ng2/pull/5

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/ng2#28
