### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by sebakerckhof** [angular-ui/ui-router#3093]
Hello,

I'm using angular 1 ui-router 1.0.0-beta.3 and I have a route declaration like:
```js
angular
  .module(name, [... ])
  .run(handleTransitionErrors)
  .config(configureRoutes)

function handleTransitionErrors ($state) {
  $state.defaultErrorHandler(function (error) {
    switch (error) {
      case 'AUTH_REQUIRED':
        $state.go('auth.login');
        break
    }
  })
}

function configureRoutes($stateProvider){
$stateProvider
    .state('auth', {
      url: '/auth',
      component: 'auth',
    })
    .state('user', {
      url: '/user',
      redirectTo: 'user.profile',
      resolve: {
        currentUser: ['$auth',
          $auth => $auth.getUser().then((user) => new Promise((done, err) => {
            if (user) done(user)
            else err('AUTH_REQUIRED')
          }))
        ]
      }
    })
   .state('user.profile', {
      url: '/profile',
      component: 'userProfile',
    })
}
  
```

So if a user who is not logged in visits `/user` he will be redirected to `/auth` to login.
Now after the login, I want to redirect the user back to the route he was requesting.
However, the name of the `$state.$current().name` in the error handler callback is empty.

I've currently solved this by creating a history service like:

```js
function listenToChanges($history, $state, $transitions) {
  $transitions.onStart({}, function (transition) {
     $history.push(fransition.to());
  });
}

export default angular
  .module(name, [...])
  .service("$history", HistoryService)
  .run(listenToChanges);
```

But I'm wondering if this can be done simpler or better?

**Comment by christopherthielen** [comment]
The `Transition` object contain two key pieces of information:

1) the `from` state:
https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#from

2) the `Transition` object which was redirected (causing the current Transition):
https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#redirectedfrom

The Sample App has a `login` state which uses this information to build a  "returnTo" resolve value (which is a [`TargetState`](https://ui-router.github.io/docs/latest/classes/state.targetstate.html) object)

After successful login, the `login` state does a `$state.go()` to the `returnTo` TargetState

Read over this code: https://github.com/ui-router/sample-app-ng1/blob/master/app/main/app.states.js#L44-L83

For this to work, you should use a *transition hook* to perform auth (do not use `resolve` unless you're fetching **data**)

Read the `requiresAuth` hook in the Sample App:  https://github.com/ui-router/sample-app-ng1/blob/master/app/global/requiresAuth.hook.js#L1-L28 .  The hook uses [`data: { requiresAuth: true }`](https://github.com/ui-router/sample-app-ng1/blob/master/app/contacts/contacts.states.js#L17) on a state definition to trigger the hook.



Closing because I believe I've answered the question

**Comment by DoubleDot** [comment]
Even though i understand how the examples shows how to redirect to a state after authenticating, i don't see a solution for a "complex" state which has a few parameters. With that setup, they are lost.

When i was using 0.4.2 we build a service that kept the last "valid" redirectable state, but with 1.0 i'm strungling to find the right object to get/store.

Any chance you have more information / best practice regarding this issue?
