### ISSUE TITLE
$stateNotFound with 1.0.0 beta 3

### ISSUE THREAD

**Issue by dsebastien** [angular-ui/ui-router#3101]
Hello, 

I would like to know how to rewrite the code I currently have that handles the "$stateNotFound" event. From what I understood, I should now use the transition API, but for this specific error I don't know what to use and how.

Should I just check if transition.targetState().exists() in the $transition$.onError transition callback function? If transition.targetState.exists() is false, will transition.to() return null?

Sorry for the newbie questions btw :)

**Comment by christopherthielen** [comment]
> Sorry for the newbie questions btw :)

Don't be sorry, and that's not a newbie question at all!

`$stateNotFound` was replaced by [`onInvalid`](https://ui-router.github.io/docs/latest/classes/state.stateservice.html#oninvalid) but that detail didn't make it into the migration guide. 

I created [an issue](https://github.com/ui-router/ui-router.github.io/issues/5) to track this missing documentation.

### Why not a transition hook?

I can explain why `onInvalid` is different than transition hooks: 

We decided that an `Transition` object with an non-existent `TargetState` [shouldn't be allowed](https://github.com/ui-router/core/blob/1c77551084f5dd321b16b49d1641cc707b4753fc/src/transition/transition.ts#L111-L117).  This made a lot of things inside the `Transition` class more consistent (we don't have to check if the target state is `valid()` all over the place).  

Because of that, an `onBefore` transition hook doesn't make sense for this use case.  Instead, the `transitionTo` method of `StateService` [performs some pre-checks](https://github.com/ui-router/core/blob/1c77551084f5dd321b16b49d1641cc707b4753fc/src/state/stateService.ts#L315-L324) before [creating and running a `Transition`](https://github.com/ui-router/core/blob/1c77551084f5dd321b16b49d1641cc707b4753fc/src/state/stateService.ts#L363-L364).  

As long as I'm pasting code, here's the [onInvalid handler code](https://github.com/ui-router/core/blob/1c77551084f5dd321b16b49d1641cc707b4753fc/src/state/stateService.ts#L93-L118)

**Comment by dsebastien** [comment]
Thanks for the thorough answer. I'll test this now :)
One last question: what's the purpose of the .exists() method on Transition objects then? A leftover of an earlier design? Or are there still use cases for that?

**Comment by dsebastien** [comment]
Works like a charm, thanks a lot @christopherthielen !

**Comment by christopherthielen** [comment]
@dsebastien 

>One last question: what's the purpose of the .exists() method on Transition objects then? A leftover of an earlier design? Or are there still use cases for that?

Do you mean `TargetState.exists()`?  I don't see `exists` on the `Transition` object
