### ISSUE TITLE
Routed components + lazy modules (ocLazyLoad) ng1

### ISSUE THREAD

**Issue by alo** [angular-ui/ui-router#3102]
Hi! 

I'm trying to use ui.router(@version v1.0.0-beta.3) with component routed and oc.lazyLoad(@version v1.0.9)

**This is working**
```javascript
angular.module('app').config(
    ['$stateProvider',
    function ($stateProvider) {

      $stateProvider
        .state('app.sessions', {
          url: '/sessions', 
          template: '<sessions-comp></sessions-comp>', //this is the difference 
          resolve: {
            store: function ($ocLazyLoad) {
              return $ocLazyLoad.load(
                {
                  name: "sessions",
                  files: ["app/dev/sessions/sessions.js",
                    "app/dev/sessions/sessions/sessions.component.js",
                    "app/dev/sessions/shared/sessions.service.js",
                    "app/dev/sessions/shared/sessions-list/sessions-list.component.js"]
                }
              );
            }
          }
        });
      }
    ]
    );
```

**This is NOT working**
```javascript
angular.module('app').config(
    ['$stateProvider',
    function ($stateProvider) {

      $stateProvider
        .state('app.sessions', {
          url: '/sessions', 
          component: 'sessionsComp', //this is the difference 
          resolve: {
            store: function ($ocLazyLoad) {
              return $ocLazyLoad.load(
                {
                  name: "sessions",
                  files: ["app/dev/sessions/sessions.js",
                    "app/dev/sessions/sessions/sessions.component.js",
                    "app/dev/sessions/shared/sessions.service.js",
                    "app/dev/sessions/shared/sessions-list/sessions-list.component.js"]
                }
              );
            }
          }
        });
      }
    ]
    );
```

I've ask to the ocLazyLoad group [Link](https://github.com/ocombe/ocLazyLoad/issues/354)

[Repo to test](https://github.com/alo/oclazyload-uirouter-component-routing-tests)

Thanks!

**Comment by christopherthielen** [comment]
Very interesting.  I'll take a look.

For now I'll link to this plunker which has a lazy load component hook: http://plnkr.co/edit/3kvrVY?p=preview

**Comment by christopherthielen** [comment]
OK, I see how this happens now.

The template builder (which is how route-to-component works) requires that the component is available, in order to wire up inputs, etc.

- The template builder is invoked from [an `onStart` hook](https://github.com/ui-router/core/blob/master/src/hooks/views.ts#L19-L26) via [`view.load()`](https://github.com/angular-ui/ui-router/blob/master/src/ng1/statebuilders/views.ts#L135-L138).
- Resolves are fetched [in an `onEnter` hook](https://github.com/ui-router/core/blob/master/src/hooks/resolve.ts#L27-L43).
- `onStart` happens earlier than `onEnter`

You have two options:
- Use a transition hook to lazy load code
- Mark your resolve as "EAGER" using a [resolve policy](https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#resolvepolicy). (EAGER resolves are fetched [as an `onStart` hook](https://github.com/ui-router/core/blob/master/src/hooks/resolve.ts#L10-L25))

```
angular.module('myApp', ['ui.router', 'oc.lazyLoad'])
  .config(
  ['$stateProvider', '$urlRouterProvider',
    function ($stateProvider, $urlRouterProvider ) {
      $urlRouterProvider.otherwise('/');
      $stateProvider
      .state('app', {
        url: '/', 
        component: 'appComp',
        resolvePolicy: { deps: { when: "EAGER" } }, // LOAD `deps` RESOLVE EAGERLY
        resolve: {
          deps: ['$ocLazyLoad', function ($ocLazyLoad) {
            return $ocLazyLoad.load(
              {
                name: "lazyModule",
                files: ["./lazy-module.js"]
              }
            );
          }]
        }
      });
    }
  ]
);
```

**Comment by alo** [comment]
Thanks so much for the explanation!
