### ISSUE TITLE
How to get params from a parent state in 1.0.0 Beta 3

### ISSUE THREAD

**Issue by christophercr** [angular-ui/ui-router#3105]
Hi,

I'm trying out now the latest version 1.0.0 Beta 3 and I must say is awesome and more powerful. However I'm stuck now trying to refactor a breadcrumb component. The breadcrumb component takes the current state (child) and extracts the current params, and it does the same for all the parents up to the root state in order to construct a `Map<state, params>` so the breadcrumb contains everything needed to navigate to a certain state with the correct params when the user clicks on it.

Now in the 1.0.0 Beta 3 I can't find a way to get the actual value of the params. It seems I need to do something like this:

```javascript
// get current state own params (the same can be done with the parents via 'parent')
let stateParams: Param[] =  $state.$current.parameters({inherit:false}));
// then somehow filter only the state's own params and look them up in the $state.params
let params: StateParams = $state.params.
// but $state.params gets the current values (from the child)
```

But this would only work for the current state, how can I do the same for the parent states? What if the parent state has paramX = "hey" and the child overrides paramX = "hello", how can I get the "hey" value from the parent?

I'm afraid the docs are not clear enough...

**Comment by christopherthielen** [comment]
first off, I should mention that overriding parameters is (paramX defined in parent and child state) is not supported, and the behavior is undefined.  This is because most of the ui-router api uses an object of key/value pairs to provide parameter values.  I wish I could allow it, but it would demand some major API changes.

---

To get the transition params object, use [`Transition.params()`](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#params).  This returns all the transition parameters, but not organized by state.

---

To get the parameter values for each [PathNode](https://ui-router.github.io/docs/latest/classes/path.pathnode.html) (in the activated state), use the [`Transition.treeChanges()` function](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#treechanges).  From there it's trivial to get the parameter values:

```
var path = $transition$.treeChanges().to; // an array of `PathNode` for the `to` state.
var tuples = path.map(pathnode => [pathnode.state.name, pathnode.paramValues]);
var map = tuples.reduce((acc, [name, values]) => (acc[name] = values, acc), {});
```
