### ISSUE TITLE
1.0: Can't inject $transition$ into component's controller?

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#3110]
Trying to route to component, but the following throws an error: Unknown provider: $transition$Provider <- $transition$

```
.component('adminApplicants',{
    templateUrl:'admin.applicants.html',
    controller:function($http,$transition$){
    }
})
```

With legacy .controller("SomeCtrl",function($transition$){}), there is no error. Why?

**Comment by christopherthielen** [comment]
Yes, this is a limitation of route to component.

`$transition$` isn't a global service, it's a locally scoped injectable.  In old school `.controller()` style, ui-router actually instantiates the controller using `$controller(yourControllerFunction)` so we can pass locals to it (such as `$transition$`).  With route-to-component, we no longer instantiate the controller ourselves.  Instead, we generate a template string, such as `<admin-applications></admin-applications>` and let angular do its thing.

You can use component input bindings to address this:
```js
.component('adminApplicants',{
    bindings: { $transition$: '<' },
    templateUrl:'admin.applicants.html',
    controller:function($http,$transition$){
    }
})
```

Now the generated template looks like this:
`<admin-applications $transition$="::$resolve.$transition$"></admin-applications>`

The `$transition$` will be bound on your controller.

Keeping this ticket open because it needs to be added to the docs, here: https://github.com/ui-router/ui-router.github.io/blob/master/_guide/105.ng1-route-to-component.md

**Comment by shawnlan** [comment]
Makes sense. Thanks!

**Comment by mikemccaughan** [comment]
This also applies to https://ui-router.github.io/docs/latest/modules/ng1.html#_stateparams where it says to inject `$transition$` using `$inject`, which does not work as I get the same error as mentioned above. Also, the migration guide says to inject `$transition$` as well. Or, is there something I'm missing?

**Comment by sebastian-zarzycki-es** [comment]
Any reason why this doesn't work?
```
bindings: { myVar: '<$transition' },
```

"Error: [$compile:iscp] Invalid controller bindings definition for directive. Definition: {... myVar: '<$transition$' ...}

$transition$ is just very ugly name for a variable.

**Comment by christopherthielen** [comment]
@sebastian-zarzycki-es 

### alias resolve

You can create an alias in a resolve:

```js
  $stateProvider.state({ 
    name: 'home', 
    url: '/home', 
    component: 'home',
    resolve: { 
      homeData: () => 'home data',
      trans: '$transition$'
    },
  });
```

```js
app.component('home', {
  bindings: { trans: '<', homeData: '<' },
  template: `
  <h1>home state loaded: {{ $ctrl.homeData }}</h1>
  <h1>Transition ID: {{ $ctrl.trans.$id }} </h1>
  <div ui-view></div>
`});
```

### Global alias

Or you can give it a global alias using a transition hook:

```js
  $transitionsProvider.onBefore({}, trans =>
      trans.addResolvable(new Resolvable("flooble", () => trans)));
```

```js
app.component('foo', {
  bindings: { flooble: '<', fooData: '<' },
  template: `
  <h1>foo state loaded: {{ $ctrl.fooData }}</h1>
  <h1>Transition ID: {{ $ctrl.flooble.$id }}</h1>
`});
```

**Comment by shawnlan** [comment]
bindings: { myVar: '<$transition$' }

why would this causes an error?

**Comment by christopherthielen** [comment]
@shawnlan @sebastian-zarzycki-es it's the angular compiler that's complaining. 

`$transition$` doesn't match [this regular expression](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/compile.js#L986)

**Comment by aestheticsdata** [comment]
As says @mikemccaughan , there's a deprecation warning in the latest doc, and the official example in the official doc ( https://ui-router.github.io/docs/latest/modules/ng1.html ) is :

MyController.$inject = ['$transition$'];
function MyController($transition$) {
var username = $transition$.params().username;
// .. do something with username
}

It's still possible though to inject $transition$ in a resolve. But what is the best practice then when we need for instance a service and $transition$.params().index in the controller of the component ? : 
- a property in a resolve which is $transition$.params().index, and access it in the controller thru bindings, and a property in the resolve for the service
- a single property in the resolve which return an object which contains the index and the service
- a single property in the resolve which return the index, and inject the service directly in the controller

thanx.

-

**Comment by christopherthielen** [comment]
I've opened an issue with angular.js asking about allowing rename of bindings with a dollar sign:

https://github.com/angular/angular.js/issues/15586

**Comment by christopherthielen** [comment]
# To summarize this issue

- You cannot inject `$transition$` into a component controller's constructor when using route-to-component.
  - The `$transition$` object is not a global service
  - The component is constructed by angular itself, so we cannot provide additional DI locals
- You cannot rename the `$transition$` to a different variable on the controller in the component's `bindings`.
  - Follow https://github.com/angular/angular.js/issues/15586 to see if angular team will change this behavior

# Workarounds
- You can bind `$transition$` directly
  - `.component('foo', { bindings: { $transition$: '<' } })`
- You can globally alias the `$transition$` token yourself
  - `$transitionsProvider.onBefore({}, trans => trans.addResolvable({ token: "trans", resolveFn: () => trans });`
- You can locally alias the `$transition$` token yourself
  - `$stateProvider.state({ ... resolve: { trans: '$transition$' } });`
- You can map your component input (`blarble`) to a specific resolve (`$transition$`) using [ui-router component view bindings](https://ui-router.github.io/docs/latest/interfaces/ng1.ng1viewdeclaration.html#bindings).
  - `$stateProvider.state({ ... component: 'foo', bindings: { blarble: '$transition$' } });`


Because a) injecting into the component is impossible and b) I have no control over renaming the binding and c) there are four workarounds, I am closing this issue as `wontfix`

**Comment by shawnlan** [comment]
Just curious. For `$stateProvider.state({ ... resolve: { trans: '$transition$' } });`, that means a resolve can reference to another resolve by name string? And this will work too: `$stateProvider.state({ ... resolve: { trans: '$transition$', trans2: 'trans' } });`? (Not useful, I know)

This is specific implementation by ui-router?

**Comment by NeoGenet1c** [comment]
1st workaround:
```
.component('foo', { bindings: { $transition$: '<' } })
```

stopped working for me since Angular v1.6.* - Angular 1.5.9 was OK.

Now, I'm getting error `Cannot read property 'params' of undefined`, when trying to call `vm.$transition$.params()` from within the Controller.

Anyone experienced similar issues?

**Comment by shawnlan** [comment]
I think you need to use `$onInit`: https://toddmotto.com/angular-1-6-is-here

It's a breaking change in 1.6.

**Comment by christopherthielen** [comment]
> that means a resolve can reference to another resolve by name string?

@shawnlan yep, it's a holdover from quite a long time ago.

As seen here on the old old docs site: https://github.com/angular-ui/ui-router/wiki#resolve

> The resolve property is a map object. The map object contains key/value pairs of:
>     key – {string}: a name of a dependency to be injected into the controller.
>     factory - {string|function}:  If string, then it is an alias for a service.

This is implemented in 1.0 [as a resolvable](https://github.com/ui-router/core/blob/48c5af6ec4dd3d34eb113524f9960431be255744/src/state/stateBuilder.ts#L184) which is essentially:

```js
new Resolvable('trans', function($transition$) { return $transition$; }, ['$transition$'])
```

which itself is basically: 

```js
resolve: { 
  trans: ['$transition$', function($transition$) { return $transition; }
}
```

**Comment by christopherthielen** [comment]
Now Documented in the route-to-component guide: https://ui-router.github.io/guide/ng1/route-to-component#accessing-transition

**Comment by christopherthielen** [comment]
@sebastian-zarzycki-es @shawnlan 

Thanks to @frederikprijck for [creating the PR](https://github.com/angular/angular.js/pull/15594) which closed [this ticket](https://github.com/angular/angular.js/issues/15586)

It was merged, and should (I assume) land in angular `1.6.2`

**Comment by sebastian-zarzycki-es** [comment]
Great, thanks!

**Comment by wangxingkang** [comment]
@christopherthielen   
I would like to use `$ transition $` in the controller to listen for the `$ stateChangeSuccess` event, can i do?

```
vm.$onInit = function () {
      var onSuccess = this.trans.onSuccess();

      onSuccess({ }, function () {
        console.log(11111);
      })
    };
```

**Comment by loxy** [comment]
I need all the current params in an angular run block. How is that possible without using $stateParams?

**Comment by NeoGenet1c** [comment]
@loxy Inject `$uiRouterGlobals` and use its attribute `params` like this:

$uiRouterGlobals.params.myParam

**Comment by loxy** [comment]
Ah ok. Thank you!

**Comment by crhistianramirez** [comment]
Is this issue specific to angular components? I'm not able to inject it into a controller  for a directive.
