### ISSUE TITLE
How to pass data between two views

### ISSUE THREAD

**Issue by Wallcraft97** [angular-ui/ui-router#3128]
Hi guys, i have two views, One that contains a form, and the second that contains a table with ng-repeat.
The first view, when the send button is clicked, sends the name to a servlet, the servlet takes the parameter, do his calcs and return a response. This response contains information that are needed to create the table in the second view, the problem is that the table is empty.
If i put the table on the first view, the table get filled, in the second no. So the problem is that the controller don't send data to the second views. There's a simple way to pass data to the second views?

**Comment by realappie** [comment]
I think you are looking for services.

**Comment by christopherthielen** [comment]
There are many options for doing this. @realappie gave a valid option. Other options might include things like nested states with nested views.  However, since this is a issue tracker for bugs and feature requests, I have to close this issue. 

If you would like to ask further questions about _how to use angular and ui-router_, please ask them at StackOverflow: http://bit.ly/UIR-SOF
