### ISSUE TITLE
Multi-child states form and autoload child state

### ISSUE THREAD

**Issue by archasek** [angular-ui/ui-router#3148]
Hi!

I have something like this: https://plnkr.co/edit/Ah6To1rpQjrMXgtGHZ7T?p=preview

What I want to accomplish is:

1. When I get to the `index.form` state, I would like to automatically load one of my child states - index.form.step1 (this may vary in the future). It means that I want to have a link (`ui-sref`) to the parent and set it to make a redirect to one of the child states. Should I use just `onEnter` and then `$state.go()` or `$state.target()`?

2. I want my child states (form steps + maybe additionally the parent itself) to use the same controller (or anything else) to inherit and convey model values. On every step I would like to fill the form fields and at the end (the last step/child state) I want to have ability to submit the form with all values from all steps. How can I get it done?

What is the proper approach for these cases?

Thanks :)

**Comment by danpottshimself** [comment]
@archasek You could try using Angulars require component/directive to inherit from the parent state controller. Also, using .otherwise will allow you to enter a specific state when first loading based on a url. For example, .otherwise('index.form'); will open the index.form state when first loading or when there are no states to go to. Don't know if I've been much help there but good luck.

**Comment by archasek** [comment]
@danpottshimself I think using `require` is a good idea. But I didn't understand the part about `.otherwise`. Any example? The point was I wanted to autoload one of child states of `index.form` state.

**Comment by danpottshimself** [comment]
'otherwise' is part of Angular $routeProvider.It sets route definition that will be used on route change when no other route definition is matched. This can help you if you don't go to any route when first loading the game, it will go to the route stated in the otherwise. Its basically a safety blanket but can be used for setting a default state. 

Basic Example
var app = angular.module("myApp", ["ngRoute"]);
app.config(function($routeProvider) {
   $routeProvider
    .when("/home", {
        template : "<h1>Banana</h1><p>Bananas contain around 75% water.</p>"
    })
    .when("/form", {
        template : "<h1>Tomato</h1><p>Tomatoes contain around 95% water.</p>"
    })
    .otherwise("defaultRoute", {
        template : "<h1>None</h1><p>Nothing has been selected,</p>"
    });
});

You can also just use   $urlRouterProvider.otherwise('/form/');, given you inject $urlRouterProvider as a dependency

**Comment by danpottshimself** [comment]
> 'otherwise' is part of Angular $routeProvider.It sets route definition that will be used on route change when no other route definition is matched. This can help you if you don't go to any route when first loading the game, it will go to the route stated in the otherwise. Its basically a safety blanket but can be used for setting a default state. 
> 
> Basic Example:
> var app = angular.module("myApp", ["ngRoute"]);
> app.config(function($routeProvider) {
>    $routeProvider
>     .when("/home", {
>         template : "<h1>Banana</h1><p>Bananas contain around 75% water.</p>"
>     })
>     .when("/form", {
>         template : "<h1>Tomato</h1><p>Tomatoes contain around 95% water.</p>"
>     })
>     .otherwise("defaultRoute", {
>         template : "<h1>None</h1><p>Nothing has been selected,</p>"
>     });
> });
> 
> You can also just use   $urlRouterProvider.otherwise('/form/');, given you inject $urlRouterProvider as a dependency

**Comment by danpottshimself** [comment]
@archasek 
'otherwise' is part of Angular $routeProvider.It sets route definition that will be used on route change when no other route definition is matched. This can help you if you don't go to any route when first loading the game, it will go to the route stated in the otherwise. Its basically a safety blanket but can be used for setting a default state. 

Basic Example:
var app = angular.module("myApp", ["ngRoute"]);
app.config(function($routeProvider) {
   $routeProvider
    .when("/home", {
       template : “<span>hello world</span>"
    })
    .when("/form", {
      template : “<span>hello world</span>"
    })
    .otherwise("defaultRoute", {
           template : “<span>hello world</span>"
    });
});

You can also just use   $urlRouterProvider.otherwise('/form/');, given you inject $urlRouterProvider as a dependency

**Comment by christopherthielen** [comment]
@archasek
1) use [`redirectTo` property](https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#redirectto)

https://plnkr.co/edit/vl6vVwlFUexSd2GVNwvp?p=preview
```
.state('index.form', {
  redirectTo: 'index.form.step1'
  ... 
}
```

2) Define a model that holds all the data for all the steps.  Keep track the overall model in the resolve for `index.form`.  Each step can update the model directly (using databinding).  

In this example, I bound a `stepModel` property to each component, but you could also make the template bind directly to a subobject like `<input type="text" ng-model="wizardModel.step2.input">`

https://plnkr.co/edit/vl6vVwlFUexSd2GVNwvp?p=preview


Hope this helps
