### ISSUE TITLE
Updating bindings when state params change

### ISSUE THREAD

**Issue by davazp** [angular-ui/ui-router#3166]
Hello,

I am not sure if this functionality is available but, if it not, I would like to propose it as I think it fits very well with the new Angular 1.5 components.

Is it possible that, when some query parameters are updated, ui-router will re-evaluate the resolvers and updating the bindings for the components, so $onChanges is fired?  Without reinstantiating the component, like with `reloadOnSearch=false`, of course, I do not want to lose the rest of the state or redraw the template.

**Comment by christopherthielen** [comment]
This is a very clever idea, but it doesn't really fit with the ui-router design.

I think this might be a job for something like RxJS.   You can make your parameters `dynamic: true` and have a resolve which returns an observable.  When the query parameters change, the observable should emit a new object and you can update your component.

---

I really appreciate your idea, but closing because I don't think it quite fits (I'm willing to be argued at though), and I think there are other ways to accomplish this.
