### ISSUE TITLE
Parse url to state in ui-route 1.x for angular 1.x

### ISSUE THREAD

**Issue by funber** [angular-ui/ui-router#3174]
Hi,  I found this comment  - "**Nope, can't think of a way to do this, sorry (although it'll be possible in the new 1.0 version we're working on).**" in https://github.com/angular-ui/ui-router/issues/2166  

This feature has already been implemented?

**Comment by christopherthielen** [comment]
This should do the trick:
```js
$state.get().filter(state => state.$$state().url.exec(currentUrl));
```

`$$state()` allows you to access the internal state, which has a UrlMatcher on it

https://ui-router.github.io/docs/latest/classes/state.state-1.html#url
https://ui-router.github.io/docs/latest/classes/url.urlmatcher.html#exec

**Comment by mattbrunetti** [comment]
@christopherthielen Is it safe to access the internal state? If so, that would mean that "internal" API is locked down, correct? (or rather, it will be >= 1.0.0 and < 2.0.0, as per semantic versioning)

`eslint-plugin-angular` /w `eslint-config-angular` is warning me that "Using $$-prefixed Angular objects/methods are not recommended"  (rule name is angular/no-private-call), which generally makes sense assuming that $$-prefixed objects/methods are generally private. Is this the case here? (i.e. is it private?)

Does it make sense to have a way to get states from urls, using a public method, rather than private/internal one?

Thanks

**Comment by christopherthielen** [comment]
@mattbrunetti we make no guarantees about internal API.  They can change at any time, regardless of semver.  That said, I think the $$state().url is not likely to change any time soon.

> public method
Yes, but it's not high on the list of priorities

**Comment by graingert** [comment]
FYI you can get it with:

https://ui-router.github.io/ng1/docs/latest/classes/url.urlservice.html#match

```js
function foo($urlService) {
  const rule = $urlService.match({ path: '/', search: '...', hash: '...' });
}
```

**Comment by warby613** [comment]
@graingert thanks! Your `$urlService.match` approach worked to match all my routes, including nested ones.
The `UrlMatcher.exec` approach above was only able to match top level routes (having a root-relative url).
