### ISSUE TITLE
Examples of triggering parent state resolve and injecting parent resolve into child state?

### ISSUE THREAD

**Issue by Josh68** [angular-ui/ui-router#3200]
I must be missing something, but I'm having 2 fundamental issues using ui-router for Angular 1 v1b3 (routing to components).

1) Every time I try to inject a parent resolve into a child state, I get an unknown provider error. From what I've read, I thought I'd be able to inject a parent's resolve object properties by name into a child state's resolves. I'm also not clear whether using a redirect from the parent to the child destroys the parent's resolves (the parent-child relationship  seems to mean the parent state is retained).

2) Every time I try to trigger a resolve on a parent state by activating a child route (a resolve that's never run before), the resolves are not triggered. That is, if I do `$state.go('ChildRouteName')` the resolves on the parent route (whether abstract or not) do not run.

Are there some plunkers I can look at for clear examples of these patterns?

Thanks for all of your work.

**Comment by christopherthielen** [comment]
Hi @Josh68 

1) you should be able to inject parent resolves into children by name, as you stated.  
Redirecting *should not* affect this.   In 1.0, we have [tests specifically for this](https://github.com/ui-router/core/blob/b64973694e77c85ff331b51fc9d10ff8e975b4fb/test/resolveSpec.ts#L348-L398)
In fact, we take care not to trigger a resolve twice (once on the first transition, again on the new transition due to the redirection)

2) That's should also work like you expect.  A resolve on a parent state should run when the state *is entered*, regardless  of which state is the overall destination state (i.e., either the parent or child)

here's a simple plunker demonstrating 2) http://plnkr.co/edit/qnsRwES54qgUW35wloal?p=preview

**Comment by Josh68** [comment]
Thanks for the plunkr. I'm still having some issues with a more complex setup, but realized 2 new things:

1) NgInject doesn't work with providing nested resolves to child states, and, for me, neither does just injecting the parent resolve in the child resolve's callback, but using the old-style min-safe way of writing the resolve works:

no provider error:
`{
  childProp: (parentProp) => parentProp
}`

works:
`{
  childProp: ['parentProp', (parentProp) => parentProp]
}`

2) I somehow missed the option to trigger a reload on a state, and part of the issue I've been having is that I want to re-use a parent state for pre-auth and logged-in states. In one case, most of the resolves shouldn't run, but when logged in, they should. My impulse was to try writing a function that returns a resolve object with conditional resolve properties, but I can't figure out a pattern like that, and don't even see that it's available, according to the docs.

So I've just put conditions into the callback for each resolve property and reloaded the parent state after login. Now I'm just having a problem of my route not actively changing on a $state.go statement with the reload and location options set to true.

I think the use of these options should be more front-and-center in the docs, because the default of having a parent state's resolves not update any time a new child state is entered, while a sensible default, is something for which an override is probably a common need (like when switching between logged-out and logged-in states and using the same "master template" for both states - a template that needs lots of data on login).

Thanks again for your work and feedback.

**Comment by christopherthielen** [comment]
1) I suggest using [strictDi](https://docs.angularjs.org/api/ng/function/angular.bootstrap#usage) to ensure youve annotated all your resolves.  I'm not sure why you didn't get a provider error.

2) You've got the right idea using `{ reload: true }` or `{reload: 'parent.child' }` after login to re-fetch all the resolves.  

I might choose to have separate parent states for logged-in and not-logged-in, even if they end up routing to the same component, but with different resolve data.

---

As for docs, I'm open to suggestions.  where do you think the information about reloading states belongs?

---

I appreciate the feedback as well.  Closing now because I think all the issues except docs have been addressed.

**Comment by Josh68** [comment]
Although this is closed, I will look at the docs to see where I might suggest more details (or write them and do a PR).

Also, I originally did have two states for pre-login/post, referencing the same component. The thing there is dealing with which one wins in which application state, since the same url can trigger either state. I also tried every variation of abstract/not-abstract, url/no-url, with varied success. Suffice it to say it gets complicated, and I think reusing and reloading the parent/root state isn't a bad approach, especially if you can condition resolves.

If there's a good pattern for dealing with having 2 states with the same url and component, that's another example it would be nice to see.

Cheers
