### ISSUE TITLE
chore: run test suite against angular 1.6

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#3206]
A couple of changes in angular 1.6.0 affects the test suite:

- `$locationProvider.hashPrefix()` now defaults to `$locationProvider.hashPrefix("!")` instead of the empty string
  - https://docs.angularjs.org/guide/migration#-location-
- Transcluded simple strings are no longer wrapped in a `<span>`
  - Possibly due to https://github.com/angular/angular.js/issues/15223 but we also see spans generated at least since angular 1.2

Not affecting the test suite, but worth mentioning here:

- Rejected Promises without catch blocks print  error messages to the console: `Possibly unhandled rejection`

**Comment by mbarakaja** [comment]
There is a lot of weird behavior with angular 1.6. Navigating between states using the ui-router API works well.

The problem is when the user introduces the URL manually, in the browser, and the string `%2F` is inserted, which is equivalent to the `/` character. But additionally there is an extra `#` character, which I don't know from where is coming. Maybe that character is making the browser encode the `/` wrong.

So, for example  `/#/login` goes to  `/#!#%2Flogin`.

There is an issue related to this already; #3203.
