### ISSUE TITLE
Anchor not removed for subsequent states

### ISSUE THREAD

**Issue by pfeigl** [angular-ui/ui-router#3218]
The following might be intentional, but it is not what I would have expected. Perhaps someone could give me an alternative or confirm it to be a problem.

We are using version 1.0.0-beta.3

When having two links with an ui-sref, one of them having an anchor, after clicking the first one, every other link also shows the anchor.

An example of what I'm seeing is here:
https://plnkr.co/edit/Fiwxa02foATMFi98z4TB

Also here a short code example of what we are doing:

`<a ui-sref="hello({'#': 'test'})" ui-sref-active="active">Hello</a>`
`<a ui-sref="about" ui-sref-active="active">About</a>`

My expectation would have been, that I switch between "/hello#test" and "/about" but it actually goes to "/about#test".

Regards,
Philipp

**Comment by pfeigl** [comment]
sdfg`

**Comment by christopherthielen** [comment]
It was intentional (the "#" is tracked as a state parameter on the "root state").  Since default behavior for `ui-sref` is to inherit parameter values (`{ inherit: true }`), the hash is retained.

However, I see your point that the behavior is surprising.

You can clear out the hash manually by using `ui-sref-opts='{ inherit: false }'` or by explicitly passing null `ui-sref="about({ '#': null })"

**Comment by pfeigl** [comment]
Thanks for the feedback, is there any way to solve this on a more global level? Both of your options require me to more or less alter any link which does not currently have a hashtag, right?

**Comment by christopherthielen** [comment]
You could write a hook that redirects without the hash param value. It's a pain in the ass to get right, but at least it's global.


Based on this discussion and previous discussions, I think the hash value behavior should be changed. I'm just not sure what that looks like yet.

**Comment by pfeigl** [comment]
Nice to hear, that you will put some thoughts into this. I tried the hook approach, but not via redirect but by changing the params after the transition happened via the following code:

`
            $transitions.onFinish({}, function (trans) {
                trans.params("from")['#'] = null;
                trans.params("to")['#'] = null;
            });`

But this didn't seem to work unfortunately

**Comment by esinek** [comment]
Just what I was looking for! And that also goes for using `$state.go()`. Second param should have the `{ '#': null }` as part of that object.

**Comment by christopherthielen** [comment]
Here's one hook approach that uses private API:
http://plnkr.co/edit/8KoqPPhw9etOQfcdvHY9?p=preview

It alters the transition's to path and the params global object

---

Here's another that uses public API only:
http://plnkr.co/edit/8yWDI43lwz6ZmvQtjerL?p=preview

It detects a transition where the target state didn't include a hash (such as `ui-sref="about"`), but the computed parameters includes a hash (due to inherit). Then it redirects to a new target, clearing the hash in the params.

**Comment by pfeigl** [comment]
This is just perfect, thank you Christopher!

Shall I keep the ticket open for until you know, how to proceed with this topic or close it, as my concerns are actually resolved by your hooks?

**Comment by christopherthielen** [comment]
Let's keep it open. I'm considering making the hash parameter not inherit
by default.

**Comment by christopherthielen** [comment]
I'm making the hash parameter not inherited

**Comment by christopherthielen** [comment]
Closed by 849f84f7c35530b01d3ebae1a2fd500c2eebda21 in rc.1
