### ISSUE TITLE
(Question) Angular2 - Ng2StateDeclaration with nested views

### ISSUE THREAD

**Issue by danicomas** [angular-ui/ui-router#3223]
I have this:
```
let states:Ng2StateDeclaration[] = [
  { name: 'users', url: '/', component: UsersComponent },
  { name: 'user', url: '/users/:id',component: UserComponent, params: {id: null} },
  { name: 'userimages', url: '/users/:id/images', view: {
    user: { component: UserImagesComponent }
  }}
];
```
And

```
@Component({
	template: `
	<h1>{{id}}</h1>
	<nav>
      <ul class="nav nav-tabs">
        <li><a uiSref="user" [uiParams]="'{id:' + id +'}'">About Me</a></li>
        <li><a uiSref="userimages" [uiParams]="'{id:' + id +'}'">Images</a></li>
	  </ul>
	  </nav>
	<ui-view name="user"></ui-view>
  `
})
```

The **user** state is working well but How can I do work the state **userimages**? uiParams is not working with this state. @christopherthielen

Thanks in advance,

**Comment by christopherthielen** [comment]
For nested views you probably want also nested states

instead of
```
  { name: 'userimages', url: '/users/:id/images', view: {
    user: { component: UserImagesComponent }
  }}
```

make `userimages` a child of `user` by naming it `user.images`.  Also the url will append to the parent url, so strip off the duplicated parts:
```js
  { name: 'user.images', url: '/images', view: {
    user: { component: UserImagesComponent }
  }}
```

**Comment by danicomas** [comment]
Hi @christopherthielen,

By now an example with /{id/<string> doesn't exist. I attach a plunkr and you could see what I am referring:
http://plnkr.co/edit/NGYsRuaoVgmWav9CdWbn

**Comment by christopherthielen** [comment]
Here's a few issues with your plunker

- 1) `view:` should be `views:`

Note, however, I recommend avoiding named views, unless absolutely necessary.
Instead of:
```js
  { name: 'user.images', url: '/images', views: {
    user: { component: UserImagesComponent }
  }}
```
it can be simply 
```js
  { name: 'user.images', url: '/images',  component: UserImagesComponent }
```

and in `UserComponent` simply `<ui-view></ui-view>`

- 2) links to children don't need to re-set existing parms.  By default ui-sref uses `{ inherit: true }` so [all existing parameter values are re-used](https://ui-router.github.io/docs/latest/interfaces/transition.transitionoptions.html#inherit)

- i also added a `user.about` sub state and wired it up

- I also updated your links to use uiSrefActive to highlight the active tab.

```html
	<nav>
      <ul class="nav nav-tabs">
        <li uiSrefActive="active"><a uiSref=".about">About Me</a></li>
        <li uiSrefActive="active"><a uiSref="user.images">Images</a></li>
	    </ul>
	  </nav>
```

Note one of the links uses relative addressing (as an example) `.about`

**Comment by danicomas** [comment]
Really nice. Thanks for the information @christopherthielen. I have updated the plnkr solving the mistakes:
http://plnkr.co/edit/4riHNG?p=preview

**Comment by chat-du-cheshire** [comment]
Hi, could you tell me how can I replace ui-view compnent? I have a list 'items', and I want to display detail replacing list view 'items.item'. I tried to do this with views, but it doesn't work
