### ISSUE TITLE
Element attributes in 1.0

### ISSUE THREAD

**Issue by bathos** [angular-ui/ui-router#3231]
I couldn’t find a mechanism to supply attributes to a component in 1.0. I thought bindings might do it, but it seems they aren’t simply adding `attr="expression"` to the component element like I had imagined.

Is this functionality available? Use cases include usage of attribute directives — especially those associated with layout, e.g. in ngMaterial, which couldn’t justify unique wrapper components.

**Comment by christopherthielen** [comment]
> Is this functionality available? 

No, it's not available.  Can you just write a template for your state instead of "route to component"?

Instead of:
```js
.state('foo', { component: 'foo' });
```

do this:
```js
.state('foo', {
  template: '<foo attr="expression"></foo>'
});
```

> I thought bindings might do it, but it seems they aren’t simply adding attr="expression"

Bindings is explicitly for mapping resolves to attributes.  The resolves are bound using `attr="::$resolve.resolvename"`

---


I'm trying to gauge how common this request might be.  At the moment, it does not seem like it would be a common request, and the workaround (write the template manually) seems pretty trivial.  Therefore I'm closing as "wontfix", but if there's additional demand, we will consider reopening and implementing.

**Comment by bathos** [comment]
Yes, thanks! I hadn’t realized that `template` was still available when I asked, sorry — I was just following the migration guide and mistakenly thought `component` was a strict replacement for `template`. Still learning stuff & reading the source.

The new code is beautiful by the way. I’m having a great time with 1.0 so far — really appreciate the care that has gone into this project.

**Comment by christopherthielen** [comment]
> The new code is beautiful by the way. I’m having a great time with 1.0 so far — really appreciate the care that has gone into this project.

I appreciate those kind words 😄
