### ISSUE TITLE
'ui-sref' of Angular UI-Router not working as expected

### ISSUE THREAD

**Issue by jagchat** [angular-ui/ui-router#3238]
If I am working with href, UI Router works as expected. But, if I am using ui-sref, it is not working as expected.

I have two issues with the following example:

- the anchors 'link-series-2-no-param' and 'link-series-2-one-param' do not trigger 'otherwise' (they do in 'link-series-1'). What to do if they need to go to 'otherwise'?

- if you click all 'link-series-2' and do the same in reverse, it's not going to work (always shows the result of 'link-series-2-two-params', even if you click on others)

I am unable to properly format the code here and I posted code at:

http://stackoverflow.com/questions/41429784/ui-sref-of-angular-ui-router-not-working-as-expected

**Comment by christopherthielen** [comment]
That is expected behavior.  ui-sref uses `inherit: true` by default, which [inherits the current parameter values](https://ui-router.github.io/docs/latest/interfaces/transition.transitionoptions.html#inherit) when navigating.

Use `ui-sref-opts="{ inherit: false }"` or explicitly nullify the params you do not want to inherit `ui-sref='foo({ param1: 1, param2: null })'`

**Comment by TaylorPzreal** [comment]
use ```ui-sref-opts="{inherit: false}"``` it works, thx
