### ISSUE TITLE
Understanding versions

### ISSUE THREAD

**Issue by justageek** [angular-ui/ui-router#3255]
Can someone explain why there is a version 1 for Angular 1 and a version .3x for Angular 1?  What's the difference, which is the most current version?  The entire structure of the project is very confusing.

**Comment by christopherthielen** [comment]
UI-Router 0.3.x is the current "stable" version.  It's now considered "legacy" since ui-router 1.0 is in release candidate.

During development of ui-router 1.0 alpha releases, the core of ui-router was extracted and rewritten as pure javascript (well, typescript). The core code does not know anything about angular. That core code now lives in a separate repository: http://github.com/ui-router/core.  

UI-Router 1.0 for Angular 1 depends on ui-router-core.  80% of the `angular-ui-router` code comes from `ui-router-core`.  Only the "angular specific bits" live in http://github.com/angular-ui/ui-router.

The core code is also used to implement [UI-Router for Angular 2](https://ui-router.github.io/ng2/) and [UI-Router for React](https://ui-router.github.io/react/)

Hope this is helpful
moved to a separate repository at

**Comment by justageek** [comment]
Thanks!  That makes a lot more sense, I want to try the component routing so I'm getting the 1.0 rc to give it a whirl.

**Comment by christopherthielen** [comment]
I just updated the route to component guide. 

If you find it useful (and have twitter) feel free to RT this: https://twitter.com/ChrisThielen/status/819240599450746880 
:)
