### ISSUE TITLE
Nested state resolve injected into parent controller

### ISSUE THREAD

**Issue by madgozzilla** [angular-ui/ui-router#3256]
I have an abstract state with a controller and 2 child state. If I resolve some data in a nested state could I Injected into the parent controller cause ain't working for me.

**Comment by madgozzilla** [comment]
For further information : http://stackoverflow.com/questions/41596584/child-state-resolve-injected-in-a-parent-controller

**Comment by christopherthielen** [comment]
>  If I resolve some data in a nested state could I Injected into the parent controller cause ain't working for me.

No, the resolves are available for injection into the state that defines them, or any substates.  Parent states should not have access to resolve data from children states.

**Comment by madgozzilla** [comment]
So how those resolved data should be accessed from the parent controller ? Or there's no way to do that

**Comment by christopherthielen** [comment]
You can create a container object as a resolve in the parent, then add *properties* to that object in the child:

```
.state('parent', {
  resolve: { parentContainer: function() { return {}; } },
  controller: function(parentContainer, $scope) {
    $scope.container = parentContainer;
    $scope.$watch('parentContainer.childResolve', function(newval, oldval) {
      // do something with childResolve
    }
  }
})
.state('parent.child', {
  resolve: { 
    childResolve: function(container) {
      var childVal = {};
      container.childResolve = childVal;
      return childVal;
    }
  }
});
```

**Comment by christopherthielen** [comment]
You can also use 1.0.0-rc.1 and use parent/child component communications: 

https://ui-router.github.io/guide/ng1/route-to-component#routed-parentchild-component-communication

**Comment by cadilhac** [comment]
The parentContainer saved me from broadcasting events. It's a very nice way to constrain a communication from a child state to a parent state. I could not use the parent/child component communications technique in my case...
My real use case was this: a parent state shows 2 tabs containing 2 kind of listings. A child state loads a listing and display it in another pane. Depending on the type of listing, I have to activate one tab or another. Since the listing is a resolve from the child state, I could not get the information in the parent state to choose the right tab. So with your technique I let the child state determing the tab, I put its id in the parentContainer object and voila!
