### ISSUE TITLE
Error Cannot read property 'globals' of null

### ISSUE THREAD

**Issue by geun** [angular-ui/ui-router#326]
It happen sometime but I don't know why.

Do I need to check something?

**Comment by imeninnik** [comment]
Faced this issue, when a link that I click have `href="#"` , so change attribute `to href=""` hides the error

**Comment by mamartins** [comment]
I found this error using an OnEnter on a abstract state, no onExit or onEnter on the state I want to transition to

**Comment by nxtlvlgg** [comment]
I was also getting this issue in a redirect in an onEnter, and wrapping the $state.go in a $timeout seems to have done the trick, but it causes the initial state to flicker in before the state change. $location.path only seems to work with the $timeout as well resulting in the same issue. Anyone have an idea of how I might get the redirect without the flicker?

**Comment by codephobia** [comment]
I was also getting this issue in a redirect in an onEnter, and wrapping the $state.go in a $timeout seems to have done the trick, but it causes the initial state to flicker in before the state change. $location.path only seems to work with the $timeout as well resulting in the same issue. Anyone have an idea of how I might get the redirect without the flicker?

**Comment by mamartins** [comment]
I've also solved it with a timeout

**Comment by chaseoli** [comment]
@codephobia The reason you're getting the flicker is because when you use 'onEnter' and 'onExit' callbacks get called when a state becomes active and inactive respectively. When you use onEnter and in combination with the timeout ui-router it loads the current route then when your timeout completes your redirected with $state.go (or however your redirecting within the timeout). Instead try to do your redirect logic inside a 'resolve' (not onEnter). A resolve function will be run prior to the current route controller and view loading, so if you do a $state.go from within a resolve function your flicker should go away.

**Comment by A-Allam** [comment]
I face this issue while back from the browser window, and it's working fine from the app.
Is there any solutions?
