### ISSUE TITLE
API docs issues

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3262]
The example for `otherwise` in the [docs](https://ui-router.github.io/ng1/docs/latest/classes/url.urlrouter.html#otherwise) seems to be incorrect. I tried the following:

```js
.config(function($urlRouterProvider) {
  $urlRouterProvider.otherwise((url, router) => {
    router.stateService.go('error', {error: 'page-not-found'});
  });
})
```

But this resulted in an error `Cannot read property 'stateService' of undefined`.
I then moved the logic to the `run` cycle instead:

```js
.run(function($urlRouter) {
  $urlRouter.otherwise((url, router) => {
    router.stateService.go('error', {error: 'page-not-found'});
  });
})
```

This led to `Cannot read property 'go' of undefined`.

Upon analysis of parameters, I found that a boolean value is inserted as the first parameter to the function. Changing to:

```js
.run(function($urlRouter) {
  $urlRouter.otherwise((bool, url, router) => {
    router.stateService.go('error', {error: 'page-not-found'});
  });
})
```

Finally did the trick.

So not sure what that first parameter is, but it's missing from the example. In addition, the `return` statement in the example is superfluous.

Further, the docs [here](https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#to) should probably state: 

> Returns the state that the transition is going *to*

E.g. *to* instead of *from*.

**Comment by aj-dev** [comment]
`$urlRouterProvider` and `$urlRouter` are deprecated.

Try using `$urlServiceProvider.rules.otherwise((matchValue, url, router) => {});`.

All parameters are optional. See here https://ui-router.github.io/ng1/docs/latest/interfaces/url.urlrulehandlerfn.html

**Comment by christopherthielen** [comment]
The docs for `urlRouter` service (injected as `$urlRouter` at runtime) are correct.  For `$urlRouterProvider` (injected at config time), follow this chain:

[injectables](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html) -> [`$urlRouterProvider`](https://ui-router.github.io/ng1/docs/latest/classes/url.urlrouterprovider.html) -> [`$urlRouterProvider.otherwise`](https://ui-router.github.io/ng1/docs/latest/classes/url.urlrouterprovider.html#otherwise)

The reason for this is:

In angular-ui-router, we've always used `.config(function($urlRouterProvider) {})` to add rules like `otherwise`.  Those rules were passed the `$injector`, i.e.
```js
$urlRouterProvider.otherwise(function ($injector, $location) {
    return '/a/valid/url';
  }));
```

In ui-router-core, we're dropping the `$injector` wherever possible, but the ng1 code still should support it for backwards compatibility.   Since `$urlRouterProvider` is only an ng1 concept, it keeps the OLD API for use in `.config()` blocks.

**Comment by adamreisnz** [comment]
Thanks for the clarification, I'll review the doc changes and refactor my code accordingly
