### ISSUE TITLE
Add onBefore to method state of $stateProvider

### ISSUE THREAD

**Issue by tiberiuzuld** [angular-ui/ui-router#3269]
Hello,
I am using [Angular-ACL](https://github.com/mikemclin/angular-acl) to implement roles and permissions in the application.
Before 1.0 release was using resolve to make authorization with different permissions on each state:

```javascript
$stateProvider.state("devices", {
    resolve: {
       acl: resolveAcl(PERMS.SHOW_DEVICES)
    }, 
    url: "/devices"
});
```
In 1.0 release with [onBefore](https://ui-router.github.io/ng1/docs/latest/classes/transition.transitionservice.html#onbefore) is not working: 
```javascript
 $stateProvider.state('devices', {
      onBefore: resolveAcl(PERMS.SHOW_DEVICES),
      url: '/devices'
});
```
or [onEnter](https://ui-router.github.io/ng1/docs/latest/classes/transition.transitionservice.html#onenter) 

```javascript
 $stateProvider.state('devices', {
      onEnter: resolveAcl(PERMS.SHOW_DEVICES),
      url: '/devices'
});
```

Please add onBefore on [state](https://ui-router.github.io/ng1/docs/latest/classes/ng1.stateprovider.html#state) method of $stateProvider

Thanks

**Comment by christopherthielen** [comment]
Sorry, but the semantics for `onBefore` (if it were allowed to be defined on a state) are simply unclear.  Is it triggered when the state is navigated to?  What about when one of its substates are navigated to?  

This is why only `onEnter` `onExit` and `onRetain` [are implemented on a state object](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#onenter).  We won't be adding transition level hooks like `onStart`/`onBefore` to a state object unless we can clear up the semantics in a way that is intuitive to everyone.

---

Your `onEnter` hook should be sufficient, if it's implemented properly.  The hook can return [any HookResult to allow/cancel/redirect the transition](https://ui-router.github.io/ng1/docs/latest/modules/transition.html#hookresult).

---

However, I recommend adding metadata to your states (such as PERMS.SHOW_DEVICES), then creating a global hook (`onBefore` works great) which checks the permissions of the states being entered.  *Note, I'm not familiar with your third party library, so I'm using pseudocode*

```js
 $stateProvider.state('devices', {
      perms: PERMS.SHOW_DEVICES,
      url: '/devices'
});
```

```js
var transitionMatchCriteria = { to: state => state.perms != null }
$transitions.onBefore(transitionMatchCriteria, function(transition) {
  var AclService = transition.injector().get('AclService');
  var toState = transition.to();
  if (!AclService.hasPermission(to.perms)) {
    return false;
  }
});
```

This could be further enhances to use `data` for inherited permissions to child states, or to use `transition.entering()`  to check permissions for all nested states being entered.

---

Closing because we won't be adding `onBefore` to the state definition, and I've shown how to implement the pattern using a global hook
