### ISSUE TITLE
Specifying parameter type `string` results in it consuming additional parameters

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3286]
Given the following state definitions:

```js
$stateProvider.state('welcome', {
    parent: 'portal',
    abstract: true,
    template: '<ui-view/>',
    url: '/welcome/:token',
    params: {
      token: {
        type: 'string',
      },
    },
    resolve: {
      token($transition$) {
        const params = $transition$.params();
        return params.token;
      },
    },
  });

$stateProvider.state('welcome.loading', {
    url: '',
    component: 'welcomeLoading',
});
$stateProvider.state('welcome.details', {
    url: '/details',
    component: 'welcomeDetails',
});
$stateProvider.state('welcome.personalisation', {
    url: '/personalisation',
    component: 'welcomePersonalisation',
});
```

When I land directly on the `welcome.details` state, e.g. `/welcome/<token>/details`, the output of the transition is (correctly):

```
Transition #0 r0: Started  -> "Transition#0( ''{} -> 'welcome.details'{"token":"<token>"} )"
```

However, when I land on the `welcome.personalisation` page, e.g. `/welcome/<token>/personalisation`, the output of the first transition is:

```
Transition #0 r0: Started  -> "Transition#0( ''{} -> 'welcome.loading'{"token":"<token>/personalisation"} )"
```

Suddenly the `/personalisation` part of the route is appended to the token parameter, and the transition wants to go to the loading state instead.

What is happening here? Why would the router append a part of the path to the token parameter?

When I remove the following bit from the configuration:

```js
    params: {
      token: {
        type: 'string',
      },
    },
```

Then the second transition works as expected:

```
Transition #0 r0: Started  -> "Transition#0( ''{} -> 'welcome.personalisation'{"token":"<token>"} )"
```

**Comment by christopherthielen** [comment]
This is working as expected. 

The [`string` type](https://ui-router.github.io/ng1/docs/latest/classes/params.paramtypes.html#string) has a regexp which matches *anything*, including slashes.  The [`path` type on the other hand]](https://ui-router.github.io/ng1/docs/latest/classes/params.paramtypes.html#path) behaves like the `string` type, but does not match slashes.

I assume you're using `rc.1`?  The new types are mentioned in the release notes: https://github.com/angular-ui/ui-router/releases/tag/1.0.0-rc.1

Ctrl-F: "path parameters default to the new" (wish I could link directly to the heading, but github doesn't add ids)

---

The path parameters are defaulting to `path` type, so remove your `{ type: 'string' },` or change it to `type: 'path'` if you want to be explicit.  (note: you can also put the type in the url string like `'/welcome/{token:path}'`

Closing as wontfix because it works as expected.

**Comment by adamreisnz** [comment]
Ok thanks for clarifying. One question remains though: how come it works correctly for the welcome state, but not for the personalisation state? The definitions are the same for both. Seems a little bit fishy?

**Comment by christopherthielen** [comment]
> how come it works correctly for the details state (e.g. doesn't consume token), but not for the personalisation state (does consume it)? The definitions are the same for both. Seems a little bit fishy?

That does seem fishy.  Maybe there is a related bug...

**Comment by christopherthielen** [comment]
Seems to work as I would expect... in both cases it's matching the parent state: http://plnkr.co/edit/806jZ278rj9Zj44PfXn0?p=preview

Maybe you're activating the 'personalization' state using an href, but activating the 'details' using a ui-sref?  what happens if you refresh on the 'details' state after its activated?

**Comment by adamreisnz** [comment]
No I was landing on both directly (e.g. changing URL in my browser).
I will try to replicate it somehow.

**Comment by christopherthielen** [comment]
sounds good, thanks.

**Comment by adamreisnz** [comment]
I've played around with it a bit more, and I think I know what's happening.

http://plnkr.co/edit/1wBz2akmVPsQoQwaEtvJ?p=preview

The order in which the routes are defined (or loaded after code concatenation/minification) matters here. In the above plunker, do the following:

1) Click on the `details` link, and observe the following output:
```
Current URL: /welcome/foo/details 
Current State: welcome.details 
Current Params: { "#": null, "token": "foo" }
```

2) Click on the `personalisation` link and observe the following output:
```
Current URL: /welcome/foo/personalisation 
Current State: welcome.loading 
Current Params: { "#": null, "token": "foo/personalisation" }
```

What happens, is that ui-router never gets in the personalisation state, because it thinks the token is `foo/personalisation` and it greedily consumes the `/personalisation` part, matching the URL to the loading route state instead of the personalisation state.

Removing the bit:

```
    params: {
      token: {
        type: 'string',
      },
    },
```

from the welcome state fixes the issue because as you said string type will match anything, including `/`.

So I suppose this works as intended, and the mistake was to use the string type rather than path. The confusing bit, that one route worked correctly and the other didn't, is due to the order in which they are loaded and in which ui router maps the URL to states.
