### ISSUE TITLE
Does the `onFinish` lifecycle hook have guaranteed access to async resolvables?

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3292]
I couldn't find this documented, and it *looks* like it's the case, but just wanted to confirm; does the `onFinish` lifecycle hook have guaranteed access to async resolvables? In other words, if I use `transition.injector().get('user')` and the `user` was resolved via a promise, is it guaranteed that this injection will have the resolved user available to it?

Same question for `onEnter`, but for resolvables which are provided by a parent route. It seems to be the case that if I have a parent route with a resolveable, then when the child route `onEnter` hook is called, that resolvable is always available. Could you confirm that?

(Ref: https://ui-router.github.io/ng1/docs/latest/classes/transition.transitionservice.html#onfinish)

Edit: I am aware that if using the `NOWAIT` policy the resolvables will not be available probably.

**Comment by christopherthielen** [comment]
your assumptions are all correct.

When `onStart` runs, we fetch all the `EAGER` resolves before continuing.
When each state is entered, we fetch all its `LAZY` resolves before continuing.

Since `onFinish` is after `onEnter`, all the resolves are fetched.
Since parent states are entered before children, the parent resolves are fetched before the child state is entered.

**Comment by adamreisnz** [comment]
Great thank you! :+1:
