### ISSUE TITLE
Question about Versions 0.2.x | 0.4.2 | 1.0

### ISSUE THREAD

**Issue by squadwuschel** [angular-ui/ui-router#3303]
Hi,

currently I am using 0.2.8 and I am not using any npm or gulp only NuGet. 
But I am using TypeScript with typings from 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/angular-ui-router

that works fine so far.

Now I would like to Upgrade and the only compatible Version I've found without npm was 0.4.2 where I cann use the typings from DefinitelyTyped is this version getting bugfixes if there are some bugs or is this also a "dead" version like 0.2.8.

And when should I use 1.0 instead of 0.4.2? Will there be a NuGet compatible version for 1.0 in the future with "plain" typings?

**Comment by christopherthielen** [comment]
0.4.2 is still the latest "stable" release and is not even 2 weeks old.  0.4.2 is the latest in the `legacy` branch.  We jumped from 0.2.x to 0.3.x and 0.4.x because there were some potential breaking changes, as documented in the release notes.  If you want to stay on the legacy branch, I recommend moving to 0.4.2.  0.4.2 will continue to get any critical bug fixes (such as the recent change in angular 1.6.x promise handling).  Other than those critical bug fixes, it will not be developed any further.

On the `master` branch, `1.0.0-rc.1` is the latest release.  rc.1 looks good, so I don't think we'll need an rc.2.  The next release will likely be 1.0 final, so now would be a good time to [think about the update](https://ui-router.github.io/guide/ng1/migrate-to-1_0).

We don't have any control over NuGet published version.  Some third party published it there.  We only publish to npm (and for legacy reasons, we still publish the ng1 releases to bower).

We also aren't involved in the DefinitelyTyped typings.  That was also published by a third party (which is totally awesome).  DefinitelyTyped "plain typings" are sort of a band-aid or stop-gap solution for non-typescript projects.  Now that ui-router is written in Typescript, there's not much of a reason to publish separate typings to DefinitelyTyped.  The official typings are distributed and updated in each released version. 

Hope these answers are helpful
