### ISSUE TITLE
1.0 error handling on route

### ISSUE THREAD

**Issue by avilao** [angular-ui/ui-router#3307]
Good afternoon. I want to have a default error state when one of the resolves gets 404.

I'm doing the following:
```
 $transition$.onError({}, function ($transition$) {
                $state.go(errorHandlerState, $transition$._error);
});
```

Is this the correct way? It doesn't seem to reach the state:
```
Transition #0 r0: <- Rejected "Transition#0( ''{} -> 'supplierPortal'{"alias":"hh3"} )", reason: [object Object]
```

Thank you.

**Comment by avilao** [comment]
This happens if i stay in the same state but the params are different. The reason object contains the previous params.

**Comment by christopherthielen** [comment]
There's a duplicate issue reported where we had some related conversation: https://github.com/angular-ui/ui-router/issues/3331

http://plnkr.co/edit/gFKhztf49VYnvQAqlAVV?p=preview

Your code is probably not working because `$transition$._error` isn't a valid parameters. 

Try: `{ error: $transition$.error() }`
