### ISSUE TITLE
Issue with changing states if multiple apps are running

### ISSUE THREAD

**Issue by kristoforsalmin** [angular-ui/ui-router#3318]
Hello everyone,

I ran into an issue with new _route to component_ feature of UI-Router. If I have two independent apps running at the same time then only one of them is able to change its states. The other app will crash if I tried to change its state.

It is not an issue when I use regular _route to controller_ approach.

Can anyone please help me figure out how to fix that issue?

Thanks

**Demos**

* [Route to component demo](https://jsfiddle.net/qe6b5htw/2/)
* [Route to controller demo](https://jsfiddle.net/nzqew1zq/2/)

**Environment details**

Chrome v56.0.2924.87, AngularJS v1.5.8, UI-Router v1.0.0-rc.1.

**Comment by christopherthielen** [comment]
Thanks for the fiddles!

ui-router doesn't currently support running multiple times in a single browser.  The `$injector` instance in your plunker is probably causing the problem.  We (unfortunately) track that service as a global object.  

In this case, since the code in question is not in ui-router-core, it's pretty easy to fix to use the correct $injector instance, but you'll likely encounter other (more subtle) problems running two instances in the same browser.  

We also track the Promise implementation (`$q`) as a global, so it's also currently being shared between angular apps, which might cause issues with proper digest loop integration

**Comment by christopherthielen** [comment]
In the future we may be able to scope the internal injector and promise apis to a single router instance, which would allow for multiple simulatenous apps.

As an aside, I'm curious about your ui-router apps.  You must not be using URLs since they would conflict, so what features of UI-Router do your apps use?

**Comment by racse1** [comment]
Thanks for the feedback! You are right, the URLs would be messed up. I primarily use states (without URL)  and transition listeners to handle situations of different kind in scalable way (instead of going for directives like `ngShow` or `ngIf`).
