### ISSUE TITLE
onBefore hook doesn't work as expected

### ISSUE THREAD

**Issue by Skfsh** [angular-ui/ui-router#3329]
I've been testing a redirect-after-auth <a href="https://github.com/ui-router/sample-app-ng1/blob/master/app/main/app.states.js#L59-L83">mechanism</a> from UI-Router's sample app.
It works great, but suddenly problem occurs in onBefore hook. 
The hook is registering and executing as expected but redirect to returned TargetState is not happening, although the promise resolves correctly.

Expected behaviour: "root" -> redirectTo "login" -> executing logIn() method -> returnTo "root" -> redirectTo "login" -> redirect to "home"

Actual behaviour ->  "root" -> redirectTo "login" -> executing logIn() method -> returnTo "root" -> redirectTo "login" -> stuck at "login" state
Have I misunderstood something?

Check out the <a href="https://plnkr.co/edit/UX3oQPMOtbQhCQKfYHOo?p=preview">plunker</a>.
Sorry for a bit complicated example.
UI-Router's version is v1.0.0-rc.1

**Comment by christopherthielen** [comment]
You've got the right idea, but there's a bug in rc.1 that is solved.  I modified your plunker with the code built from master:  https://plnkr.co/edit/M6TnELF2DnbXIqLtzkZN?p=preview

The problem was that the "ignored transition" code was being run before the promise from your  onBefore hook could be processed.  So it thought you were going from "login" to "login" and ignored the transition.  This is fixed by https://github.com/ui-router/core/issues/40 and https://github.com/ui-router/core/commit/30b82aacae66883fc603e199b2a8690edaf1903d and will be in rc.2, so closing I'm going to close this ticket as fixed.
