### ISSUE TITLE
forward slashe being replaced by %2F in the latest version of UI-router

### ISSUE THREAD

**Issue by amitneg1** [angular-ui/ui-router#3350]
forward slashe being replaced by %2F in the latest version of UI-router

Application is hosted on S3

Please help us asap

**Comment by christopherthielen** [comment]
Please provide the relevant details.

Forward slashes where? In urls? in path parameters? query parameters?
How do you expect they should be encoded?

Please provide a plunker that demonstrates the issue:  http://bit.ly/UIR-Plunk

Closing because there isn't enough information to answer.  Re-open when you have provided necessary details.
