### ISSUE TITLE
how to set query params to array even if it has only one element?

### ISSUE THREAD

**Issue by ibreathebsb** [angular-ui/ui-router#3369]
define state :
`url: '/list?assigned_domain&assigned_plan`

if i input `?assigned_domain=2&assigned_domain=265` then i got an array,
but when i input  `?assigned_domain=2` the param becomes a single string,
how to make it an  array even if it has only one element?

**Comment by mischkl** [comment]
I ran into this today .. I get the error "invalid parameters" even though I wrap  the parameters as an array, because apparently UI-Router automatically converts it into a string!!

**Comment by christopherthielen** [comment]
For query parameters, we can't guess if you want the data as an array or not, so we automatically wrap as an array if multiple values exist, but for the most common case (single parameter value) do not wrap.

Use `array: true` in a [`params` block](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#params) on your state.

```
...
url: '/list?assigned_domain&assigned_plan',
params: { 
  assigned_domain: { array: true }
}
...
```

**Comment by mischkl** [comment]
Unfortunately it seems this touches on a subtle bug in UI-Router that is still present. Namely, if you specify array parameter types in the `url` field of the state definition, UI-Router seemingly ignores the specification and auto-converts array types to strings anyway. This is the only case as far as I know where specifying types in the URL does not work as expected.

For instance, we are implementing a search that has the ability to sort items by multiple properties. If we specify the route as follows:
`/search?{sortBy: string[]}`
and then only specify a single property to sort by, it will arrive as a string instead of an array, despite the fact that we told it we expected an array. This is obviously pretty bad from a coding perspective because it means that if we try to call array properties on the data (which is unexpectedly a string), it will crash the application. Even worse, UI-Router itself throws an error due to mismatched param types, even thought it's caused by its own auto-conversion!

For now we've added the fix (aka workaround) that you described above, by manually configuring the properties via the `params` block. However, IMHO it's a bug that plenty people are likely to trip over, if the array types specified in the URL don't actually get adhered to.

**Comment by ibreathebsb** [comment]
set `array:true` can solve this problem,while i find another solution:
convert `[1,2,3]` to string `'[1,2,3]'` to shorten the url
