### ISSUE TITLE
Transition to same state keep the query string

### ISSUE THREAD

**Issue by dreignier** [angular-ui/ui-router#3376]
I have a state like this:

```
'home' : {
    url: '/{id}?message
}
```

My problem is the following: 

If i browse to a state with a message (like `$state.go('home', { id: 'test', message : '42' });`, my url is correct. I got `/test?message=42`. But now if i do `$state.go('home', { id: 'test2' });`, my new url is `/test2?message=42`. And worst of all, `$stateParams.message` is still `'42'`.

Why `message` is still here ?

**Comment by christopherthielen** [comment]
Because ([as the documentation states](https://ui-router.github.io/ng1/docs/latest/classes/state.stateservice.html#go)) state.go uses [the `{ inherit: true }` option](https://ui-router.github.io/ng1/docs/latest/interfaces/transition.transitionoptions.html#inherit)

Specify `inherit: false` if you do not want the parameter values to be inherited.

Next time, please respect the issues template; this question is better suited for stack overflow: http://bit.ly/UIR-SOF
