### ISSUE TITLE
$stateParams is different in version 0.2.18 & 1.0.0

### ISSUE THREAD

**Issue by tgly307** [angular-ui/ui-router#3431]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:
- [x] Feature Request

My version of UI-Router is: (1.0.0 and 0.2.18)

i found this issue when use the demo (http://angular-ui.github.io/ui-router/sample)
The demo use the 0.2.18 version, '$stateParams' and '$state full url' are showed normal, but when i use the 1.0.0 version, the result of these two attributes is not the same.

**0.2.18version:**

> $state = home
> $stateParams = {}
> $state full url = /

**1.0.0version:**

> $state = home
> $stateParams = {"#":null}
> $state full url =

i dont know if this is a new feature or something wrong. Did I use this in right way?

**Comment by christopherthielen** [comment]
The difference in `$stateParams` is due to the way hash is handled by the router in 1.0.  In 1.0+, the hash value can be set using a parameter value (`$state.go('foo', { #: 'newhashvalue' })`).

Also note that [`$stateParams` is deprecated](https://ui-router.github.io/guide/ng1/migrate-to-1_0#stateparams-deprecation) in favor of injecting the transition and getting `$transition$.params()`
