### ISSUE TITLE
Resolve doesn't work with components and nested view

### ISSUE THREAD

**Issue by kopach** [angular-ui/ui-router#3434]
This is a:

- [x] Bug Report

My version of UI-Router is: (1.0.0-rc.1)

# Bug Report

#### Current Behavior:

When using nested views with angular components - there is no ability to define `resolve` section independently per each view. When I do so - component isn't rendering at all

#### Expected Behavior:

Each nested view should have independent resolve section

#### Link to Plunker that reproduces the issue:

https://plnkr.co/edit/pfW3cPjxJsBipSqxmgEx

**Comment by Anber** [comment]
It was an undocumented feature in 0.3.x and now it's removed. More info here #2717.
I have my own workaround for this case. If you want, I can publish it as a package.

**Comment by christopherthielen** [comment]
@kopach Anber is correct, this was never officially supported because resolves cannot be *scoped to a view*. 

In 0.x you could declare them at a view level, but it was the same behavior as declaring them at the state level.  In addition, if you declared two resolves with the same name in two different views, the results were undefined.

In this example, the resolved value for `foo` is non-deterministic.  For this reason we no longer support the behavior of 0.x.
```
.state('foo', {
views: {
  view1: { 
    resolve: { foo: function() { return "ABC"; } }
  },
  view2: {
    resolve: { foo: function() { return "DEF"; } }
  }
});
```

**Comment by kylephp** [comment]
@Anber Could u publish your workaround?
