### ISSUE TITLE
Can not disable the highlight on previous clicked menu while click next menu .

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [angular-ui/ui-router#3455]
My version of UI-Router is:v0.3.2 (version)

# Bug Report

#### Current Behavior:
The landing page menu is always highlighted even after clicked on other menu.

#### Expected Behavior:
Here I need when user will click on any menu that menu will be highlighted and initially the landing page menu will highlight.I have all details in stack overflow.
https://stackoverflow.com/questions/44278666/can-not-disable-the-highlight-on-previous-clicked-menu-while-click-next-menu-usi/44278875?noredirect=1#comment75565409_44278875.

Please check this link and try to resolve my problem.
#### Link to Plunker that reproduces the issue:

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [x] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [ ] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by schester44** [comment]
looks like your markup is incorrect. Your landing page is your parent state whereas the other pages are children to your landing page. You need to use `ui-sref-active-eq="active"` instead of `ui-sref-active="active"`. Links to your children should also use `ui-sref-active-eq="active"`.

Some additional reading: https://stackoverflow.com/questions/24669462/ui-router-active-class-for-parent-menu-when-submenu-selected
