### ISSUE TITLE
redirect form abstract state to child state

### ISSUE THREAD

**Issue by X4V18** [angular-ui/ui-router#3456]
Hi,

I'm trying to redirect the route that match an abstract state to a default child state.
I'm using the version 1.0.0-beta.3.
This is an real simple example of what I'm doing.
Is it normal that the $urlRouterProvider.when("/abstract-state", "/abstract-state/reachable-state"); does not change anything ? Even with with that part of code, I still get an error saying "Error: Cannot transition to abstract state 'test'"

There is Demo : https://codepen.io/X4V1/pen/OmKeBJ

**Comment by christopherthielen** [comment]
URL rules only affect url synchronization.

Since your demo performs `$state.go('test1')`, the transition is created and subsequently rejected before the URL ever has a chance to change, and so the rules are never processed.

As your demo also shows, you can redirect using an `onBefore` hook.

You can also simply mark the state as non-abstract and use a `redirectTo` rule as seen here: https://codepen.io/anon/pen/MoYwGz?editors=1010
