### ISSUE TITLE
Route not work in production server with Rails 

### ISSUE THREAD

**Issue by NSLog0** [angular-ui/ui-router#3463]
I use ruby on rails in development I have a trouble with route can't find views then solved with gem "angular-rails-templates". It's woking well. Since I deploy application I got empty page no error both server(log) and browser(inspector). If anyone used to work with rails and angular I posted the other information in gem "angular-rails-templates" repository here https://github.com/pitr/angular-rails-templates/issues/155 and Help me find out please

My version of UI-Router is: "0.2.18" and In my bower I put "angular-ui-router": "~0.2"

**Comment by avatarr** [comment]
Update: I found actually problem, A real problem. if some state have resolve function it will be freeze ui. I don't know why because I never met before. I working with resolve many time only error form server will make resolve and ui will freeze. I ran "rails s -e production" is work normal but on real server not working
