### ISSUE TITLE
uirouter/angularjs dependency tied to 5.0.3

### ISSUE THREAD

**Issue by jmlopez-rod** [angular-ui/ui-router#3473]
uirouter/angularjs still has uirouter/core@5.0.3 as a dependency instead of newly released one:

https://github.com/angular-ui/ui-router/blob/0ac932a285a7a99ef195b44c2a50c026c36bb338/package.json

```
"dependencies": {
    "@uirouter/core": "5.0.3"
  },
  "peerDependencies": {
    "angular": ">=1.2.0"
  },
```

Can you use the `^` so that npm can download the newest version of angularjs/core? I'm having an issue with the views and I'm hoping the newest release (5.0.4) fixes it. Thanks.

EDIT:
Just noticed that `yarn.lock` is not in the `.npmignore` file, same goes for `rollup.config.js`. Some files just don't seem to be necessary for the published version.
![screen shot 2017-06-15 at 5 09 31 pm](https://user-images.githubusercontent.com/1810397/27203887-97a65792-51ed-11e7-848d-0a0eb08eb20f.png)

**Comment by christopherthielen** [comment]
Each *released version* of uirouter/angularjs is tied to a specific version of uirouter/core.  

It is bad for users to installed the same version of uirouter/anguarjs one day, but see different behavior when they install the exact same version at a later date (due to changes in core)

To get fixes from core into uirouter/angularjs we need to release a new version of uirouter/angularjs

**Comment by jmlopez-rod** [comment]
Thank you stale bot, i think this is no longer needed, i'll close it up for you.
