### ISSUE TITLE
Clarify bundles for core/angular js (link in notice broken)

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3486]
There is a notice in the `angular-ui-router.js` bundle which states that it is now recommended to include the core bundle separately instead. This points to a non-existing URL (http://ui-router.github.io/blog/angular-ui-router-umd-bundles)

Can you please fix the URL and/or clarify what the preferred way of bundling is?

Do we manually include a dependency on `@uirouter/core`? If so, how is versioning tied? Core is at master version 5.x wherease angularjs is only at 1.x. Are they somehow linked or do they follow the same major/minor/patch cycles?

Or do we rely on it being a dependency of `@uirouter/angularjs`? If so, how do we prevent issues like https://github.com/angular-ui/ui-router/issues/3473? What if the folder structure chances?

And any particular reason that angularjs bundles are sitting in `release` and core bundles in `_bundles`?

**Comment by christopherthielen** [comment]
Here's the correct link: https://ui-router.github.io/blog/uirouter-for-angularjs-umd-bundles/

The short version is: 
- Using npm+webpack? Don't do anything, it's all automatic
- Using npm? The dep on `@uirouter/core` is fetched automatically
- Not using npm? The dep on `@uirouter/core` can be found in the `@uirouter/angularjs` `package.json`.
- Using something to concat bundles? Prefer concating `ui-router-angularjs.js` and `ui-router-core.js`, but `angular-ui-router.js` will work as it always has.

> Do we manually include a dependency on @uirouter/core?
Not if you're using `npm`

> If so, how is versioning tied? 
The [`package.json` for `@uirouter/angularjs`](https://unpkg.com/@uirouter/angularjs@1.0.5/package.json) lists a dependency on `@uirouter/core`

> Are they somehow linked or do they follow the same major/minor/patch cycles?
Linked by package.json.  Core is used by numerous other projects and has its own lifecycle.

> If so, how do we prevent issues like #3473?
That's not an issue from my perspective.  The behavior of a specific version of `@uirouter/angularjs` should not change depending on when it was installed.  In other words, we want a specific version of `@uirouter/angularjs` to be permanently tied to a specific version of `@uirouter/core`.

> What if the folder structure chances?  And any particular reason that angularjs bundles are sitting in release and core bundles in _bundles?

The reason `angularjs` has a `/release` dir and the rest of the projects have `_bundles` is because changing the folder structure affects users downstream, and the `angular-ui-router` project has historically put its bundles into `/release`.  So instead of changing `@uirouter/angularjs` folder structure, we just grandfathered `/release` in as the bundle directory.
