### ISSUE TITLE
onEnter hook executed multiple times

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3543]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

I _think_ this is a bug, but maybe there's a reason for it.

See http://plnkr.co/edit/6EVBkon3JFHdkGXgMwVs?p=preview

If you open the console, you can see some log output. You can see that both the wildcard onEnter hook and the explicity `to: 'foo'` onEnter hook are called twice when you click the link to the `foo` route.

Why is this the case? You'd expect this hook to only be called once per transition?
This is the log output:

```
Transition #0 r0: Started  -> "Transition#0( ''{} -> 'foo'{} )"
onEnter
onEnter to FOO
onEnter
onEnter to FOO
Transition #0 r0: <- Success  "Transition#0( ''{} -> 'foo'{} )", final state: foo
```

In my production app it's even worse, with the same onEnter hook being called 4 times in the same transition cycle. I'm really curious why.

**Comment by adamreisnz** [comment]
I couldn't figure out why it's called multiple times, but I discovered that it's the exact same `transition` object passed to the hook every time, so I applied a property to it once the hook finished and added a check at the start of the hook to check for the presence of this property and not execute the code again.

I really hope I don't have to create that kind of logic for all of my hooks though, because I am using them quite extensively...

**Comment by adamreisnz** [comment]
It only seems to happen for the `onEnter` hook in particular, the other hooks are called only once:

![image](https://user-images.githubusercontent.com/490562/31052224-041a28b8-a6da-11e7-8e62-860c56288993.png)

**Comment by adamreisnz** [comment]
I think the `onEnter` hook is called for every single state in the hierarchy, e.g. `parent route -> child route -> grandchild route`. Is this observation correct?

If so, why is this the case? It seems rather redundant, as you only really enter one state, which may or may not have a parent state.

If this is intended behaviour, can you somehow distinguish between the different states using the hook criteria? E.g. to ensure the hook is only applied on the grandchild state?

**Comment by dreamoftrees** [comment]
Hmm experiencing the same behaviour and it's a little confusing. Thanks for your solution tip @adamreisnz

**Comment by asder707** [comment]
I have similar problem whit  `$transitions.onStart` and i cant solve it.
The transition ejecute all hook registered previous

**Comment by SirDarquan** [comment]
I just ran into this same problem but I came from a slightly different angle. You are correct that onEnter is running for each state in the hierarchy and I believe that was intended and correct behavior. The reason you're not getting what you seem to want is because you created a hook that asks for any transition into the onEnter phase. If you only want the grandchild hook you need to either add the hook directly to the onEnter property in the state definition or create the hook specifically for the state in question.

I also agree with you that there needs to be something specifically for the onEnter/onExit/onRetained hooks that specifies which state it is talking about if you've chosen to skip to an ancestor state. Maybe @nateabele can tell us if adding a $current to the transition object is feasible that will be available only during state level transition hooks referencing the specific state that is being entered/retained/existed?

**Comment by adamreisnz** [comment]
> If you only want the grandchild hook you need to either add the hook directly to the onEnter property in the state definition or create the hook specifically for the state in question.

I was under the impression that I'm doing that, with stating `{to: 'foo'}` in the onEnter hook rules.

By my understanding, this should only execute this hook for the `foo` state, not multiple times for each of it's parent states as well.

I haven't tried adding the hook in the onEnter property of the state, will see if that has an effect.

**Comment by scooper91** [comment]
Is there any update on this issue?

We're seeing the same issue but with the `onExit` hook.  When we're exiting two states, we're getting into the `onExit` hook twice (fine), but both have the same `from` and `to` states (see example [Plunker](https://embed.plnkr.co/R3FdEQfaJumCBNlvETtt/)).

**Comment by tonybrasunas-sighten** [comment]
Having this issue with `onStart` as well. Any update here would be helpful. 

Getting around it with a similar hack to the above:
`transition.checked = isUndefined(transition.checked) ? 0 : transition.checked + 1`

**Comment by adamreisnz** [comment]
Still an issue in the latest version of ui-router, just ran into it again

**Comment by n0is** [comment]
I've the same problem for onStart hook but not all the time.  For some pages of the app, it runs only one but for some others, twice (however, it's always the same).   And it happens only when doing a browser refresh.
Exemple: 
* app start -> go to login
* login -> see page of projects
** everything's fine and onStart is run only once per page
* refresh the projects page
** onStart is fired twice

**Comment by justinwrobel** [comment]
Not sure if it helps but I was able to resolve this issue by excluding the nodes by using the Criteria Object. In my example, I excluded about which was is the only parent.
For instance in the @scooper91's plunk ([fork w/changes](https://plnkr.co/edit/NrOQdRFNHmzFImok1l1d)):
```
$transitions.onExit({exiting: (state) => !['about'].some((i) => i === state.self.name)}, function(transition) {...
```

While workable, I wish there was a way to easily select just children or parent nodes or something.

**Comment by christopherthielen** [comment]
This behavior is expected and is by design.  

### Multiple nested states are entered

In the initial bug report, the `onEnter` hook is run twice when `foo` is initially activated.  This is because the `onEnter` hook is invoked _for each state that is entered_ (both `portal` and `foo` states were entered). 

This animation from the [transitions guide](https://ui-router.github.io/guide/transitions) visually demonstrates this aspect:

![multiple-entered-exited](https://user-images.githubusercontent.com/2053478/70642509-2bdb8b80-1bf4-11ea-9192-ffa9af1ca203.gif)

### Transition hook criteria object

When a transition hook is registered, a criteria object is provided.  The criteria object only selects a matching *transition*.  It does not indicate the *states* that the hook is invoked for.  

### onEnter hook behavior

The `onEnter` hook is a [State Level Hook](https://ui-router.github.io/guide/transitionhooks#state-level-hooks).  The `onEnter` hook is invoked for *each state that is entered* during the transition.

### The second argument is the state

The `onEnter`, `onExit`, and `onRetain` transition hooks take a `TransitionStateHookFn` callback.  The [TransitionStateHookFn](https://ui-router.github.io/core/docs/latest/interfaces/transition.transitionstatehookfn.html) is a function that takes two arguments: the *transition* and the *state*.  If you want to run a globally registered `onEnter` hook only for a specific state, then you should check the second argument in the callback.

**Comment by christopherthielen** [comment]
@adamreisnz

**Comment by adamreisnz** [comment]
Only 2 and a half years late, but thanks 😆
