### ISSUE TITLE
Dynamic (sync) resolvable added in `onEnter` hook not available in `onSuccess`

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3544]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.x

# Bug Report

#### Current Behavior:
http://plnkr.co/edit/u0JKQCIabRCixHJLmBbB?p=preview

See console log. The app errors with:

`Error: Resolvable async .get() not complete:"bar"`

#### Expected Behavior:
For `bar` to be available in the `onSuccess` hook, just like `foo`, because it's not async and there is no reason why it should not be available/complete.

Expected behaviour is for it to work, just as it works in the `onBefore` hook.

(FYI the reason I need it in the `onEnter` hook is because I'm relying on another global resolvable to create the new resolvable, which is only available in the `onEnter` hook.)

**Comment by adamreisnz** [comment]
@christopherthielen this issue is quite a big blocker for us, could you please have a look at what's happening or maybe provide some suggestions for a work around?

**Comment by adamreisnz** [comment]
In fact, it's also happening in the `onBefore` hook when browsing away from the state, and then going back to it. The `addResolvable` is called fine, but then in the subsequent `onSuccess` the resolvable is not available in the injector.

**Comment by adamreisnz** [comment]
You can test this by defining the resolvable (sync) and calling the injector on the same transition right after; that shouldn't error right?

```js
const module = {foo: 'bar'};
transition.addResolvable({
      token: 'module',
      resolveFn: () => module,
    });
transition.injector().get('module');
```

==> `Error: Resolvable async .get() not complete:"module"`

**Comment by adamreisnz** [comment]
When using `{when: 'EAGER'}` policy, the module is available in `onSuccess` and doesn't error. However, according to https://github.com/angular-ui/ui-router/issues/3060#issuecomment-252124772, LAZY resolves should *also* be available in `onSuccess` hooks.

**Comment by christopherthielen** [comment]
This does look like a bug.  The added resolve should be available in any (currently unentered) child states.  I have a [unit test for something similar](https://github.com/ui-router/core/blob/3f5d3bbf88721d93712727777989a87e977d98f9/test/transitionSpec.ts#L669-L677) but it's not catching this scenario.

---

A few things to note:

1) You can add a resolvable with pre-resolved data (not async) [using the `data` property](https://ui-router.github.io/ng1/docs/latest/interfaces/resolve.resolvableliteral.html#data):


[add pre-resolved values](http://plnkr.co/edit/u0JKQCIabRCixHJLmBbB?p=preview)
```js
const module = {foo: 'bar'};
transition.addResolvable({
      token: 'module',
      resolveFn: () => module,
      data: module,
    });
transition.injector().get('module');
```

2) The `Injector` has a `getAsync()` method which will return [a promise for the resolve](https://ui-router.github.io/ng1/docs/latest/interfaces/core.uiinjector.html#getasync).

[using async/await](http://plnkr.co/edit/yPeF8p6kCCdgRV1rWT1D?p=preview)
```js
    const injector = transition.injector();
    const foo = await injector.getAsync('foo');
    console.log(foo);
    const bar = await injector.getAsync('bar');
    console.log(bar);
```

[using promises](http://plnkr.co/edit/gtRW5fqzNIlLtQM74xXl?p=preview)

```js
    const injector = transition.injector();
    Promise.all([injector.getAsync('foo'), injector.getAsync('bar')])
      .then(results => { console.log(results[0]); console.log(results[1]) })
```

3) Resolves are assumed to be async by default.

> by defining the resolvable (sync) and calling the injector on the same transition right after; that shouldn't error right?

You can't do this unless you explicitly provide the `data` property to create a sync resolvable.

4) `EAGER` resolves are fetched [when the transition starts](https://github.com/ui-router/core/blob/3f5d3bbf88721d93712727777989a87e977d98f9/src/hooks/resolve.ts#L11-L26).  `LAZY` resolves are fetched [when the state they belong to is entered](https://github.com/ui-router/core/blob/3f5d3bbf88721d93712727777989a87e977d98f9/src/hooks/resolve.ts#L28-L44).

By adding the resolvable in `bar`'s `onEnter`, there is no further triggers to process the newly added resolvable (all states have been entered already).  This is essentially where the bug lies.  To prove the point, if we added another nested state `foo.bar` then [the resolve is indeed processed and ready in `onSuccess`](http://plnkr.co/edit/dhkJAtCavwtKHom2KwOT?p=preview) (also change the criteria objects from `to: 'foo'` to `entering: 'foo'`

**Comment by adamreisnz** [comment]
Thanks for looking into it and finding the bug, and also for pointing out `data` instead of `resolveFn`, I was looking for a simple property like that for sync data but must have missed it.

I've tried to change `resolveFn` to `data` in the (plunkr)[http://plnkr.co/edit/u0JKQCIabRCixHJLmBbB?p=preview] but that errors with:

![image](https://user-images.githubusercontent.com/490562/34285572-80f3e1a8-e73f-11e7-9e52-253fd41eff72.png)

Not sure if this is related to the bug you fixed or not.

**Comment by christopherthielen** [comment]
> Unless I'm expected to use both? But that doesn't make sense to me.

Although it doesn't make much sense, use both.  Maybe we can fix this in a future release.
