### ISSUE TITLE
Why @uirouter/core not install duding installation on @uirouter.angularjs  ?

### ISSUE THREAD

**Issue by mikeandersun** [angular-ui/ui-router#3578]
I update to  last version  1.0.11 in package.json :
` "@uirouter/angularjs": "1.0.11",`
and try to bundle  js libs with webpack :
```
import 'angular';
import 'angular-material';
import '@uirouter/angularjs';
```
. here is the error :
```
ERROR in ./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js
Module not found: Error: Can't resolve '@uirouter/core' in 'D:\myproject\node_modules\@uirouter\angularjs\release'
 @ ./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js 9:101-126
```
In the previous vesrion i had a @uirouter/core folder in  node_modules folder , but in new version @uirouter/core not created. 
Is there any breaking changes in this release?

**Comment by christopherthielen** [comment]
no known breaking changes in 1.0.11.  

The `package.json` for `1.0.11` includes a dependency on `@uirouter/core`: https://unpkg.com/@uirouter/angularjs@1.0.11/package.json

What version of `npm` or `yarn` are you using?  `npm` prior to 3.x is known to install dependencies [in a tree, instead of flattened](https://docs.npmjs.com/how-npm-works/npm3) which can cause the behavior you described.

I just tested this with npm 5.5.1 and it seems to work fine:

```
bash-3.2$ npm init --force >/dev/null
npm WARN using --force I sure hope you know what you are doing.
bash-3.2$ npm install --save @uirouter/angularjs@1.0.11

> @uirouter/core@5.0.11 install /Users/chris/t/node_modules/@uirouter/core
> node migrate/migratewarn.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @uirouter/angularjs@1.0.11 requires a peer of angular@>=1.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN t@1.0.0 No description
npm WARN t@1.0.0 No repository field.

+ @uirouter/angularjs@1.0.11
added 2 packages in 1.307s
bash-3.2$ ls -la node_modules/\@uirouter/
total 0
drwxr-xr-x   4 chris  staff  136 Dec 20 15:35 .
drwxr-xr-x   3 chris  staff  102 Dec 20 15:35 ..
drwxr-xr-x  16 chris  staff  544 Dec 20 15:35 angularjs
drwxr-xr-x  12 chris  staff  408 Dec 20 15:35 core
bash-3.2$
```

Note that I have a `node_modules/@uirouter/angularjs` and a `node_modules/@uirouter/core`

Closing because this works as expected as long as npm is up to date

**Comment by toblender** [comment]
I ran into this issue as well.  
`import '@uirouter/angularjs';`

The tutorial material still says:
import uiRouter from 'angular-ui-router';
