### ISSUE TITLE
Facing issue with angular ui-router 1.0.5 and angular 1.6.5 in IE11 browser Ask

### ISSUE THREAD

**Issue by gopirajum** [angular-ui/ui-router#3579]
# ui-router is causing an issue in the IE11 browser, Everything is working fine in chrome, firefox, and even IE10. getting following error in the browser console.

#### Current Behavior:
```javascript
SCRIPT5022: [$injector:modulerr] Failed to instantiate module TestApp due to:
TypeError: Object.keys: argument is not an Object
   at _extend (https://example.com/scripts/vendor.09a8eb90.js:100012:9)
   at Anonymous function
```

I'm pasting the ui-router code here where exactly causing an issue.

```javascript
function _extend(toObj) {
    for (var i = 1; i < arguments.length; i++) {
        var obj = arguments[i];
        if (!obj)
            continue;
        var keys = Object.keys(obj);
        for (var j = 0; j < keys.length; j++) {
            toObj[keys[j]] = obj[keys[j]];
        }
    }
    return toObj;
}
```

Any guesses of why this happening would be greatly appreciated.

**Comment by christopherthielen** [comment]
I suspect one of the arguments to this function is `null` or `undefined`.  `_extend` is used extensively, so it's impossible to know what the root cause is without a stack trace (with sourcemaps so its not all `vendor.??????.js`)

 This could be a bug in ui-router, or in your code (sometimes ui-router uses your configuration as second/third arguments to this fn)

**Comment by christopherthielen** [comment]
Any updates?  Did you try debugging?

**Comment by mark-branchboston** [comment]
Just a note for others that run into this (because this is a top search result in google).

Issue was with my usage of a transition hook:
```$transitions.onSuccess("app.somestate.**", (transition) => {
    doStuff();
  });```

The first param should be an object:
```$transitions.onSuccess({ from: "app.somestate.**"} , (transition) => {
    doStuff();
  });```

Reference: https://ui-router.github.io/guide/transitionhooks

@christopherthielen Not sure if there is better way to have error checking around this but it was a convoluted road to find out that this is what IE11 was complaining about (Chrome/FF had no issue with it being a string)

**Comment by daerogami** [comment]
Just a note for others that run into this (because this is a top search result in google).

Issue was with my usage of a transition hook:

```
$transitions.onSuccess("app.somestate.**", (transition) => {
    doStuff();
  });
```

The first param should be an object:

```
$transitions.onSuccess({ from: "app.somestate.**"} , (transition) => {
    doStuff();
  });
```

Reference: https://ui-router.github.io/guide/transitionhooks

@christopherthielen Not sure if there is better way to have error checking around this but it was a convoluted road to find out that this is what IE11 was complaining about (Chrome/FF had no issue with it being a string)
