### ISSUE TITLE
Disable parameter inheritance in ui-sref directive

### ISSUE THREAD

**Issue by tobigit** [angular-ui/ui-router#376]
Is there a way to disable parameter inheritance in ui-sref directive?
I would like to have a second parameter, like this:

``` html
<a ui-sref="contacts.detail({ id: contact.id }, {inherit: false})">{{ contact.name }}</a>
```

With the second parameter i could set the options for the method $state.go().

**Comment by janhartigan** [comment]
For reference, the way to do this is:

```
ui-sref-opts="{inherit: false}"
```

**Comment by msieurtoph** [comment]
This did not work for me ...
I had to use ui-sref="myState({myParam:null})" to get real uninheritance ...

My State was this simple : 

```js
        .state('releases', {
            parent:'root',
            url:'releases/:releaseId',
            templateUrl: 'views/view-releases.html',
            data: ...
        })
```

`releaseId` is optional. If not supplied, the page will get the last releaseId from localStorage (and update URL)

When I was using version `0.4.2`, I could use `ui-sref="releases"` to make it work ... 
Since I migrated to version `1.0.3`, it does not worked anymore. I got the following error message: 

> Transition Rejection($id: 0 type: 6, message: The transition errored, detail: Error: Param values not valid for state 'releases')

I tried `ui-sref-opts="{inherit: false}"` with no luck.
I had to use `ui-sref="releases({releaseId:null})` instead to get it working.

Any idea or explanation ?
Thx in advance.
