### ISSUE TITLE
Dynamically modifying state views

### ISSUE THREAD

**Issue by eahutchins** [angular-ui/ui-router#379]
I've got a use case for being able to alter the views associated with a state dynamically, after the state has already been defined. I also see some confusion between state and the views under a given state, it seems if you'd really like to use the views to allow reusable components (say a bunch of different types of graphs in a business dashboard app) you'd like to avoid having to define a new state for every possible permutation of view that the user might select. To clarify:

![nested views](https://raw.github.com/wiki/angular-ui/ui-router/MultipleNamedViewsExample.png)

Imagine the user had the ability to select which types of views are being used for the table and graph, but that this selection was transient and not something the designer wanted to be able to navigate to. Currently this seems really hard to get working with ui-router, what I'd like is to be able to do something like:

`$state.setViews({ 'viewname': { ... } })`

This also brings up the issue of why states can only have templates or views, but not both. What was the thinking behind this restriction (or is it only an implementation limitation)? The use case I'm working on would benefit from being able to populate the current state's template with reusable components in named views (as well as those of any parent state). Am I missing some big drawback to being able to do this?

**Comment by shanealsingh** [comment]
Any updates on this?

**Comment by wchavezsalinas** [comment]
@nateabele, @timkindberg Hey, beginner ui-router user here. This might be a dumb question and I'm not really sure if it's been mentioned. Are we able to pass in state parameters to this function so that the view that's rendered reflects a different set of data?

for example something like this...
```javascript
$view.load("view.name@state({num:10})", {
  templateUrl: "/partials/foo.html",
  controller: "MyController"
});
```
as opposed to 
```javascript
$view.load("view.name@state", {
  templateUrl: "/partials/foo.html",
  controller: "MyController"
});
```
I was looking at the view.js file and I saw that it supports template parameters, but I'm not really sure if this is what I'm thinking of.

Any input would be appreciated.

**Comment by nateabele** [comment]
@wchavezsalinas You can pass parameters, but not like that. See https://github.com/angular-ui/ui-router/blob/master/src/view.js#L31-L34

**Comment by plong0** [comment]
wondering if there was ever a clear answer on this?

$view.load doesn't seem to do anything in v0.2.15. I tried it with fully qualified view names ('view.name@state').  I even tried updating to 1.0.0alpha0 and $view.load gives the error "viewConfig.hasTemplate() is not a function"

I tried using `var state = $state.get('view.name');` and then altering `state.views`, but that doesn't work either.

All I'm trying to do is change the template property after the state has been defined ...  for my use case it doesn't matter if it's in config or run, but run seems easier because we have the $state and $view services there.

**Comment by christopherthielen** [comment]
Changing a template string at runtime is best done with templateProvider

**Comment by plong0** [comment]
Thank you.  But is there any way to change the templateProvider function at runtime?

I know I could refactor the code so the original templateProvider resolves a different template, however in this case it would be much simpler if I could simply change the templateProvider function.

**Comment by TheJson** [comment]
Hello @nateabele @christopherthielen I have similar situation. I want to chage the content of named view at runtime or similar. This is my question: 
http://stackoverflow.com/questions/42657489/angular-ui-router-change-content-of-named-view
I tried using $view.load() but not working. I'm using ui-router 0.2.18. Thanks
