### ISSUE TITLE
Latest build does not work with ngCloak

### ISSUE THREAD

**Issue by programmerdave** [angular-ui/ui-router#487]
If you apply an ng-cloak directive to ui-view, it doesn't remove ng-cloak when loaded. Any ideas?

**Comment by armyofda12mnkeys** [comment]
Question about this for old angular 1 code Im supporting (using "angular-animate": "1.4.9" and "angular-route": "1.4.9",)...
If ui-view is being animated so usually the old ui-view is fading out, while the new ui-view is being faded in (im using animations to fade between Question#1 and Question#2 in a questionnaire)... Is there a way to stop that very 1st router animation so that the 'old ui-view fading out' doesn't even occur, it shouldnt be shown at all because it just shows {{question-text}} for example. Putting ng-cloak onto the ui-view div element doesn't help as you said "it's not ui-view's job to remove the ng-cloak class". Is the angular-animation javascript supposed to help with this?
