### ISSUE TITLE
Redirect abstract states

### ISSUE THREAD

**Issue by blackjid** [angular-ui/ui-router#497]
Is there any way to redirect to another state when I try to load an abstract state?

``` js
.state('client', {
   url: '/client/:clientId',
   abstract: true
})
.state('client.details' {
   url: '/details',
   templateUrl: '/views/mytemplate.html',
   controller: 'ClientDetailsCtrl'
});
```

I'd like to redirect to the `client.details` state whenever I navigate to the url that match the `client` state

thanks

**Comment by rhutchison** [comment]
```javascript
$stateProvider
    .state('client', {
        url: '/client/:clientId',
        templateUrl: '/views/parent.html', // must have <div ui-view></div>
        controller: 'ClientDetailsCtrl',
        abstract: true
    })
    .state('client.default' {
        url: '',
        templateUrl: '/views/mytemplate.html'
    })
    .state('client.details' {
        url: '/details',
        templateUrl: '/views/mytemplate.html'
    });
```

**Comment by vdzundza** [comment]
Some directives used $state.go(parentState);  and they didn't know anything about states(abstract or not), so I think redirectTo feature should be implemented in ui-router

**Comment by mjrk** [comment]
+1 for a tested redirectTo feature

**Comment by Namek** [comment]
Use DSR from `ui-router-extras` and configure `deepStateRedirect.default` like here:
http://christopherthielen.github.io/ui-router-extras/#/dsr And don't make your parent state abstract.

**Comment by Toadskin** [comment]
The lack of a default on abstract states appears to be a glaring omission given its usefulness and the recurring demand for it.   Using "when" to redirect is not a direct solution and feels like a hack.  What developers are looking for is to $state.go('target') where 'target' resolves to an optional default, if set, given an abstract target. Otherwise we are messing with URLs rather than states as a work-around.

**Comment by pduey** [comment]
There is a default on the abstract state, and there are a couple of options for implementing (per the wiki), and they both work *except* when you use ui-sref. I.e., if you type the url to the abstract state into the browser, it correctly loads the default child state. But, if you click on a link that goes to the abstract state, it's gets the error. Why would the two things behave differently when it's the same URL?

**Comment by nateabele** [comment]
@pduey That shouldn't happen. Open a new issue and post a plunkr that demonstrates it.

**Comment by filipesilva** [comment]
I'm having the issue described by @pduey as well. I'll put up a new issue with plunkr.

**Comment by filipesilva** [comment]
As a note here, having the `ui-sref` links not work with the FAQ solution also means that `ui-sref-active` does not work.

**Comment by zenpuppet** [comment]
I have been using the ui-router in a tree menu that generates from a JSON object. 

I was having a horrible time with this, this being the ui-sref not working and the FAQs saying that it should work. At the end of it all, I created some code that appended .index onto any parents that I wanted to load in an "overview" child page. I will be posting the entire solution up in a couple days. It's a wreck at the moment otherwise i would upload it now. It's fairly useful for roughing together prototypes that need a fairly complex, multi-level tree structure.

**Comment by nateabele** [comment]
@zenpuppet That sounds like something worth adding to the wiki FAQ.

**Comment by zenpuppet** [comment]
I have just uploaded the code. I am doing a bit of polish on it so its slightly more robust. I am fixing my code so you can define if you want a parent to use just the <div ui-vew></div> as a template or if you actually have a templateUrl. I also want to fix it so that in the parent node you can define a particular child as the default subview. I'm doing that today. If you are interested in seeing the code in its current state let me know.

**Comment by nateabele** [comment]
@zenpuppet No, that's fine (thanks for asking). Ping when it's polished.

**Comment by khullah** [comment]
@zenpuppet have you advanced on this?

**Comment by jeremysawesome** [comment]
This solution works and it needs more exposure:
https://github.com/angular-ui/ui-router/issues/1431#issuecomment-222589705
