### ISSUE TITLE
Back Button Support?

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/ui-router#52]
It would be absolutely amazing if we could detect when the back button is pressed, using `window.onpopstate` on newer browsers.

Then once ngAnimate is in, we could have transitions between pages that look different depending on forward or back (eg github file browser, any mobile app).

I'd be willing to work on this, has anyone else done anything with this?

**Comment by mwager** [comment]
What about adding a variable to the "event" parameter of "stateChangeStart/stateChangeSuccess" which tells the developer if the event was triggered programmatically or not?

Something like:

```
$rootScope.$on('$stateChangeStart', function(event) {
```

1. $state.go 'some_where'  -> event.isTriggeredProgrammatically === true
2. back button clicked -> event.isTriggeredProgrammatically === false

**Comment by cudasteve** [comment]
Here's my use case.  I think it's one of the more common ones.  I'm listening for $stateChangeStart to prompt for "are you sure?" to prevent leaving unsaved edits.

If the user clicks a link to leave the page, using $stateChangeStart, I can prompt them, get their response, and cancel the navigation if the user dictates.  Then if they click the link again and this time say "OK I'd like to leave" I can just let them go through.

However, if we try that same workflow with the back button things are a little different.  When they hit the back button, you can see the URL change to the toState.  After prompting I can call event.preventDefault() to prevent them and UI-router will put the correct URL back, but the page they were originally trying to go back to gets removed from the browser's history.  So if they hit back again and accept this time, it'll send them back two pages.

@mwager's suggestion would allow me to get around this relatively nicely by allowing me to essentially check for whether they hit the back button or not.  If they did, I can just call history.pushState({}, ''), which will quickly re-save the page they were trying to go to (because the URL has already changed) before event.preventDefault() pushes the original state back up on top.

For now, I'm probably going to compare `$state.href(fromState, fromParams)` with `$location.path()` to determine if the back button was pressed.  That should get me by but isn't very elegant.

....if that makes any sense.

It'd be really nice to have a "here's how you prevent the user from leaving a page with unsaved edits" best practice writeup for UI-Router that covers all the ways to leave a page state-change, link-click, back button, refresh button, and close button.  ...oh and shoot what about the FORWARD button???

**Comment by cudasteve** [comment]
FYI, in case anyone needs something like this in the future, this is what my final solution looks like that accounts for link-clicking, state changes, back button, reload button, and close button.  The other two (forward button and history item selection) are a lot harder I think.

        // State change, link clicking, and back button
        $scope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
            if (!$scope.noSave  && hasChanged()) {
                if (confirm("Are you sure?\nUnsaved changes will be lost.")) {
                    $scope.noSave = true;  // so subsequent redirects in this same state change don't ask again
                } else {
                    if ($state.href(fromState, fromParams) !== $location.path()) {
                        // Clicked back button
                        history.pushState({}, '');  // Requires HTML5 pushState API
                    }
                    event.preventDefault();
                }
            }
        });
        
        // Refresh and close buttons
        $window.onbeforeunload = function () {
            return hasChanged() ? 'Unsaved changes will be lost.' : null;
        };
        $scope.$on('$destroy', function() {
            $window.onbeforeunload = undefined;
        });

**Comment by floyd-may** [comment]
This StackOverflow answer seems to be far more complex than what @cudasteve has posted:

http://stackoverflow.com/a/22402285/170407

Is the SO answer overkill?

**Comment by cudasteve** [comment]
@floyd-may I think the SO answer is answering something slightly different than my solution.  My solution is just a way to implement "are you sure?" prompts when leaving states using the back button.  My solution assumes the previous states have already been added to the browser's history via URL changes, whereas the SO answer seems to be about how to leverage the back button for navigation even without URL changes.

And neither of those things are the full scope of what I think is being discussed in this issue anyway.

**Comment by amypellegrini** [comment]
My case involves 404 redirection on certain routes. When a user (for whatever reason not relevant here) gets a 404 page, going "back" navigates to the same route that redirected to 404, which ends up again in a 404 page. I've tried to prevent pushing state for these cases, so the URL is not recorded in history, but fur some reason `$state.go('notFound', {}, { location: false })` is not doing the trick, I'm not sure if this is actually a bug.
