### ISSUE TITLE
How to avoid big state config function in large applications

### ISSUE THREAD

**Issue by ffesseler** [angular-ui/ui-router#54]
I'm writing a large app, up to  4 level deep navigation with URL routing.
I've declared all states in the main app module. That means I've something like :

```
angular.module('myApp').config(function ($stateProvider) {
$stateProvider
.state("toplevelfeature", { url : '/topleavelFeature'...})
.state("toplevelfeature2", { url : '/topleavelFeature2'...})
.state("toplevelfeature.midfeature", { url : '/midFeature'...})
.state("toplevelfeature.midfeature2", { url: '/midFeature2...})
.state("toplevelfeature.midfeature.anothernestedfeature", { url: '/anothernestedfeature...})
});
```

I've already defined a dozen of states and I know I will have to handle at least 50 other ones. Obviously, I'd like to split state definitions to avoid a giant config method!
For now, each feature get its own module so I thought I would be able to do something like this :

```
angular.module('anothernestedfeature').config(function ($stateProvider) {
$stateProvider
.state("toplevelfeature.midfeature.anothernestedfeature.home", {...})
.state("toplevelfeature.midfeature.anothernestedfeature.detail", {...})
.state("toplevelfeature.midfeature.anothernestedfeature.other", {...})
});
```

Unfortunately, when I do that, there is an error saying parent state (here: toplevelfeature.midfeature) can't be found.

Any idea about this? (Sorry If I'm not on the right place to ask this but I didn't find any information about where to ask these kind of questions)

**Comment by lucassus** [comment]
Here you could find my proposal. It's based od es6 modules
https://github.com/lucassus/angular-webpack-seed/blob/ce4e9b91ce9ed47ca74073d754b0cbacff8cb65f/src/app/contacts/contacts.config.js

**Comment by ProLoser** [comment]
I believe states don't have to be declared in order anymore as long as the entire ancestry exists before entering the state. Or linking to it?

I add states to every module, I don't declare them in one place in any capacity. I also further attempt to decouple the ancestry by mixing in the use of a parent property. Children within a module use dot notation and the top route of the module uses a parent property. This way you can easily refactor your modules without having to update many different places. I have nesting modules and parent modules import child modules.

I also don't think I see a big benefit to exporting just the state definition because you shouldn't be importing the file if you don't want the state defined.
