### ISSUE TITLE
Branch angular-1.2 doesn't accept ui-view inside an ng-if

### ISSUE THREAD

**Issue by swallez** [angular-ui/ui-router#552]
I'm currently using ui-router 0.2.0 with Angular 1.2-rc3 and wanted to try the angular-1.2 branch to use the new animation stuff.

In this branch, the ui-view directive doesn't work if it's a child of an ng-if directive: the view can't find its parent and so its name is not correctly resolved.

I tracked this down to `var parent = element.parent().inheritedData('$uiView')` in viewDirective.js: when this code is called, the element is in a DOM document fragment created by the ng-if directive, and so the parent view can't be found.

I haven't been able to understand why with ui-router 0.2.0 the document fragment has already been inserted in the main DOM when we reach the equivalent code. Could this be related to the ui-view directive not having `transclude: true` in the angular-1.2 branch?

Here's a plunker showing the issue: http://plnkr.co/edit/l97kW2LCcpK2sOjFuoUS?p=preview - you can switch between 0.2.0 and the current angular-1.2 branch by changing the comments in `index.html`

**Comment by paulbhartzog** [comment]
ui-view still does not work inside of ng-if

**Comment by eddiemonge** [comment]
Unfortunately, the issue tracker for this has gotten a bit out of control. In the interest of weeding out real bugs and feature requests, this issue is being closed. If you feel like the problem reported is still valid, please add a comment saying it is still affecting you. We will reevaluate it and if it is valid we will reopen it.

You can/should/please also try the new [feature-1.0 branch](https://gist.github.com/eddiemonge/f9f8cb0a9dc7f42515db) that is in development to see if it fixes your issue. Keep in mind this is still in development but it is the direction the project is heading. If you want to file a ticket against this branch, use the format `1.0: (subject)` for the subject.

You can also try asking on [StackOverflow](http://bit.ly/UIR-SOF) if this is an implementation issue rather than a bug in ui-router.

Thank you for supporting and contributing to the project.

**Comment by jlynchISM** [comment]
The key here is to move the variable to $rootScope.  
The ui-router loads the PARENT view before the CHILD view.  Now in order to send information from the CHILD back to the PARENT you need a globalized binding, which is found in $rootScope.

Thanks.  The plkr told everything I need to know.
