### ISSUE TITLE
event $viewContentLoading doesn't seem to work

### ISSUE THREAD

**Issue by dmatteo** [angular-ui/ui-router#685]
It seems I'm unable to get the `$viewContentLoading` fired.

The doc says it's fired by the `$rootScope`, while in the example listen to the `$scope`

```
$scope.$on('$viewContentLoading', 
function(event, viewConfig){ 
    // Access to all the view config properties.
    // and one special property 'targetView'
    // viewConfig.targetView 
});
```

I've tried both, but I couldn't catch any event

**Comment by mladenp** [comment]
For me too $viewContentLoaded is not firing. How the heck should i know that my view is ready?

**Comment by nateabele** [comment]
Still waiting on a plunkr that demonstrates the issue.

**Comment by laurynas-karvelis** [comment]
+1

**Comment by 0xae** [comment]
+1

**Comment by lc-nyovchev** [comment]
+1

**Comment by 111crb111** [comment]
Not firing, too :(

**Comment by metamatt** [comment]
I think the problem is that the `$viewContentLoading` / `$viewContentLoaded` events are not always paired.

`$viewContentLoading` is emitted from `$ViewProvider.load` which is called from `resolveViews` as a side effect of state transition.

`$viewContentLoaded` is emitted from `<ui-view>`'s `updateView` whenever it needs to update (as a side effect of initial instantiation, `$viewContentLoading`, or `$stateChangeSuccess`), after it runs the controller.

The problem is if you have nested views and states such that you can update views without activating new states (such as transitioning from a child state to a parent state, which involves only state DEactivation) then you get `$viewContentLoaded` without `$viewContentLoading`.  [Plunkr here](http://plnkr.co/edit/66tLGy?p=preview) (all the output goes to the devtools console so open the console, then click back and forth between "enter state 1" and "enter state 2" to verify you get matched pairs of loading/loaded events, then click "enter root state" and you'll see only a loaded event but no loading event.)

**Comment by metamatt** [comment]
I also note in real usage in my real apps that when `ui-view` receives a `$viewContentLoading` event, it always seems to follow the `return; // nothing to do` path in `updateView()`. Then immediately after that, it receives a `$stateChangeSuccess` event which triggers another call to `updateView()` which is not a no-op. That is, it never does anything with the `$viewContentLoading` event, and its behavior is always driven directly from `$stateChangeSuccess`.

Proposal 1: leave `$viewContentLoading` how it is for backwards compatibility, but add a second event (`$viewContentReallyLoading`?!) that is emitted inside `updateView` before the `$transclude` call, always paired with `$viewContentLoaded`. (Use case: my test harness wants to know when views are instantiating so that if a controller throws an exception, it knows which view to blame. So I really want a reliable "loading" signal.)

Proposal 2: remove the existing `$viewContentLoading`, and just emit `$viewContentLoading` from `updateView` before the `$transclude` call. This might break people who depend on the current behavior, but barring an explanation I don't currently understand, this behavior makes more sense.

I'd favor proposal 2 because I don't know what the meaning of the existing `$viewContentLoading` site really means to external client code (since it doesn't reliably happen), the internal consumer of the current `$viewContentLoading` event doesn't seem necessary, I think the other site is a more reliable indicator of what external client code wants to know, and I think `$viewContentLoading` is the right name for the event that's paired with `$viewContentLoaded`. But it's very possible I'm missing something about the current `$viewContentLoading` emit site.

I'd be happy to submit a PR for either of these proposals if the main contributors would nominate their preference.

**Comment by metamatt** [comment]
A couple other differences I note between `$viewContentLoading` (in 0.2.15) and `$viewContentLoaded`:

- `$viewContentLoading` is broadcast down from the root scope, `$viewContentLoaded` is emitted up from the view scope
- I didn't prove it in that plunkr but I'm guessing since "loading" is sent from the resolve-state path, and "loaded" is sent from the view-update path, if one state maps to multiple views, you get one "loading" event and multiple "loaded" events
- `$viewContentLoading` comes with an "options" parameter (which doesn't actually seem to include the name of the view that's loading), `$viewContentLoaded` does not

Again if there's a need (for backwards compatibility or for internal reasons I don't understand) for the current `$viewContentLoading` behavior (broadcast on the root scope once per state transition and only if notify was specified and it needs to include the `options` parameter) then I suggest we keep it and add another event which is paired with `$viewContentLoading` (emitted on the view scope once per view update); that's roughly my proposal 1 above; if there's no such need then my proposal 2 seems simpler and cleaner.

@nateabele please note the new plunkr in response to the plunkr-please label, and I'm curious what you think of this analysis and the proposals.

**Comment by metamatt** [comment]
I updated [the plunkr](http://plnkr.co/edit/66tLGy?p=preview) to demonstrate that if one state has two child views, and a child state populates both those views, you get two "loading" and two "loaded" events, but if a child state populates only one of those views, you get one "loading" and two "loaded" events. The problem I understand is related to situations with multiple views defined across multiple states with inheritance. The inherited views get a "loaded" event but no "loading" event.

**Comment by christopherthielen** [comment]
Metamatt Thanks for the analysis. I've never understood how people are using these events external to ui-router code. I think option #2 seems reasonable.

Can anyone else speak up if they are using viewContentLoading in some meaningful way and would object to proposal #2?

That said, Nate is revamping the transition to view interaction, and these events are likely going to be deprecated or removed completely in 1.x.

**Comment by OnkelTem** [comment]
To those who requested use cases — take a look at my original issue:  https://github.com/angular-ui/ui-router/issues/2403 and [finally] working example: http://plnkr.co/edit/ED0SGYyJerO1kaNDCwGv?p=preview

This requires the patch from: https://github.com/angular-ui/ui-router/pull/2003

**Comment by nateabele** [comment]
@OnkelTem I'm not sure I follow. #2003 has been merged. Is there something further to do here?

**Comment by OnkelTem** [comment]
No actually, I just leaved a message for those seeking additional information.

**Comment by nateabele** [comment]
Ah, okay. :smile: Thanks!
