### ISSUE TITLE
RFC: support URL fragments in ui-sref

### ISSUE THREAD

**Issue by beyang** [angular-ui/ui-router#701]
Proposal is to support \# URL fragments/hashes in ui-sref.  So you could do:
`<a ui-sref="mystate(myparams)#myhash>...</a>`

It appears that `$state.go(href)` already supports having a hash in href, so all this would require is making a change to the ui-sref directive (make it parse the hash and then pass this to $state.go).

**Comment by cryode** [comment]
For anyone else struggling with this particular issue, here's how I went around it:

```js
angular.module('app').config(['$provide', function ($provide) {

  /**
   * Extend the UI Router $stateProvider, adding the ability to specify an
   * anchor hash as a parameter in the ui-sref directive.
   */
  $provide.decorator('$state', ['$delegate', function ($stateProvider) {

    // Save the orignal function for generating a state's URL.
    var $stateHref = $stateProvider.href;

    // Create our extended function.
    $stateProvider.href = function href(stateOrName, params, options) {
      var hash = '';
      params = params || {};
      var hashParam = params['#'];

      // Check if the anchor parameter was specified.
      if (typeof hashParam !== 'undefined') {
        // Ensure hash parameter is a string and not empty.
        if ((typeof hashParam === 'string' || hashParam instanceof String) && hashParam.length) {
          hash = '#' + hashParam;
        }

        delete params['#'];
      }

      // Return the original parsed URL with the hash appended.
      return $stateHref(stateOrName, params, options) + hash;
    };

    return $stateProvider;
  }]);

}]);
```

[`$state.href`](https://github.com/angular-ui/ui-router/blob/0.2.13/src/state.js#L1273-L1294) is where the state identifier / params / options are parsed into a path (as best as I can tell, anyway). The code is pretty easy to read, but the workflow is pretty much:

1. Original function is saved, so it can be used again (not sure if there's a more OOP way to do this -- thoughts?)
2. Checks if there is a `#` parameter supplied. If so, save its value, then remove it from the params object.
3. Generate the path using the original function.
4. Return the generated path with the anchor appended.

This is used by simply specifying a `#` parameter as part of your `ui-sref` directive:

```html
<a ui-sref="my.state({ id: Model.id, '#': IDToScrollTo })" class="btn">
```

**Comment by mismith** [comment]
@cryode HTML5 user here. Looks great and technically works—in that the href tag gets filled with the proper #-having URL—but the problem is if a user clicks this link ui-router ignores the changes made and moves to the non-#-having URL anyway, essentially rendering the changes useless. I think there needs to be some deeper integration into ui-router, primarily in where it generate the string it'll replace the location bar URL with via HTML5

**Comment by cryode** [comment]
@mismith Thank you for the feedback with HTML5! I actually realized not too long after making this post that the above really only affects the URL generated with `ui-sref`, and not much else (as you've unfortunately discovered).

The problem lies with how UI router generates and handles URL parameters (both URI segments and search params as a whole). The process is done in a few places, and the code to do such is duplicated, rather than performed in a central location. I haven't taken the time to confirm if that is done with good reason, or is simply an oversight. Either way, the solution was far beyond implementation in the application level, and more than likely will need to be done on UI Router's end.

I will try to reply with the specifics of where the fragment breaks down on both sides (generation and consumption), and see if I can't work with someone here (a core contributor or otherwise) to get us to a working solution.

**Comment by mismith** [comment]
That mirrors what I found when I looked into it myself. I'd be happy to help but `ui-router` is a pretty large project and I don't wanna screw anything up.

I know @nateabele offered to help coach a bit in #1455... :)

**Comment by cryode** [comment]
That's good news! Maybe I'll spend one of my evenings here putting together at least a recommended solution. Maybe not a full blown PR (I'll have to see what UI Router prefers re: PR format, code), but at least work with a couple of you to move this forward!

**Comment by mismith** [comment]
I'm digging into things a bit over at https://github.com/angular-ui/ui-router/pull/1187 too

**Comment by slownslower** [comment]
For the purpose of supporting URL fragments as in original request:
```
 <a ui-sref="mystate(myparams)#myhash>...</a>
```
would using ui-sref-opts work?
http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref
Look up the "Parameters" table within the page.

**Comment by kikar** [comment]
Any news?

**Comment by slownslower** [comment]
Its supported.  You need to download ui-router v0.2.14.

Refer to this https://github.com/angular-ui/ui-router/pull/1867.  The syntax is {'#': 'frag'}

**Comment by samguergen** [comment]
These workarounds are hacks that really shouldn't take that many lines of code. Any chance to add the ui-sref="nav#anchor" feature? It's really one of the perks of traditional <a href=""> and a **major** thumbs down if ui-router can't feature it...
