### ISSUE TITLE
RFC: Nested state support for ui-sref-active

### ISSUE THREAD

**Issue by MrOrz** [angular-ui/ui-router#704]
It is mentioned in #635 and #19 that `ui-sref-active` will support nested state in the future, but I could not find the details discussed anywhere. As I browse the current source code, I found that it is actually not hard to achieve, and that it would seem redundant if I create another directive just for supporting nested states.

Since I need this feature right away, I've implemented a quick and dirty way to meet my need: when an extra html attribute `ui-nested` is present, `ui-sref-active` would use `$state.includes` instead of strict equality on the states.

Demo: http://plnkr.co/edit/CWUy3T0M7dTap75hASkk?p=preview

This can be achieved by merely changing 1 line (yeah I'm only capable of making a modification <= 4 lines... :P)
https://github.com/MrOrz/ui-router/compare/ui-nested

Hope that through this little dirty hack, we can initiate a discussion on how this function should be properly implemented.

**Comment by chbrown** [comment]
Just to clarify to anyone coming to this thread late, like me, from an old-ish version of ui-router: the feature described in this issue is now implemented in `ui-router`, at least in the current version (0.2.13).

The old `ui-sref-active` behavior is replaced by `ui-sref-active-eq`, and the new [`ui-sref-active`](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active) applies its values as class names whenever the corresponding `ui-sref` is a ancestor of the current route.

I use a hierarchical ui-router paradigm in my app, with lots of abstract states, so I have a nav bar that looks like this:

    <nav>
      <span ui-sref="admin.administrators" ui-sref-active="current" class="tab">
        <a ui-sref="admin.administrators.table">Administrators</a>
      </span>
      <span ui-sref="admin.experiments" ui-sref-active="current" class="tab">
        <a ui-sref="admin.experiments.table">Experiments</a>
      </span>
      
    </nav>
    <ui-view></ui-view>

The nav's children, the spans, are not actual links (and those span's ui-sref states are abstract) but I want them to activate whether the user is on the .table or .new, or any other subroutes. Not entirely DRY, but it works!

**Comment by lekhnath** [comment]
@atesgoral 's solution worked for me. short and sweet, would like to thank for letting know about that.

**Comment by atesgoral** [comment]
@lekhnath You're welcome :)

**Comment by stryju** [comment]
the fix is in place, tho

**Comment by lekhnath** [comment]
I was actually trying to add an active class in `ionicframework's ion-item` directive and don't want to add span and anchors for just a purpose of adding active class, so for me atesgoral solution was best suit. If the same requirement came in web development then I should go with the newer (fix) approach.

**Comment by praveenkumararepalliGit** [comment]
@atesgoral Please provide a working example
Thanks for your help...

**Comment by praveenkumararepalliGit** [comment]
http://plnkr.co/edit/V67mToDSN0SbzaGJTHw2?p=preview 
 Here is working Example
