### ISSUE TITLE
Update URL silently

### ISSUE THREAD

**Issue by cburgdorf** [angular-ui/ui-router#852]
I'm investigating using/abusing the ui-router for a special scenario. today we have URLs such as:

`category/some-category/`
`product/some-product/`

We want to switch to more SEO friendly URLs which only make sense to humans but don't follow a pattern which a router could deconstruct.

E.g.

`/some/crazy/category`
`/some/crazy/product`

What this basically means is that we can't continue to have the URL being the driver and let the ui-router match it with a Controller.

However, the ui-router seems quite a good fit for such scenarios as it already allows you to manually switch states by just calling `$state.transitionTo('product')`. Now what I want is to update the `location` of the browser to an URL which I know at the point that I set the state.

To let code speak, this:

`$state.transitionTo('product', { location: 'some/crazy/product' });`

All this should do is transition to the given state and update the URL of the browser silently without causing further action.

If this might be possible with the `ui-router` as of today, I would appreciate any pointers. If not, would you accept a PR for such a feature?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by nmpribeiro** [comment]
Actually... I think we should look at combining translate and ui-router. Because, it makes sense for the routes to exist in a per language config file (same way as angular translation operates).

So... does anyone want to try to do that? Cause I have managed to change the url's per language, but then I always end up doing the workaround of firing $state.go({url1param: translated_param1}) which is actually not a good idea.

I would prefer to just update the url bar, since there's no need to change to another state. It's the same state with a different 'currentLanguage'.

How can I do that? Anyone?
