### ISSUE TITLE
templateUrl relative to webserver root and not <base> set on app

### ISSUE THREAD

**Issue by RoyceLithgo** [angular-ui/ui-router#976]
I've set <base href="/dev/myapp/"> and my state Url matching is working fine with relative paths defined in my states. The only thing that doesn't work are templateUrls, which are being loaded relative to the web server root and ignoring /dev/myapp base path set in index.html. 

The result is the same with or without html5mode.

**Comment by gflarity** [comment]
I'm seeing the exact same issue. I've never had this problem with ngRoute... 

I've resorted to doing something like this:
http://nozzle.io/devblog/relative-angularjs-modules/

I realize that there might not be resources to fix this, but can a maintainer/commiter confirm this is undesirable? I'm tempted to submit a pull request.

**Comment by npearson72** [comment]
+1

**Comment by nateabele** [comment]
I can see why you might expect this behavior, but the chain of delegation is `$state -> $view -> $templateFactory -> $http -> XHR`, and XHR does not respect the `<base />` tag, so this is really about two different things (since, as far as UI-Router is concerned, the `<base />` tag is primarily about your app's URLs).

Shortly, we will be switching to `$templateRequest` (which is also what ngRoute uses) so if you still have trouble after that, we can see about kicking it up to Angular core, but it _should_ work after that, or at least, be consistent with ngRoute.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by michelank** [comment]
+1
I'm now sure whether we're talking about the same issue, but I fell in something like it and I fixed using this (in typescript):

    export class UrlHelper {

        static rootPath = () => "/CR";
        static pathViews = () => UrlHelper.rootPath() + "/App/views/";

        static mapPath(url: string): string {            
            return url.replace('~', UrlHelper.rootPath);
        }

        static setRoute(url: string): string {
            return UrlHelper.pathViews()
                .concat(url)
                .concat(".html");
        }
    }
